<?php
namespace V5_5_1;
require_once \DirPath::get('classes') . DIRECTORY_SEPARATOR . 'migration' . DIRECTORY_SEPARATOR . 'migration.class.php';

class M00002 extends \Migration
{
    /**
     * @throws \Exception
     */
    public function start()
    {
        self::generateTranslation('not_found', ['pt-BR' => 'Não encontrado']);
        self::generateTranslation('age_restriction', ['pt-BR' => 'Restrição de Idade']);
        self::generateTranslation('info_age_restriction', ['pt-BR' => 'Deixe o campo vazio para nenhuma restrição. Caso contrário, insira a idade mínima para acessar o conteúdo']);
        self::generateTranslation('access_forbidden_under_age', ['pt-BR' => 'Acesso restrito abaixo de %s']);
        self::generateTranslation('option_enable_age_restriction', ['pt-BR' => 'Habilitar restrição de idade nas mídias']);
        self::generateTranslation('option_enable_user_dob_edition', ['pt-BR' => 'Permitir edição da data de nascimento']);
        self::generateTranslation('user_dob_edition_disabled', ['pt-BR' => 'A edição da data de nascimento está desativada']);
        self::generateTranslation('option_enable_blur_restricted_content', ['pt-BR' => 'Desfocar conteúdos restritos']);
        self::generateTranslation('tips_enable_blur_restricted_content', ['pt-BR' => 'Quando ativado, os conteúdos restritos ficam visíveis, mas desfocados; quando não, os conteúdos restritos ficam ocultos']);
        self::generateTranslation('enable_global_age_restriction', ['pt-BR' => 'Ativar pop-in global de restrição de idade']);
        self::generateTranslation('error_age_restriction', ['pt-BR' => 'Você não tem idade suficiente para acessar este conteúdo']);
        self::generateTranslation('error_age_restriction_save', ['pt-BR' => 'A idade mínima exigida deve ser entre 1 e 99 anos']);
        self::generateTranslation('age_verification', ['pt-BR' => 'Verificação de idade']);
        self::generateTranslation('age_verification_text', ['pt-BR' => 'Este site contém materiais com restrição de idade. Ao entrar, você afirma que tem pelo menos %s anos de idade.']);
        self::generateTranslation('disclaimer_older', ['pt-BR' => 'Tenho %s ou mais - Enter']);
        self::generateTranslation('disclaimer_return', ['pt-BR' => 'Tenho menos de %s - Sair']);
        self::generateTranslation('tips_enable_global_age_restriction', ['pt-BR' => 'Cadastro com uma idade base minima']);
        self::generateTranslation('edition_min_age_request', ['pt-BR' => 'A idade não pode ser inferior a %s']);
        self::generateTranslation('option_enable_quicklist', ['pt-BR' => 'Ativar lista rápida']);
        self::generateTranslation('option_hide_empty_collection', ['pt-BR' => 'Ocultar coleções vazias']);
        self::generateTranslation('option_display_video_comments', ['pt-BR' => 'Exibir comentários de vídeos']);
        self::generateTranslation('option_display_photo_comments', ['pt-BR' => 'Exibir comentários de fotos']);
        self::generateTranslation('option_display_channel_comments', ['pt-BR' => 'Exibir comentários de canais']);
        self::generateTranslation('comment_disabled_for', ['pt-BR' => 'Os comentários estão desativados para este %s']);
        self::generateTranslation('enable_collection_comments', ['pt-BR' => 'Habilitar comentários em coleções']);
        self::generateTranslation('display_collection_comments', ['pt-BR' => 'Exibir comentários de coleções']);
        self::generateTranslation('dev_mode', ['pt-BR' => 'Modo de Desenvolvimento']);
        self::generateTranslation('dev', ['pt-BR' => 'dev']);
        self::generateTranslation('discord_error_log', ['pt-BR' => 'Habilitar log de erros do Discord']);
        self::generateTranslation('discord_webhook_url', ['pt-BR' => 'URL do Webhook do Discord']);
        self::generateTranslation('discord_webhook_url_invalid', ['pt-BR' => 'O URL do webhook do Discord é inválido']);
        self::generateTranslation('option_enable_sitemap', ['pt-BR' => 'Ativar mapa do site']);
        self::generateTranslation('category_type_unknown', ['pt-BR' => 'Tipo de categoria desconhecido: %s']);
        self::generateTranslation('admin_setting', ['pt-BR' => 'Configurações do Administrador']);
        self::generateTranslation('site_setting', ['pt-BR' => 'Configurações do Site']);
        self::generateTranslation('admin_username', ['pt-BR' => 'Usuário do Administrador']);
        self::generateTranslation('admin_password', ['pt-BR' => 'Senha do Administrador']);
        self::generateTranslation('admin_email', ['pt-BR' => 'Email do Administrador']);
        self::generateTranslation('save_continue', ['pt-BR' => 'Salvar e Continuar']);
        self::generateTranslation('hint_admin_username', ['pt-BR' => 'O nome de usuário pode ter apenas caracteres alfanuméricos, sublinhados e hifens']);
        self::generateTranslation('hint_admin_email', ['pt-BR' => 'Verifique seu endereço de e-mail antes de continuar']);
        self::generateTranslation('admin_install_info', ['pt-BR' => 'Todas as etapas principais foram concluídas, agora informe o nome de usuário e a senha do seu usuário como administrador, por padrão, seu nome de usuário é: <strong>admin</strong> | A senha é: <strong>admin</strong>']);
        self::generateTranslation('generate', ['pt-BR' => 'Gerar']);
        self::generateTranslation('current', ['pt-BR' => 'Atual']);
        self::generateTranslation('website_configuration', ['pt-BR' => 'Configurações básicas do site']);
        self::generateTranslation('website_configuration_info', ['pt-BR' => 'Aqui você pode definir as configurações básicas do seu site, você pode alterá-las posteriormente acessando Área administrativa > Configurações do site']);
        self::generateTranslation('website_title', ['pt-BR' => 'Nome do Site']);
        self::generateTranslation('website_title_hint', ['pt-BR' => 'É o título do seu site E você pode ALTERÁ-LO NA área ADMIN']);
        self::generateTranslation('website_slogan', ['pt-BR' => 'Slogan do Site']);
        self::generateTranslation('website_slogan_hint', ['pt-BR' => 'É o slogan do seu site, você pode alterá-lo na área administrativa']);
        self::generateTranslation('website_url', ['pt-BR' => 'URL do Site']);
        self::generateTranslation('website_url_hint', ['pt-BR' => 'Sem barra final']);
        self::generateTranslation('agreement', ['pt-BR' => 'Acordo']);
        self::generateTranslation('pre_check', ['pt-BR' => 'Pré-verificação']);
        self::generateTranslation('permission', ['pt-BR' => 'Permissões']);
        self::generateTranslation('database', ['pt-BR' => 'Base de Dados']);
        self::generateTranslation('data_import', ['pt-BR' => 'Importação de Dados']);
        self::generateTranslation('finish', ['pt-BR' => 'Terminar']);
        self::generateTranslation('continue_admin_area', ['pt-BR' => 'Continuar para a Área Administrativa']);
        self::generateTranslation('continue_to', ['pt-BR' => 'Continuar para']);
        self::generateTranslation('successful_install', ['pt-BR' => 'foi instalado com sucesso!']);
        self::generateTranslation('default_language', ['pt-BR' => 'Idioma Padrão']);
        self::generateTranslation('error_server_config', ['pt-BR' => 'Você deve atualizar as <strong>"Configurações do Servidor"</strong>. <a href="%s">Clique aqui</a> para mais detalhes.']);
        self::generateTranslation('not_required_version', ['pt-BR' => 'A versão atual do %s é <strong>%s</strong>, a versão <strong>%s</strong> é a minima requerida']);
        self::generateTranslation('dob_required', ['pt-BR' => 'A data de nascimento é obrigatória']);
        self::generateTranslation('completed', ['pt-BR' => 'Concluído']);
        self::generateTranslation('error_allow_photo_types', ['pt-BR' => 'Somente os seguintes formatos de imagem são permitidos: %s']);
        self::generateTranslation('mysql_client', ['pt-BR' => 'Cliente MySQL']);
        self::generateTranslation('mysql_server', ['pt-BR' => 'Servidor MySQL']);
        self::generateTranslation('option_git_path', ['pt-BR' => 'Caminho Git']);
        self::generateTranslation('core_upgrade_avaible', ['pt-BR' => 'Atualização de núcleo disponível, clique aqui para atualizar: ']);
        self::generateTranslation('update_core_label', ['pt-BR' => 'Atualização de Núcleo']);
        self::generateTranslation('update_core_description', ['pt-BR' => 'Use o GIT para reverter todas as alterações de núcleo e atualizar para a revisão mais recente']);
        self::generateTranslation('core_up_to_date', ['pt-BR' => 'Seu núcleo está atualizado']);
        self::generateTranslation('clean_session_table_label', ['pt-BR' => 'Limpar tabela de sessão']);
        self::generateTranslation('clean_session_table_description', ['pt-BR' => 'Excluir entradas de sessões na tabela com mais de um mês']);
        self::generateTranslation('tool_recalcul_video_file_label', ['pt-BR' => 'Atualizar listagem de arquivos de vídeo']);
        self::generateTranslation('tool_recalcul_video_file_description', ['pt-BR' => 'Atualizar a lista de arquivos de todos os vídeos']);
        self::generateTranslation('recreate_thumb_label', ['pt-BR' => 'Recriar miniaturas de fotos']);
        self::generateTranslation('recreate_thumb_description', ['pt-BR' => 'Recrie todos as miniaturas das fotos']);
        self::generateTranslation('no_logs', ['pt-BR' => 'Nenhum registro para exibir']);
        self::generateTranslation('show_log', ['pt-BR' => 'Mostrar últimos registros']);
        self::generateTranslation('tool_started', ['pt-BR' => 'Ferramenta iniciada']);
        self::generateTranslation('tool_stopped', ['pt-BR' => 'Ferramenta parada']);
        self::generateTranslation('tool_ended', ['pt-BR' => 'Ferramenta encerrada']);
        self::generateTranslation('enable_tmdb', ['pt-BR' => 'Habilitar TMDB']);
        self::generateTranslation('tmdb_token', ['pt-BR' => 'Token de autenticação TMDB']);
        self::generateTranslation('tmdb_token_check', ['pt-BR' => 'Verifique o token TMDB']);
        self::generateTranslation('get_data_tmdb', ['pt-BR' => 'Obtenha informações do The Movie DataBase']);
        self::generateTranslation('release_date', ['pt-BR' => 'Data de Lançamento']);
        self::generateTranslation('import', ['pt-BR' => 'Importar']);
        self::generateTranslation('actors', ['pt-BR' => 'Atrores']);
        self::generateTranslation('producer', ['pt-BR' => 'Produtor']);
        self::generateTranslation('crew', ['pt-BR' => 'Equipe']);
        self::generateTranslation('genre', ['pt-BR' => 'Gênero']);
        self::generateTranslation('executive_producer', ['pt-BR' => 'Produtor Executivo']);
        self::generateTranslation('director', ['pt-BR' => 'Diretor']);
        self::generateTranslation('option_tmdb_get_genre', ['pt-BR' => 'Obtenha o gênero do TMDB']);
        self::generateTranslation('option_tmdb_get_actors', ['pt-BR' => 'Obtenha atores do TMDB']);
        self::generateTranslation('option_tmdb_get_producer', ['pt-BR' => 'Obtenha o produtor do TMDB']);
        self::generateTranslation('option_tmdb_get_executive_producer', ['pt-BR' => 'Obtenha produtor executivo do TMDB']);
        self::generateTranslation('option_tmdb_get_director', ['pt-BR' => 'Obter diretor do TMDB']);
        self::generateTranslation('option_tmdb_get_crew', ['pt-BR' => 'Obtenha equipe do TMDB']);
        self::generateTranslation('option_tmdb_get_poster', ['pt-BR' => 'Obtenha pôster do TMDB']);
        self::generateTranslation('option_tmdb_get_release_date', ['pt-BR' => 'Obtenha a data de lançamento do TMDB']);
        self::generateTranslation('option_tmdb_get_title', ['pt-BR' => 'Obtenha o título do TMDB']);
        self::generateTranslation('option_tmdb_get_description', ['pt-BR' => 'Obtenha a descrição do TMDB']);
        self::generateTranslation('tmdb_search', ['pt-BR' => 'Pesquisar no The Movie Database']);
        self::generateTranslation('movie_infos', ['pt-BR' => 'Info do Filme']);
        self::generateTranslation('option_enable_video_poster', ['pt-BR' => 'Ativar pôster']);
        self::generateTranslation('option_enable_video_backdrop', ['pt-BR' => 'Ativar cenário']);
        self::generateTranslation('option_tmdb_get_age_restriction', ['pt-BR' => 'Obtenha restrição de idade do TMDB']);
        self::generateTranslation('option_tmdb_get_backdrop', ['pt-BR' => 'Obtenha o cenário do TMDB']);
        self::generateTranslation('sort_by', ['pt-BR' => 'Classificar por %s']);
        self::generateTranslation('backdrop', ['pt-BR' => 'Cenário']);
        self::generateTranslation('poster', ['pt-BR' => 'Pôster']);
        self::generateTranslation('thumbnail', ['pt-BR' => 'Miniatura']);
        self::generateTranslation('default_x', ['pt-BR' => 'Padrão %s']);
        self::generateTranslation('option_require_x_enabled', ['pt-BR' => 'Esta opção requer que \'%s\' esteja habilitado']);
        self::generateTranslation('select_as_default_x', ['pt-BR' => 'Selecione como padrão %s']);
        self::generateTranslation('enable_x_field', ['pt-BR' => 'Habilitar o campo %s']);
        self::generateTranslation('update_category', ['pt-BR' => 'Atualizar Categoria']);
        self::generateTranslation('add_new_category', ['pt-BR' => 'Adicionar Nova Categoria']);
    }
}