ALTER TABLE `{tbl_prefix}action_log` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}admin_notes` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}admin_todo` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}ads_data` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}ads_placements` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}collections` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}collection_categories` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}collection_contributors` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}collection_items` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}comments` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}config` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}contacts` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}conversion_queue` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}counters` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}countries` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}editors_picks` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}email_templates` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}favorites` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}flags` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}groups` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}group_categories` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}group_invitations` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}group_members` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}group_posts` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}group_topics` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}group_videos` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}languages` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}mass_emails` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}messages` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}modules` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}pages` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}photos` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}phrases` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}playlists` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}playlist_items` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}plugins` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}plugin_config` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}sessions` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}stats` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}subscriptions` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}template` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}users` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}user_categories` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}user_levels` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}user_levels_permissions` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}user_permissions` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}user_permission_types` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}user_profile` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}validation_re` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}version` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}video` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}video_categories` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}video_favourites` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}video_files` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `{tbl_prefix}video_views` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

UPDATE `{tbl_prefix}action_log` SET action_type = convert(cast(convert(action_type using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}action_log` SET action_username = convert(cast(convert(action_username using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}action_log` SET action_useremail = convert(cast(convert(action_useremail using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}action_log` SET action_ip = convert(cast(convert(action_ip using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}action_log` SET action_details = convert(cast(convert(action_details using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}admin_notes` SET note = convert(cast(convert(note using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}admin_todo` SET todo = convert(cast(convert(todo using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}ads_data` SET ad_name = convert(cast(convert(ad_name using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}ads_data` SET ad_code = convert(cast(convert(ad_code using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}ads_data` SET ad_placement = convert(cast(convert(ad_placement using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}ads_placements` SET placement = convert(cast(convert(placement using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}ads_placements` SET placement_name = convert(cast(convert(placement_name using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}collection_categories` SET category_name = convert(cast(convert(category_name using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}collection_categories` SET category_desc = convert(cast(convert(category_desc using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}collection_categories` SET date_added = convert(cast(convert(date_added using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}collection_items` SET type = convert(cast(convert(type using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}collections` SET collection_name = convert(cast(convert(collection_name using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}collections` SET collection_description = convert(cast(convert(collection_description using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}collections` SET collection_tags = convert(cast(convert(collection_tags using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}collections` SET category = convert(cast(convert(category using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}collections` SET featured = convert(cast(convert(featured using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}collections` SET broadcast = convert(cast(convert(broadcast using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}collections` SET allow_comments = convert(cast(convert(allow_comments using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}collections` SET active = convert(cast(convert(active using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}collections` SET public_upload = convert(cast(convert(public_upload using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}collections` SET type = convert(cast(convert(type using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}comments` SET type = convert(cast(convert(type using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}comments` SET comment = convert(cast(convert(comment using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}comments` SET anonym_name = convert(cast(convert(anonym_name using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}comments` SET anonym_email = convert(cast(convert(anonym_email using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}comments` SET vote = convert(cast(convert(vote using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}comments` SET voters = convert(cast(convert(voters using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}comments` SET spam_voters = convert(cast(convert(spam_voters using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}comments` SET comment_ip = convert(cast(convert(comment_ip using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}config` SET name = convert(cast(convert(name using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}config` SET value = convert(cast(convert(value using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}conversion_queue` SET cqueue_name = convert(cast(convert(cqueue_name using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}conversion_queue` SET cqueue_ext = convert(cast(convert(cqueue_ext using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}conversion_queue` SET cqueue_tmp_ext = convert(cast(convert(cqueue_tmp_ext using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}conversion_queue` SET time_started = convert(cast(convert(time_started using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}conversion_queue` SET time_completed = convert(cast(convert(time_completed using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}counters` SET section = convert(cast(convert(section using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}counters` SET query = convert(cast(convert(query using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}counters` SET query_md5 = convert(cast(convert(query_md5 using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}counters` SET date_added = convert(cast(convert(date_added using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}countries` SET iso2 = convert(cast(convert(iso2 using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}countries` SET name = convert(cast(convert(name using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}countries` SET name_en = convert(cast(convert(name_en using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}countries` SET iso3 = convert(cast(convert(iso3 using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}email_templates` SET email_template_name = convert(cast(convert(email_template_name using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}email_templates` SET email_template_code = convert(cast(convert(email_template_code using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}email_templates` SET email_template_subject = convert(cast(convert(email_template_subject using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}email_templates` SET email_template = convert(cast(convert(email_template using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}email_templates` SET email_template_allowed_tags = convert(cast(convert(email_template_allowed_tags using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}favorites` SET type = convert(cast(convert(type using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}flags` SET type = convert(cast(convert(type using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}group_categories` SET category_name = convert(cast(convert(category_name using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}group_categories` SET category_desc = convert(cast(convert(category_desc using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}group_categories` SET date_added = convert(cast(convert(date_added using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}group_categories` SET category_thumb = convert(cast(convert(category_thumb using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}group_posts` SET post_content = convert(cast(convert(post_content using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}group_topics` SET topic_title = convert(cast(convert(topic_title using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}group_topics` SET topic_post = convert(cast(convert(topic_post using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}group_topics` SET topic_icon = convert(cast(convert(topic_icon using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}groups` SET group_name = convert(cast(convert(group_name using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}groups` SET group_admins = convert(cast(convert(group_admins using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}groups` SET group_description = convert(cast(convert(group_description using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}groups` SET group_tags = convert(cast(convert(group_tags using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}groups` SET group_url = convert(cast(convert(group_url using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}groups` SET category = convert(cast(convert(category using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}languages` SET language_code = convert(cast(convert(language_code using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}languages` SET language_name = convert(cast(convert(language_name using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}languages` SET language_regex = convert(cast(convert(language_regex using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}mass_emails` SET email_subj = convert(cast(convert(email_subj using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}mass_emails` SET email_from = convert(cast(convert(email_from using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}mass_emails` SET email_msg = convert(cast(convert(email_msg using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}mass_emails` SET configs = convert(cast(convert(configs using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}mass_emails` SET users = convert(cast(convert(users using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}messages` SET message_to = convert(cast(convert(message_to using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}messages` SET message_content = convert(cast(convert(message_content using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}messages` SET message_attachments = convert(cast(convert(message_attachments using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}messages` SET message_subject = convert(cast(convert(message_subject using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}modules` SET module_name = convert(cast(convert(module_name using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}modules` SET module_file = convert(cast(convert(module_file using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}modules` SET active = convert(cast(convert(active using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}modules` SET module_include_file = convert(cast(convert(module_include_file using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}pages` SET page_name = convert(cast(convert(page_name using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}pages` SET page_title = convert(cast(convert(page_title using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}pages` SET page_content = convert(cast(convert(page_content using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}photos` SET photo_key = convert(cast(convert(photo_key using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}photos` SET photo_title = convert(cast(convert(photo_title using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}photos` SET photo_description = convert(cast(convert(photo_description using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}photos` SET photo_tags = convert(cast(convert(photo_tags using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}photos` SET voters = convert(cast(convert(voters using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}photos` SET filename = convert(cast(convert(filename using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}photos` SET file_directory = convert(cast(convert(file_directory using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}photos` SET ext = convert(cast(convert(ext using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}photos` SET server_url = convert(cast(convert(server_url using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}photos` SET owner_ip = convert(cast(convert(owner_ip using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}photos` SET photo_details = convert(cast(convert(photo_details using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}phrases` SET lang_iso = convert(cast(convert(lang_iso using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}phrases` SET varname = convert(cast(convert(varname using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}phrases` SET text = convert(cast(convert(text using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}playlist_items` SET playlist_item_type = convert(cast(convert(playlist_item_type using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}playlists` SET playlist_name = convert(cast(convert(playlist_name using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}playlists` SET playlist_type = convert(cast(convert(playlist_type using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}playlists` SET description = convert(cast(convert(description using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}playlists` SET tags = convert(cast(convert(tags using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}playlists` SET voters = convert(cast(convert(voters using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}playlists` SET last_update = convert(cast(convert(last_update using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}playlists` SET first_item = convert(cast(convert(first_item using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}playlists` SET cover = convert(cast(convert(cover using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}plugin_config` SET plugin_id_code = convert(cast(convert(plugin_id_code using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}plugin_config` SET plugin_config_name = convert(cast(convert(plugin_config_name using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}plugin_config` SET plugin_config_value = convert(cast(convert(plugin_config_value using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}plugin_config` SET player_admin_file = convert(cast(convert(player_admin_file using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}plugin_config` SET player_include_file = convert(cast(convert(player_include_file using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}plugins` SET plugin_file = convert(cast(convert(plugin_file using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}plugins` SET plugin_folder = convert(cast(convert(plugin_folder using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}plugins` SET plugin_license_type = convert(cast(convert(plugin_license_type using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}plugins` SET plugin_license_key = convert(cast(convert(plugin_license_key using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}plugins` SET plugin_license_code = convert(cast(convert(plugin_license_code using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}sessions` SET session = convert(cast(convert(session using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}sessions` SET session_string = convert(cast(convert(session_string using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}sessions` SET session_value = convert(cast(convert(session_value using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}sessions` SET ip = convert(cast(convert(ip using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}sessions` SET current_page = convert(cast(convert(current_page using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}sessions` SET referer = convert(cast(convert(referer using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}sessions` SET agent = convert(cast(convert(agent using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}stats` SET video_stats = convert(cast(convert(video_stats using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}stats` SET user_stats = convert(cast(convert(user_stats using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}stats` SET group_stats = convert(cast(convert(group_stats using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}subscriptions` SET subscribed_to = convert(cast(convert(subscribed_to using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}template` SET template_name = convert(cast(convert(template_name using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}template` SET template_dir = convert(cast(convert(template_dir using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}user_categories` SET category_name = convert(cast(convert(category_name using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}user_categories` SET category_desc = convert(cast(convert(category_desc using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}user_categories` SET date_added = convert(cast(convert(date_added using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}user_categories` SET category_thumb = convert(cast(convert(category_thumb using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}user_levels` SET user_level_name = convert(cast(convert(user_level_name using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}user_levels_permissions` SET plugins_perms = convert(cast(convert(plugins_perms using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}user_permission_types` SET user_permission_type_name = convert(cast(convert(user_permission_type_name using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}user_permission_types` SET user_permission_type_desc = convert(cast(convert(user_permission_type_desc using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}user_permissions` SET permission_name = convert(cast(convert(permission_name using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}user_permissions` SET permission_code = convert(cast(convert(permission_code using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}user_permissions` SET permission_desc = convert(cast(convert(permission_desc using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}user_profile` SET profile_title = convert(cast(convert(profile_title using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}user_profile` SET profile_desc = convert(cast(convert(profile_desc using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}user_profile` SET featured_video = convert(cast(convert(featured_video using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}user_profile` SET first_name = convert(cast(convert(first_name using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}user_profile` SET last_name = convert(cast(convert(last_name using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}user_profile` SET avatar = convert(cast(convert(avatar using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}user_profile` SET postal_code = convert(cast(convert(postal_code using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}user_profile` SET profile_tags = convert(cast(convert(profile_tags using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}user_profile` SET web_url = convert(cast(convert(web_url using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}user_profile` SET hometown = convert(cast(convert(hometown using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}user_profile` SET city = convert(cast(convert(city using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}user_profile` SET browse_criteria = convert(cast(convert(browse_criteria using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}user_profile` SET about_me = convert(cast(convert(about_me using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}user_profile` SET education = convert(cast(convert(education using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}user_profile` SET schools = convert(cast(convert(schools using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}user_profile` SET occupation = convert(cast(convert(occupation using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}user_profile` SET companies = convert(cast(convert(companies using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}user_profile` SET relation_status = convert(cast(convert(relation_status using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}user_profile` SET hobbies = convert(cast(convert(hobbies using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}user_profile` SET fav_movies = convert(cast(convert(fav_movies using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}user_profile` SET fav_music = convert(cast(convert(fav_music using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}user_profile` SET fav_books = convert(cast(convert(fav_books using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}user_profile` SET background = convert(cast(convert(background using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}user_profile` SET profile_item = convert(cast(convert(profile_item using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}user_profile` SET voters = convert(cast(convert(voters using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}users` SET featured_video = convert(cast(convert(featured_video using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}users` SET username = convert(cast(convert(username using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}users` SET user_session_key = convert(cast(convert(user_session_key using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}users` SET password = convert(cast(convert(password using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}users` SET email = convert(cast(convert(email using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}users` SET avatar = convert(cast(convert(avatar using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}users` SET avatar_url = convert(cast(convert(avatar_url using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}users` SET country = convert(cast(convert(country using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}users` SET avcode = convert(cast(convert(avcode using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}users` SET session = convert(cast(convert(session using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}users` SET ip = convert(cast(convert(ip using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}users` SET signup_ip = convert(cast(convert(signup_ip using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}users` SET upload = convert(cast(convert(upload using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}users` SET background = convert(cast(convert(background using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}users` SET background_color = convert(cast(convert(background_color using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}users` SET background_url = convert(cast(convert(background_url using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}users` SET banned_users = convert(cast(convert(banned_users using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}validation_re` SET re_name = convert(cast(convert(re_name using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}validation_re` SET re_code = convert(cast(convert(re_code using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}validation_re` SET re_syntax = convert(cast(convert(re_syntax using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET videokey = convert(cast(convert(videokey using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET video_password = convert(cast(convert(video_password using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET video_users = convert(cast(convert(video_users using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET username = convert(cast(convert(username using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET title = convert(cast(convert(title using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET file_name = convert(cast(convert(file_name using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET file_directory = convert(cast(convert(file_directory using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET description = convert(cast(convert(description using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET tags = convert(cast(convert(tags using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET category = convert(cast(convert(category using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET category_parents = convert(cast(convert(category_parents using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET broadcast = convert(cast(convert(broadcast using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET location = convert(cast(convert(location using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET country = convert(cast(convert(country using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET allow_embedding = convert(cast(convert(allow_embedding using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET rated_by = convert(cast(convert(rated_by using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET voter_ids = convert(cast(convert(voter_ids using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET allow_comments = convert(cast(convert(allow_comments using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET comment_voting = convert(cast(convert(comment_voting using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET featured = convert(cast(convert(featured using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET featured_description = convert(cast(convert(featured_description using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET allow_rating = convert(cast(convert(allow_rating using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET active = convert(cast(convert(active using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET favourite_count = convert(cast(convert(favourite_count using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET playlist_count = convert(cast(convert(playlist_count using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET flagged = convert(cast(convert(flagged using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET duration = convert(cast(convert(duration using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET aspect_ratio = convert(cast(convert(aspect_ratio using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET embed_code = convert(cast(convert(embed_code using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET refer_url = convert(cast(convert(refer_url using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET uploader_ip = convert(cast(convert(uploader_ip using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET unique_embed_code = convert(cast(convert(unique_embed_code using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET remote_play_url = convert(cast(convert(remote_play_url using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET server_ip = convert(cast(convert(server_ip using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET file_server_path = convert(cast(convert(file_server_path using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET files_thumbs_path = convert(cast(convert(files_thumbs_path using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET file_thumbs_count = convert(cast(convert(file_thumbs_count using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET filegrp_size = convert(cast(convert(filegrp_size using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET video_version = convert(cast(convert(video_version using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET extras = convert(cast(convert(extras using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video` SET thumbs_version = convert(cast(convert(thumbs_version using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_categories` SET category_name = convert(cast(convert(category_name using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_categories` SET category_desc = convert(cast(convert(category_desc using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_categories` SET date_added = convert(cast(convert(date_added using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_categories` SET category_thumb = convert(cast(convert(category_thumb using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET file_conversion_log = convert(cast(convert(file_conversion_log using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET encoder = convert(cast(convert(encoder using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET command_used = convert(cast(convert(command_used using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET src_path = convert(cast(convert(src_path using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET src_name = convert(cast(convert(src_name using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET src_ext = convert(cast(convert(src_ext using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET src_format = convert(cast(convert(src_format using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET src_duration = convert(cast(convert(src_duration using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET src_size = convert(cast(convert(src_size using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET src_bitrate = convert(cast(convert(src_bitrate using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET src_video_width = convert(cast(convert(src_video_width using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET src_video_height = convert(cast(convert(src_video_height using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET src_video_wh_ratio = convert(cast(convert(src_video_wh_ratio using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET src_video_codec = convert(cast(convert(src_video_codec using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET src_video_rate = convert(cast(convert(src_video_rate using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET src_video_bitrate = convert(cast(convert(src_video_bitrate using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET src_video_color = convert(cast(convert(src_video_color using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET src_audio_codec = convert(cast(convert(src_audio_codec using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET src_audio_bitrate = convert(cast(convert(src_audio_bitrate using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET src_audio_rate = convert(cast(convert(src_audio_rate using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET src_audio_channels = convert(cast(convert(src_audio_channels using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET output_path = convert(cast(convert(output_path using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET output_format = convert(cast(convert(output_format using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET output_duration = convert(cast(convert(output_duration using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET output_size = convert(cast(convert(output_size using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET output_bitrate = convert(cast(convert(output_bitrate using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET output_video_width = convert(cast(convert(output_video_width using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET output_video_height = convert(cast(convert(output_video_height using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET output_video_wh_ratio = convert(cast(convert(output_video_wh_ratio using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET output_video_codec = convert(cast(convert(output_video_codec using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET output_video_rate = convert(cast(convert(output_video_rate using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET output_video_bitrate = convert(cast(convert(output_video_bitrate using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET output_video_color = convert(cast(convert(output_video_color using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET output_audio_codec = convert(cast(convert(output_audio_codec using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET output_audio_bitrate = convert(cast(convert(output_audio_bitrate using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET output_audio_rate = convert(cast(convert(output_audio_rate using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_files` SET output_audio_channels = convert(cast(convert(output_audio_channels using utf8mb3) as binary) using utf8);
UPDATE `{tbl_prefix}video_views` SET video_id = convert(cast(convert(video_id using utf8mb3) as binary) using utf8);

INSERT INTO `{tbl_prefix}config`(`name`, `value`) VALUES
    ('password_salt', SUBSTRING(HEX(SHA2(CONCAT(NOW(), RAND(), UUID()), 512)),1, 32) ),
    ('show_collapsed_checkboxes', '0'),
    ('enable_advertisement', 'no'),
    ('chromecast', 'no'),
    ('vid_cat_width', '120'),
    ('vid_cat_height', '120');

ALTER TABLE `{tbl_prefix}users` CHANGE `password` `password` VARCHAR(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';

ALTER TABLE `{tbl_prefix}user_levels_permissions` ADD `view_photos` ENUM('yes', 'no') NOT NULL DEFAULT 'yes' AFTER `view_video`;
ALTER TABLE `{tbl_prefix}user_levels_permissions` ADD `view_collections` ENUM('yes', 'no') NOT NULL DEFAULT 'yes' AFTER `view_photos`;

INSERT INTO `{tbl_prefix}user_permissions` (`permission_type`, `permission_name`, `permission_code`, `permission_desc`, `permission_default`) VALUES
    (1, 'View Photos Page', 'view_photos', 'User can view photos page', 'yes'),
    (1, 'View Collections Page', 'view_collections', 'User can view collections page', 'yes');

UPDATE `{tbl_prefix}languages` SET `language_id` = 1 WHERE `language_code` LIKE 'en';
INSERT INTO `{tbl_prefix}languages` (`language_id`, `language_code`, `language_name`, `language_regex`, `language_active`, `language_default`)
    VALUES (2, 'fr', 'Français', 'fra', 'no', 'no');

DELETE FROM `{tbl_prefix}config` WHERE configid IN(SELECT configid FROM `{tbl_prefix}config` GROUP BY name HAVING COUNT(*) > 1);
