<?php
require_once DirPath::get('classes') . DIRECTORY_SEPARATOR . 'migration' . DIRECTORY_SEPARATOR . 'migration.class.php';

class M00001 extends Migration
{
    /**
     * @throws Exception
     */
    public function start()
    {
        $sql = 'UPDATE `{tbl_prefix}action_log` SET action_type = CONVERT(CAST(CONVERT(action_type USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}action_log` SET action_username = CONVERT(CAST(CONVERT(action_username USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}action_log` SET action_useremail = CONVERT(CAST(CONVERT(action_useremail USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}action_log` SET action_ip = CONVERT(CAST(CONVERT(action_ip USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}action_log` SET action_details = CONVERT(CAST(CONVERT(action_details USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}admin_notes` SET note = CONVERT(CAST(CONVERT(note USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}admin_todo` SET todo = CONVERT(CAST(CONVERT(todo USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}ads_data` SET ad_name = CONVERT(CAST(CONVERT(ad_name USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}ads_data` SET ad_code = CONVERT(CAST(CONVERT(ad_code USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}ads_data` SET ad_placement = CONVERT(CAST(CONVERT(ad_placement USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}ads_placements` SET placement = CONVERT(CAST(CONVERT(placement USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}ads_placements` SET placement_name = CONVERT(CAST(CONVERT(placement_name USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}collection_categories` SET category_name = CONVERT(CAST(CONVERT(category_name USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}collection_categories` SET category_desc = CONVERT(CAST(CONVERT(category_desc USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}collection_categories` SET date_added = CONVERT(CAST(CONVERT(date_added USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}collection_items` SET type = CONVERT(CAST(CONVERT(type USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}collections` SET collection_name = CONVERT(CAST(CONVERT(collection_name USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}collections` SET collection_description = CONVERT(CAST(CONVERT(collection_description USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}collections` SET collection_tags = CONVERT(CAST(CONVERT(collection_tags USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}collections` SET category = CONVERT(CAST(CONVERT(category USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}collections` SET featured = CONVERT(CAST(CONVERT(featured USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}collections` SET broadcast = CONVERT(CAST(CONVERT(broadcast USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}collections` SET allow_comments = CONVERT(CAST(CONVERT(allow_comments USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}collections` SET active = CONVERT(CAST(CONVERT(active USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}collections` SET public_upload = CONVERT(CAST(CONVERT(public_upload USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}collections` SET type = CONVERT(CAST(CONVERT(type USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}comments` SET type = CONVERT(CAST(CONVERT(type USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}comments` SET comment = CONVERT(CAST(CONVERT(comment USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}comments` SET anonym_name = CONVERT(CAST(CONVERT(anonym_name USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}comments` SET anonym_email = CONVERT(CAST(CONVERT(anonym_email USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}comments` SET vote = CONVERT(CAST(CONVERT(vote USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}comments` SET voters = CONVERT(CAST(CONVERT(voters USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}comments` SET spam_voters = CONVERT(CAST(CONVERT(spam_voters USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}comments` SET comment_ip = CONVERT(CAST(CONVERT(comment_ip USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}config` SET name = CONVERT(CAST(CONVERT(name USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}config` SET value = CONVERT(CAST(CONVERT(value USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}conversion_queue` SET cqueue_name = CONVERT(CAST(CONVERT(cqueue_name USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}conversion_queue` SET cqueue_ext = CONVERT(CAST(CONVERT(cqueue_ext USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}conversion_queue` SET cqueue_tmp_ext = CONVERT(CAST(CONVERT(cqueue_tmp_ext USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}conversion_queue` SET time_started = CONVERT(CAST(CONVERT(time_started USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}conversion_queue` SET time_completed = CONVERT(CAST(CONVERT(time_completed USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}counters` SET section = CONVERT(CAST(CONVERT(section USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}counters` SET query = CONVERT(CAST(CONVERT(query USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}counters` SET query_md5 = CONVERT(CAST(CONVERT(query_md5 USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}counters` SET date_added = CONVERT(CAST(CONVERT(date_added USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}countries` SET iso2 = CONVERT(CAST(CONVERT(iso2 USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}countries` SET name = CONVERT(CAST(CONVERT(name USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}countries` SET name_en = CONVERT(CAST(CONVERT(name_en USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}countries` SET iso3 = CONVERT(CAST(CONVERT(iso3 USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}email_templates` SET email_template_name = CONVERT(CAST(CONVERT(email_template_name USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}email_templates` SET email_template_code = CONVERT(CAST(CONVERT(email_template_code USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}email_templates` SET email_template_subject = CONVERT(CAST(CONVERT(email_template_subject USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}email_templates` SET email_template = CONVERT(CAST(CONVERT(email_template USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}email_templates` SET email_template_allowed_tags = CONVERT(CAST(CONVERT(email_template_allowed_tags USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}favorites` SET type = CONVERT(CAST(CONVERT(type USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}flags` SET type = CONVERT(CAST(CONVERT(type USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}group_categories` SET category_name = CONVERT(CAST(CONVERT(category_name USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}group_categories` SET category_desc = CONVERT(CAST(CONVERT(category_desc USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}group_categories` SET date_added = CONVERT(CAST(CONVERT(date_added USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}group_categories` SET category_thumb = CONVERT(CAST(CONVERT(category_thumb USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}group_posts` SET post_content = CONVERT(CAST(CONVERT(post_content USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}group_topics` SET topic_title = CONVERT(CAST(CONVERT(topic_title USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}group_topics` SET topic_post = CONVERT(CAST(CONVERT(topic_post USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}group_topics` SET topic_icon = CONVERT(CAST(CONVERT(topic_icon USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}groups` SET group_name = CONVERT(CAST(CONVERT(group_name USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}groups` SET group_admins = CONVERT(CAST(CONVERT(group_admins USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}groups` SET group_description = CONVERT(CAST(CONVERT(group_description USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}groups` SET group_tags = CONVERT(CAST(CONVERT(group_tags USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}groups` SET group_url = CONVERT(CAST(CONVERT(group_url USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}groups` SET category = CONVERT(CAST(CONVERT(category USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}languages` SET language_code = CONVERT(CAST(CONVERT(language_code USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}languages` SET language_name = CONVERT(CAST(CONVERT(language_name USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}languages` SET language_regex = CONVERT(CAST(CONVERT(language_regex USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}mass_emails` SET email_subj = CONVERT(CAST(CONVERT(email_subj USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}mass_emails` SET email_from = CONVERT(CAST(CONVERT(email_from USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}mass_emails` SET email_msg = CONVERT(CAST(CONVERT(email_msg USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}mass_emails` SET configs = CONVERT(CAST(CONVERT(configs USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}mass_emails` SET users = CONVERT(CAST(CONVERT(users USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}messages` SET message_to = CONVERT(CAST(CONVERT(message_to USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}messages` SET message_content = CONVERT(CAST(CONVERT(message_content USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}messages` SET message_attachments = CONVERT(CAST(CONVERT(message_attachments USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}messages` SET message_subject = CONVERT(CAST(CONVERT(message_subject USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}modules` SET module_name = CONVERT(CAST(CONVERT(module_name USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}modules` SET module_file = CONVERT(CAST(CONVERT(module_file USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}modules` SET active = CONVERT(CAST(CONVERT(active USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}modules` SET module_include_file = CONVERT(CAST(CONVERT(module_include_file USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}pages` SET page_name = CONVERT(CAST(CONVERT(page_name USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}pages` SET page_title = CONVERT(CAST(CONVERT(page_title USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}pages` SET page_content = CONVERT(CAST(CONVERT(page_content USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}photos` SET photo_key = CONVERT(CAST(CONVERT(photo_key USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}photos` SET photo_title = CONVERT(CAST(CONVERT(photo_title USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}photos` SET photo_description = CONVERT(CAST(CONVERT(photo_description USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}photos` SET photo_tags = CONVERT(CAST(CONVERT(photo_tags USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}photos` SET voters = CONVERT(CAST(CONVERT(voters USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}photos` SET filename = CONVERT(CAST(CONVERT(filename USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}photos` SET file_directory = CONVERT(CAST(CONVERT(file_directory USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}photos` SET ext = CONVERT(CAST(CONVERT(ext USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}photos` SET server_url = CONVERT(CAST(CONVERT(server_url USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}photos` SET owner_ip = CONVERT(CAST(CONVERT(owner_ip USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}photos` SET photo_details = CONVERT(CAST(CONVERT(photo_details USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}phrases` SET lang_iso = CONVERT(CAST(CONVERT(lang_iso USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}phrases` SET varname = CONVERT(CAST(CONVERT(varname USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = '# UPDATE `{tbl_prefix}phrases` SET text = convert(cast(convert(text using latin1) as binary) using utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}playlist_items` SET playlist_item_type = CONVERT(CAST(CONVERT(playlist_item_type USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}playlists` SET playlist_name = CONVERT(CAST(CONVERT(playlist_name USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}playlists` SET playlist_type = CONVERT(CAST(CONVERT(playlist_type USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}playlists` SET description = CONVERT(CAST(CONVERT(description USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}playlists` SET tags = CONVERT(CAST(CONVERT(tags USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}playlists` SET voters = CONVERT(CAST(CONVERT(voters USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}playlists` SET last_update = CONVERT(CAST(CONVERT(last_update USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}playlists` SET first_item = CONVERT(CAST(CONVERT(first_item USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}playlists` SET cover = CONVERT(CAST(CONVERT(cover USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}plugin_config` SET plugin_id_code = CONVERT(CAST(CONVERT(plugin_id_code USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}plugin_config` SET plugin_config_name = CONVERT(CAST(CONVERT(plugin_config_name USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}plugin_config` SET plugin_config_value = CONVERT(CAST(CONVERT(plugin_config_value USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}plugin_config` SET player_admin_file = CONVERT(CAST(CONVERT(player_admin_file USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}plugin_config` SET player_include_file = CONVERT(CAST(CONVERT(player_include_file USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}plugins` SET plugin_file = CONVERT(CAST(CONVERT(plugin_file USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}plugins` SET plugin_folder = CONVERT(CAST(CONVERT(plugin_folder USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}plugins` SET plugin_license_type = CONVERT(CAST(CONVERT(plugin_license_type USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}plugins` SET plugin_license_key = CONVERT(CAST(CONVERT(plugin_license_key USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}plugins` SET plugin_license_code = CONVERT(CAST(CONVERT(plugin_license_code USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}sessions` SET session = CONVERT(CAST(CONVERT(session USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}sessions` SET session_string = CONVERT(CAST(CONVERT(session_string USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}sessions` SET session_value = CONVERT(CAST(CONVERT(session_value USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}sessions` SET ip = CONVERT(CAST(CONVERT(ip USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}sessions` SET current_page = CONVERT(CAST(CONVERT(current_page USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}sessions` SET referer = CONVERT(CAST(CONVERT(referer USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}sessions` SET agent = CONVERT(CAST(CONVERT(agent USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}stats` SET video_stats = CONVERT(CAST(CONVERT(video_stats USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}stats` SET user_stats = CONVERT(CAST(CONVERT(user_stats USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}stats` SET group_stats = CONVERT(CAST(CONVERT(group_stats USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}subscriptions` SET subscribed_to = CONVERT(CAST(CONVERT(subscribed_to USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}template` SET template_name = CONVERT(CAST(CONVERT(template_name USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}template` SET template_dir = CONVERT(CAST(CONVERT(template_dir USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}user_categories` SET category_name = CONVERT(CAST(CONVERT(category_name USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}user_categories` SET category_desc = CONVERT(CAST(CONVERT(category_desc USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}user_categories` SET date_added = CONVERT(CAST(CONVERT(date_added USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}user_categories` SET category_thumb = CONVERT(CAST(CONVERT(category_thumb USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}user_levels` SET user_level_name = CONVERT(CAST(CONVERT(user_level_name USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}user_levels_permissions` SET plugins_perms = CONVERT(CAST(CONVERT(plugins_perms USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}user_permission_types` SET user_permission_type_name = CONVERT(CAST(CONVERT(user_permission_type_name USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}user_permission_types` SET user_permission_type_desc = CONVERT(CAST(CONVERT(user_permission_type_desc USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}user_permissions` SET permission_name = CONVERT(CAST(CONVERT(permission_name USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}user_permissions` SET permission_code = CONVERT(CAST(CONVERT(permission_code USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}user_permissions` SET permission_desc = CONVERT(CAST(CONVERT(permission_desc USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}user_profile` SET profile_title = CONVERT(CAST(CONVERT(profile_title USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}user_profile` SET profile_desc = CONVERT(CAST(CONVERT(profile_desc USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}user_profile` SET featured_video = CONVERT(CAST(CONVERT(featured_video USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}user_profile` SET first_name = CONVERT(CAST(CONVERT(first_name USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}user_profile` SET last_name = CONVERT(CAST(CONVERT(last_name USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}user_profile` SET avatar = CONVERT(CAST(CONVERT(avatar USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}user_profile` SET postal_code = CONVERT(CAST(CONVERT(postal_code USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}user_profile` SET profile_tags = CONVERT(CAST(CONVERT(profile_tags USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}user_profile` SET web_url = CONVERT(CAST(CONVERT(web_url USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}user_profile` SET hometown = CONVERT(CAST(CONVERT(hometown USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}user_profile` SET city = CONVERT(CAST(CONVERT(city USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}user_profile` SET browse_criteria = CONVERT(CAST(CONVERT(browse_criteria USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}user_profile` SET about_me = CONVERT(CAST(CONVERT(about_me USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}user_profile` SET education = CONVERT(CAST(CONVERT(education USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}user_profile` SET schools = CONVERT(CAST(CONVERT(schools USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}user_profile` SET occupation = CONVERT(CAST(CONVERT(occupation USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}user_profile` SET companies = CONVERT(CAST(CONVERT(companies USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}user_profile` SET relation_status = CONVERT(CAST(CONVERT(relation_status USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}user_profile` SET hobbies = CONVERT(CAST(CONVERT(hobbies USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}user_profile` SET fav_movies = CONVERT(CAST(CONVERT(fav_movies USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}user_profile` SET fav_music = CONVERT(CAST(CONVERT(fav_music USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}user_profile` SET fav_books = CONVERT(CAST(CONVERT(fav_books USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}user_profile` SET background = CONVERT(CAST(CONVERT(background USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}user_profile` SET profile_item = CONVERT(CAST(CONVERT(profile_item USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}user_profile` SET voters = CONVERT(CAST(CONVERT(voters USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}users` SET featured_video = CONVERT(CAST(CONVERT(featured_video USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}users` SET username = CONVERT(CAST(CONVERT(username USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}users` SET user_session_key = CONVERT(CAST(CONVERT(user_session_key USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}users` SET password = CONVERT(CAST(CONVERT(password USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}users` SET email = CONVERT(CAST(CONVERT(email USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}users` SET avatar = CONVERT(CAST(CONVERT(avatar USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}users` SET avatar_url = CONVERT(CAST(CONVERT(avatar_url USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}users` SET country = CONVERT(CAST(CONVERT(country USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}users` SET avcode = CONVERT(CAST(CONVERT(avcode USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}users` SET session = CONVERT(CAST(CONVERT(session USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}users` SET ip = CONVERT(CAST(CONVERT(ip USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}users` SET signup_ip = CONVERT(CAST(CONVERT(signup_ip USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}users` SET upload = CONVERT(CAST(CONVERT(upload USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}users` SET background = CONVERT(CAST(CONVERT(background USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}users` SET background_color = CONVERT(CAST(CONVERT(background_color USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}users` SET background_url = CONVERT(CAST(CONVERT(background_url USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}users` SET banned_users = CONVERT(CAST(CONVERT(banned_users USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}validation_re` SET re_name = CONVERT(CAST(CONVERT(re_name USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}validation_re` SET re_code = CONVERT(CAST(CONVERT(re_code USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}validation_re` SET re_syntax = CONVERT(CAST(CONVERT(re_syntax USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET videokey = CONVERT(CAST(CONVERT(videokey USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET video_password = CONVERT(CAST(CONVERT(video_password USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET video_users = CONVERT(CAST(CONVERT(video_users USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET username = CONVERT(CAST(CONVERT(username USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET title = CONVERT(CAST(CONVERT(title USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET file_name = CONVERT(CAST(CONVERT(file_name USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET file_directory = CONVERT(CAST(CONVERT(file_directory USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET description = CONVERT(CAST(CONVERT(description USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET tags = CONVERT(CAST(CONVERT(tags USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET category = CONVERT(CAST(CONVERT(category USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET category_parents = CONVERT(CAST(CONVERT(category_parents USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET broadcast = CONVERT(CAST(CONVERT(broadcast USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET location = CONVERT(CAST(CONVERT(location USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET country = CONVERT(CAST(CONVERT(country USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET allow_embedding = CONVERT(CAST(CONVERT(allow_embedding USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET rated_by = CONVERT(CAST(CONVERT(rated_by USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET voter_ids = CONVERT(CAST(CONVERT(voter_ids USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET allow_comments = CONVERT(CAST(CONVERT(allow_comments USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET comment_voting = CONVERT(CAST(CONVERT(comment_voting USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET featured = CONVERT(CAST(CONVERT(featured USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET featured_description = CONVERT(CAST(CONVERT(featured_description USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET allow_rating = CONVERT(CAST(CONVERT(allow_rating USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET active = CONVERT(CAST(CONVERT(active USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET favourite_count = CONVERT(CAST(CONVERT(favourite_count USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET playlist_count = CONVERT(CAST(CONVERT(playlist_count USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET flagged = CONVERT(CAST(CONVERT(flagged USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET duration = CONVERT(CAST(CONVERT(duration USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET aspect_ratio = CONVERT(CAST(CONVERT(aspect_ratio USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET embed_code = CONVERT(CAST(CONVERT(embed_code USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET refer_url = CONVERT(CAST(CONVERT(refer_url USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET uploader_ip = CONVERT(CAST(CONVERT(uploader_ip USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET unique_embed_code = CONVERT(CAST(CONVERT(unique_embed_code USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET remote_play_url = CONVERT(CAST(CONVERT(remote_play_url USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET server_ip = CONVERT(CAST(CONVERT(server_ip USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET file_server_path = CONVERT(CAST(CONVERT(file_server_path USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET files_thumbs_path = CONVERT(CAST(CONVERT(files_thumbs_path USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET file_thumbs_count = CONVERT(CAST(CONVERT(file_thumbs_count USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET filegrp_size = CONVERT(CAST(CONVERT(filegrp_size USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET video_version = CONVERT(CAST(CONVERT(video_version USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET extras = CONVERT(CAST(CONVERT(extras USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video` SET thumbs_version = CONVERT(CAST(CONVERT(thumbs_version USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_categories` SET category_name = CONVERT(CAST(CONVERT(category_name USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_categories` SET category_desc = CONVERT(CAST(CONVERT(category_desc USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_categories` SET date_added = CONVERT(CAST(CONVERT(date_added USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_categories` SET category_thumb = CONVERT(CAST(CONVERT(category_thumb USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET file_conversion_log = CONVERT(CAST(CONVERT(file_conversion_log USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET encoder = CONVERT(CAST(CONVERT(encoder USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET command_used = CONVERT(CAST(CONVERT(command_used USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET src_path = CONVERT(CAST(CONVERT(src_path USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET src_name = CONVERT(CAST(CONVERT(src_name USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET src_ext = CONVERT(CAST(CONVERT(src_ext USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET src_format = CONVERT(CAST(CONVERT(src_format USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET src_duration = CONVERT(CAST(CONVERT(src_duration USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET src_size = CONVERT(CAST(CONVERT(src_size USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET src_bitrate = CONVERT(CAST(CONVERT(src_bitrate USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET src_video_width = CONVERT(CAST(CONVERT(src_video_width USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET src_video_height = CONVERT(CAST(CONVERT(src_video_height USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET src_video_wh_ratio = CONVERT(CAST(CONVERT(src_video_wh_ratio USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET src_video_codec = CONVERT(CAST(CONVERT(src_video_codec USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET src_video_rate = CONVERT(CAST(CONVERT(src_video_rate USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET src_video_bitrate = CONVERT(CAST(CONVERT(src_video_bitrate USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET src_video_color = CONVERT(CAST(CONVERT(src_video_color USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET src_audio_codec = CONVERT(CAST(CONVERT(src_audio_codec USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET src_audio_bitrate = CONVERT(CAST(CONVERT(src_audio_bitrate USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET src_audio_rate = CONVERT(CAST(CONVERT(src_audio_rate USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET src_audio_channels = CONVERT(CAST(CONVERT(src_audio_channels USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET output_path = CONVERT(CAST(CONVERT(output_path USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET output_format = CONVERT(CAST(CONVERT(output_format USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET output_duration = CONVERT(CAST(CONVERT(output_duration USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET output_size = CONVERT(CAST(CONVERT(output_size USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET output_bitrate = CONVERT(CAST(CONVERT(output_bitrate USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET output_video_width = CONVERT(CAST(CONVERT(output_video_width USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET output_video_height = CONVERT(CAST(CONVERT(output_video_height USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET output_video_wh_ratio = CONVERT(CAST(CONVERT(output_video_wh_ratio USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET output_video_codec = CONVERT(CAST(CONVERT(output_video_codec USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET output_video_rate = CONVERT(CAST(CONVERT(output_video_rate USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET output_video_bitrate = CONVERT(CAST(CONVERT(output_video_bitrate USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET output_video_color = CONVERT(CAST(CONVERT(output_video_color USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET output_audio_codec = CONVERT(CAST(CONVERT(output_audio_codec USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET output_audio_bitrate = CONVERT(CAST(CONVERT(output_audio_bitrate USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET output_audio_rate = CONVERT(CAST(CONVERT(output_audio_rate USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_files` SET output_audio_channels = CONVERT(CAST(CONVERT(output_audio_channels USING latin1) AS BINARY) USING utf8);';
        self::query($sql);
        $sql = 'UPDATE `{tbl_prefix}video_views` SET video_id = CONVERT(CAST(CONVERT(video_id USING latin1) AS BINARY) USING utf8);';
        self::query($sql);

        $sql = 'INSERT INTO `{tbl_prefix}config`(`name`, `value`) VALUES
        (\'password_salt\', SUBSTRING(HEX(SHA2(CONCAT(NOW(), RAND(), UUID()), 512)),1, 32) ),
        (\'show_collapsed_checkboxes\', \'0\'),
        (\'enable_advertisement\', \'no\'),
        (\'chromecast\', \'no\'),
        (\'vid_cat_width\', \'120\'),
        (\'vid_cat_height\', \'120\');';
        self::query($sql);

        self::alterTable('ALTER TABLE `{tbl_prefix}users` CHANGE `password` `password` VARCHAR(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT \'\';', [
            'table'  => '{tbl_prefix}users',
            'column' => 'password'
        ]);

        self::alterTable('ALTER TABLE `{tbl_prefix}user_levels_permissions` ADD `view_photos` ENUM(\'yes\', \'no\') NOT NULL DEFAULT \'yes\' AFTER `view_video`;', [
            'table' => '{tbl_prefix}user_levels_permissions'
        ]);

        self::alterTable('ALTER TABLE `{tbl_prefix}user_levels_permissions` ADD `view_collections` ENUM(\'yes\', \'no\') NOT NULL DEFAULT \'yes\' AFTER `view_photos`;', [
            'table' => '{tbl_prefix}user_levels_permissions'
        ]);

        $sql = 'INSERT INTO `{tbl_prefix}user_permissions` (`permission_type`, `permission_name`, `permission_code`, `permission_desc`, `permission_default`) VALUES
            (1, \'View Photos Page\', \'view_photos\', \'User can view photos page\', \'yes\'),
            (1, \'View Collections Page\', \'view_collections\', \'User can view collections page\', \'yes\');';
        self::query($sql);

        $sql = 'UPDATE `{tbl_prefix}languages` SET `language_id` = 1 WHERE `language_code` LIKE \'en\';';
        self::query($sql);

        $sql = 'INSERT INTO `{tbl_prefix}languages` (`language_id`, `language_code`, `language_name`, `language_regex`, `language_active`, `language_default`)
        VALUES (2, \'fr\', \'Français\', \'fra\', \'no\', \'no\');';
        self::query($sql);
    }
}