INSERT INTO `{tbl_prefix}config` (`configid`, `name`, `value`) VALUES
	(NULL, 'clientid', ''),
	(NULL, 'secretId', ''),
	(NULL, 'site_title', ''),
	(NULL, 'site_slogan', ''),
	(NULL, 'baseurl', ''),
	(NULL, 'basedir', ''),
	(NULL, 'template_dir', 'cb_28'),
	(NULL, 'player_file', 'cb_video_js.php'),
	(NULL, 'closed', '0'),
	(NULL, 'closed_msg', 'We are updating our website, please visit in a few minutes.'),
	(NULL, 'description', 'ClipBucketV5 is a photo & video sharing script, by Oxygenz'),
	(NULL, 'keywords', 'clip bucket video sharing website script'),
	(NULL, 'ffmpegpath', ''),
	(NULL, 'srate', '22050'),
	(NULL, 'r_height', ''),
	(NULL, 'r_width', ''),
	(NULL, 'resize', ''),
	(NULL, 'activation', '0'),
	(NULL, 'email_verification', '1'),
	(NULL, 'allow_registeration', '1'),
	(NULL, 'php_path', ''),
	(NULL, 'videos_list_per_page', '30'),
	(NULL, 'channels_list_per_page', '25'),
	(NULL, 'video_rating', '1'),
	(NULL, 'comment_rating', '1'),
	(NULL, 'video_download', '1'),
	(NULL, 'video_embed', '1'),
	(NULL, 'seo', 'no'),
	(NULL, 'admin_pages', '100'),
	(NULL, 'search_list_per_page', '25'),
	(NULL, 'recently_viewed_limit', '10'),
	(NULL, 'max_upload_size', '1000'),
	(NULL, 'sbrate', '128000'),
	(NULL, 'thumb_width', '120'),
	(NULL, 'thumb_height', '90'),
	(NULL, 'allow_upload', ''),
	(NULL, 'allowed_video_types', 'wmv,avi,divx,3gp,mov,mpeg,mpg,xvid,flv,asf,rm,dat,mp4,mkv,webm'),
	(NULL, 'allow_template_change', '1'),
	(NULL, 'allow_language_change', '1'),
	(NULL, 'default_site_lang', ''),
	(NULL, 'video_require_login', ''),
	(NULL, 'audio_codec', 'aac'),
	(NULL, 'remoteUpload', ''),
	(NULL, 'embedUpload', ''),
	(NULL, 'vrate', '25'),
	(NULL, 'num_thumbs', '5'),
	(NULL, 'big_thumb_width', '320'),
	(NULL, 'big_thumb_height', '240'),
	(NULL, 'disallowed_usernames', 'shit, asshole, fucker'),
	(NULL, 'min_age_reg', ''),
	(NULL, 'max_comment_chr', '800'),
	(NULL, 'user_comment_own', ''),
	(NULL, 'anonym_comments', 'yes'),
	(NULL, 'player_dir', 'CB_video_js'),
	(NULL, 'player_width', '661'),
	(NULL, 'player_height', '360'),
	(NULL, 'default_country_iso2', 'PK'),
	(NULL, 'videos_items_hme_page', '25'),
	(NULL, 'videos_items_ufav_page', '25'),
	(NULL, 'videos_items_uvid_page', '25'),
	(NULL, 'videos_items_search_page', '30'),
	(NULL, 'videos_item_channel_page', '25'),
	(NULL, 'users_items_subscriptions', '5'),
	(NULL, 'users_items_contacts_channel', '5'),
	(NULL, 'users_items_search_page', '12'),
	(NULL, 'min_video_title', '4'),
	(NULL, 'max_video_title', '80'),
	(NULL, 'min_video_desc', '5'),
	(NULL, 'max_video_desc', '300'),
	(NULL, 'video_categories', '4'),
	(NULL, 'min_video_tags', '3'),
	(NULL, 'max_video_tags', '30'),
	(NULL, 'video_codec', 'libx264'),
	(NULL, 'support_email', 'webmaster@localhost'),
	(NULL, 'website_email', 'webmaster@localhost'),
	(NULL, 'welcome_email', 'webmaster@localhost'),
	(NULL, 'date_format', 'Y-m-d'),
	(NULL, 'autoplay_video', 'no'),
	(NULL, 'max_profile_pic_size', '2500'),
	(NULL, 'max_profile_pic_width', '230'),
	(NULL, 'gravatars', ''),
	(NULL, 'picture_url', 'yes'),
	(NULL, 'picture_upload', 'yes'),
	(NULL, 'background_url', 'yes'),
	(NULL, 'background_upload', 'yes'),
	(NULL, 'max_bg_size', '2500'),
	(NULL, 'max_bg_width', '1600'),
	(NULL, 'background_color', 'yes'),
	(NULL, 'send_comment_notification', 'yes'),
	(NULL, 'approve_video_notification', 'yes'),
	(NULL, 'keep_mp4_as_is', 'yes'),
	(NULL, 'max_conversion', '1'),
	(NULL, 'allow_unicode_usernames', 'yes'),
	(NULL, 'min_username', '3'),
	(NULL, 'max_username', '15'),
	(NULL, 'allow_username_spaces', 'yes'),
	(NULL, 'comments_captcha', 'guests'),
	(NULL, 'player_logo_file', 'logo.jpg'),
	(NULL, 'own_photo_rating', ''),
	(NULL, 'mail_type', 'mail'),
	(NULL, 'smtp_host', ''),
	(NULL, 'smtp_user', ''),
	(NULL, 'smtp_pass', ''),
	(NULL, 'smtp_auth', 'no'),
	(NULL, 'smtp_port', ''),
	(NULL, 'use_subs', '1'),
	(NULL, 'photo_ratio', '16:10'),
	(NULL, 'photo_thumb_width', '600'),
	(NULL, 'photo_thumb_height', '75'),
	(NULL, 'photo_med_width', '300'),
	(NULL, 'photo_med_height', '116'),
	(NULL, 'photo_lar_width', '600'),
	(NULL, 'photo_crop', '1'),
	(NULL, 'photo_rating', '1'),
	(NULL, 'max_photo_size', '2'),
	(NULL, 'watermark_photo', '0'),
	(NULL, 'watermark_max_width', '120'),
	(NULL, 'watermark_placement', 'left:top'),
	(NULL, 'enable_video_file_upload', 'yes'),
	(NULL, 'enable_video_remote_upload', 'yes'),
	(NULL, 'enable_photo_file_upload', 'yes'),
	(NULL, 'load_embed_form', 'yes'),
	(NULL, 'load_link_video_form', 'yes'),
	(NULL, 'enable_groups', ''),
	(NULL, 'groupsSection', 'yes'),
	(NULL, 'videosSection', 'yes'),
	(NULL, 'photosSection', 'yes'),
	(NULL, 'homeSection', 'yes'),
	(NULL, 'signupSection', 'yes'),
	(NULL, 'uploadSection', 'yes'),
	(NULL, 'collectionsSection', 'yes'),
	(NULL, 'channelsSection', 'yes'),
	(NULL, 'max_video_duration', '320'),
	(NULL, 'embed_player_height', '250'),
	(NULL, 'embed_player_width', '300'),
	(NULL, 'autoplay_embed', 'no'),
	(NULL, 'playlistsSection', 'yes'),
	(NULL, 'photo_main_list', '10'),
	(NULL, 'photo_home_tabs', '30'),
	(NULL, 'photo_search_result', '30'),
	(NULL, 'photo_channel_page', '10'),
	(NULL, 'photo_user_photos', '20'),
	(NULL, 'photo_user_favorites', '20'),
	(NULL, 'photo_other_limit', '8'),
	(NULL, 'collection_per_page', '12'),
	(NULL, 'collection_search_result', '20'),
	(NULL, 'collection_home_top_collections', '4'),
	(NULL, 'collection_collection_top_collections', '6'),
	(NULL, 'collection_photos_top_collections', '6'),
	(NULL, 'collection_items_page', '20'),
	(NULL, 'channel_rating', '1'),
	(NULL, 'own_channel_rating', '1'),
	(NULL, 'collection_rating', '1'),
	(NULL, 'own_collection_rating', '1'),
	(NULL, 'own_video_rating', '1'),
	(NULL, 'store_guest_session', '0'),
	(NULL, 'delete_mass_upload', 'no'),
	(NULL, 'comments_per_page', '15'),
	(NULL, 'feedsSection', 'yes'),
	(NULL, 'seo_vido_url', '1'),
	(NULL, 'use_cached_pagin', 'yes'),
	(NULL, 'cached_pagin_time', '5'),
	(NULL, 'player_logo_url', '#'),
	(NULL, 'ffprobe_path', ''),
	(NULL, 'media_info', ''),
	(NULL, 'photo_activation', '1'),
	(NULL, 'popup_video', 'yes'),
	(NULL, 'video_round_views', 'yes'),
	(NULL, 'access_to_logged_in', 'no'),
	(NULL, 'pick_geo_country', 'yes'),
	(NULL, 'password_salt', SUBSTRING(HEX(SHA2(CONCAT(NOW(), RAND(), UUID()), 512)),1, 32)),
	(NULL, 'show_collapsed_checkboxes', '0'),
	(NULL, 'enable_advertisement', 'no'),
	(NULL, 'chromecast', 'yes'),
	(NULL, 'vid_cat_width', '120'),
	(NULL, 'vid_cat_height', '120'),
	(NULL, 'chromecast_fix', '1'),
	(NULL, 'allowed_photo_types', 'jpg,jpeg,png'),
	(NULL, 'logo_name', ''),
	(NULL, 'favicon_name', ''),
	(NULL, 'comment_per_page', '10'),
	(NULL, 'stay_mp4', 'no'),
	(NULL, 'allow_conversion_1_percent', 'yes'),
	(NULL, 'force_8bits', '1'),
	(NULL, 'bits_color_warning', '1'),
	(NULL, 'control_bar_logo', 'yes'),
	(NULL, 'contextual_menu_disabled', ''),
	(NULL, 'control_bar_logo_url', '/images/icons/player-logo.png'),
	(NULL, 'player_thumbnails', 'yes'),
	(NULL, 'enable_update_checker', '1'),
	(NULL, 'email_domain_restriction', ''),
	(NULL, 'proxy_enable', 'no'),
	(NULL, 'proxy_auth', 'no'),
	(NULL, 'proxy_url', ''),
	(NULL, 'proxy_port', ''),
	(NULL, 'proxy_username', ''),
	(NULL, 'proxy_password', ''),
	(NULL, 'player_default_resolution', '1080'),
	(NULL, 'keep_audio_tracks', '1'),
	(NULL, 'keep_subtitles', '1'),
	(NULL, 'extract_subtitles', '1'),
	(NULL, 'player_subtitles', '1'),
	(NULL, 'subtitle_format', 'webvtt'),
	(NULL, 'conversion_type', 'mp4'),
	(NULL, 'enable_sub_collection', 'yes'),
	(NULL, 'player_default_resolution_hls', 'auto'),
    (NULL, 'cache_enable', 'no'),
    (NULL, 'cache_auth', 'no'),
    (NULL, 'cache_host', ''),
    (NULL, 'cache_password', ''),
    (NULL, 'cache_port', ''),
    (NULL, 'disable_email', 'no'),
    (NULL, 'enable_country', 'no'),
    (NULL, 'enable_gender', 'no'),
    (NULL, 'enable_user_category', 'no'),
    (NULL, 'enable_rss_feeds', 'no'),
    (NULL, 'enable_user_firstname_lastname', 'no'),
    (NULL, 'enable_user_relation_status', 'no'),
    (NULL, 'enable_user_postcode', 'no'),
    (NULL, 'enable_user_hometown', 'no'),
    (NULL, 'enable_user_city', 'no'),
    (NULL, 'enable_user_education', 'no'),
    (NULL, 'enable_user_schools', 'no'),
    (NULL, 'enable_user_occupation', 'no'),
    (NULL, 'enable_user_compagnies', 'no'),
    (NULL, 'enable_user_hobbies', 'no'),
    (NULL, 'enable_user_favorite_movies', 'no'),
    (NULL, 'enable_user_favorite_music', 'no'),
    (NULL, 'enable_user_favorite_books', 'no'),
    (NULL, 'enable_user_about', 'no'),
    (NULL, 'enable_user_website', 'no'),
    (NULL, 'enable_user_status', 'no'),
    (NULL, 'enable_video_social_sharing', 'yes'),
    (NULL, 'enable_video_internal_sharing', 'yes'),
    (NULL, 'enable_video_link_sharing', 'yes'),
    (NULL, 'tmdb_token', ''),
    (NULL, 'enable_tmdb', 'no'),
    (NULL, 'enable_user_dob_edition', 'yes'),
    (NULL, 'enable_age_restriction', 'yes'),
    (NULL, 'enable_blur_restricted_content', 'no'),
    (NULL, 'enable_global_age_restriction', 'no'),
    (NULL, 'enable_quicklist', 'yes'),
    (NULL, 'hide_empty_collection', 'yes'),
    (NULL, 'enable_sitemap', 'yes'),
    (NULL, 'git_path', ''),
    (NULL, 'tmdb_get_genre', 'yes'),
    (NULL, 'tmdb_get_actors', 'yes'),
    (NULL, 'tmdb_get_producer', 'yes'),
    (NULL, 'tmdb_get_executive_producer', 'yes'),
    (NULL, 'tmdb_get_director', 'yes'),
    (NULL, 'tmdb_get_crew', 'yes'),
    (NULL, 'tmdb_get_poster', 'no'),
    (NULL, 'tmdb_get_release_date', 'yes'),
    (NULL, 'tmdb_get_title', 'yes'),
    (NULL, 'tmdb_get_description', 'yes'),
    (NULL, 'tmdb_get_backdrop', 'no'),
    (NULL, 'tmdb_get_age_restriction', 'yes'),
    (NULL, 'enable_video_genre', 'yes'),
    (NULL, 'enable_video_actor', 'yes'),
    (NULL, 'enable_video_producer', 'yes'),
    (NULL, 'enable_video_executive_producer', 'yes'),
    (NULL, 'enable_video_director', 'yes'),
    (NULL, 'enable_video_crew', 'yes'),
    (NULL, 'enable_video_poster', 'no'),
    (NULL, 'enable_video_backdrop', 'no'),
    (NULL, 'tmdb_search', '10'),
    (NULL, 'enable_edit_button', 'yes'),
    (NULL, 'only_keep_max_resolution', 'no'),
    (NULL, 'enable_tmdb_mature_content', 'no'),
    (NULL, 'tmdb_mature_content_age', '18'),
    (NULL, 'tmdb_enable_on_front_end', 'no'),
    (NULL, 'enable_comments_censor', 'no'),
    (NULL, 'enable_video_description_censor', 'no'),
    (NULL, 'enable_video_description_link', 'yes'),
    (NULL, 'censored_words', ''),
    (NULL, 'enable_chunk_upload', 'yes'),
    (NULL, 'chunk_upload_size', '2'),
    (NULL, 'cloudflare_upload_limit', '100'),
    (NULL, 'nginx_path', ''),
    (NULL, 'enable_edit_photo_button', 'yes'),
    (NULL, 'enable_comments_video', 'yes'),
    (NULL, 'enable_comments_photo', 'yes'),
    (NULL, 'enable_comments_collection', 'yes'),
    (NULL, 'enable_comments_channel', 'yes');

INSERT INTO `{tbl_prefix}video_resolution` (`title`, `ratio`, `enabled`, `width`, `height`, `video_bitrate`) VALUES
	('240p', '16/9', 1, 428, 240, 240000),
	('360p', '16/9', 1, 640, 360, 400000),
	('480p', '16/9', 1, 854, 480, 700000),
	('720p', '16/9', 1, 1280, 720, 2500000),
	('1080p', '16/9', 1, 1920, 1080, 4096000),
	('1440p', '16/9', 0, 2560, 1440, 7280000),
	('2160p', '16/9', 0, 4096, 2160, 17472000);

INSERT INTO `{tbl_prefix}tools_histo_status` (`language_key_title`) VALUES ('ready'), ('in_progress'), ('stopping');
INSERT INTO `{tbl_prefix}tools` (`language_key_label`, `language_key_description`, `function_name`, `code`) VALUES
    ('generate_missing_thumbs_label', 'generate_missing_thumbs_description', 'AdminTool::generateMissingThumbs', 'generate_missing_thumbs'),
    ('update_castable_status_label', 'update_castable_status_description', 'AdminTool::updateCastableStatus', 'update_castable_status'),
    ('update_bits_color_label', 'update_bits_color_description', 'AdminTool::updateBitsColor', 'update_bits_color'),
    ('update_videos_duration_label', 'update_videos_duration_description', 'AdminTool::updateVideoDuration', 'update_videos_duration'),
    ('update_database_version_label', 'update_database_version_description', 'AdminTool::updateDataBaseVersion', 'update_database_version'),
    ('reset_cache_label', 'reset_cache_description', 'AdminTool::resetCache', 'reset_cache'),
    ('reset_video_log_label', 'reset_video_log_description', 'AdminTool::resetVideoLog', 'reset_video_log'),
    ('clean_orphan_files_label', 'clean_orphan_files_description', 'AdminTool::cleanOrphanFiles', 'clean_orphan_files'),
    ('repair_video_duration_label', 'repair_video_duration_description', 'AdminTool::repairVideoDuration', 'repair_video_duration'),
    ('clean_orphan_tags', 'clean_orphan_tags_description', 'AdminTool::cleanOrphanTags', 'clean_orpha'),
    ('update_core_label', 'update_core_description', 'AdminTool::updateCore', 'update_core'),
    ('clean_session_table_label', 'clean_session_table_description', 'AdminTool::cleanSessionTable', 'clean_session_table'),
    ('tool_recalcul_video_file_label', 'tool_recalcul_video_file_description', 'AdminTool::recalculVideoFile', 'tool_recalcul_video_file'),
    ('recreate_thumb_label', 'recreate_thumb_description', 'AdminTool::recreateThumb', 'recreate_thumb');

INSERT INTO `{tbl_prefix}tags_type` (`name`) VALUES ('video'), ('photo'), ('collection'), ('profile'), ('playlist'), ('actors'), ('producer'), ('executive_producer'), ('director'), ('crew'), ('genre');

UPDATE `{tbl_prefix}video_thumbs` SET `type` = 'auto' WHERE `type` IS NULL;

INSERT INTO `{tbl_prefix}categories_type` (`name`)
VALUES ('video'),
       ('photo'),
       ('collection'),
       ('user'),
       ('playlist');

SET @type_collection = (
    SELECT id_category_type
    FROM `{tbl_prefix}categories_type`
    WHERE name LIKE 'collection'
);
SET @type_user = (
    SELECT id_category_type
    FROM `{tbl_prefix}categories_type`
    WHERE name LIKE 'user'
);
SET @type_video = (
    SELECT id_category_type
    FROM `{tbl_prefix}categories_type`
    WHERE name LIKE 'video'
);

INSERT INTO `{tbl_prefix}categories` (`id_category_type`, `category_name`, `category_thumb`, `is_default`) VALUES
    (@type_collection, 'Uncategorized', '', 'yes'),
    (@type_user, 'Basic User', '', 'yes'),
    (@type_user, 'Gurus', '', 'no'),
    (@type_user, 'Comedian', '', 'no'),
    (@type_video, 'Uncategorized','', 'yes');
