INSERT INTO `{tbl_prefix}user_levels` (`user_level_id`, `user_level_active`, `user_level_name`, `user_level_is_origin`, `user_level_is_default`)
VALUES (1, 'yes', 'Administrator', 'yes', 'no'),
       (2, 'yes', 'Registered User', 'yes', 'yes'),
       (3, 'yes', 'Inactive User', 'yes', 'no'),
       (4, 'yes', 'Guest', 'yes', 'no'),
       (5, 'yes', 'Global Moderator', 'yes', 'no'),
       (6, 'no', 'Anonymous', 'yes', 'no');


INSERT INTO `{tbl_prefix}user_permission_types` (`user_permission_type_id`, `user_permission_type_name`, `user_permission_type_desc`)
VALUES (1, 'Viewing Permission', ''),
       (2, 'Uploading Permission', ''),
       (3, 'Administrator Permission', ''),
       (4, 'General Permission', '');


INSERT INTO `{tbl_prefix}user_levels_permissions` (`id_user_levels_permission`, `id_user_permission_types`, `permission_name`, `permission_description`)
VALUES (1, 3, 'admin_access', 'admin_access_desc'),
       (2, 2, 'allow_video_upload', 'allow_video_upload_desc'),
       (3, 2, 'allow_photo_upload', 'allow_photo_upload_desc'),
       (4, 1, 'view_video', 'view_video_desc'),
       (5, 1, 'view_photos', 'view_photos_desc'),
       (6, 1, 'view_collections', 'view_collections_desc'),
       (7, 1, 'view_channel', 'view_channel_desc'),
       (8, 1, 'view_videos', 'view_videos_desc'),
       (9, 2, 'avatar_upload', 'avatar_upload_desc'),
       (10, 3, 'video_moderation', 'video_moderation_desc'),
       (11, 3, 'member_moderation', 'member_moderation_desc'),
       (12, 3, 'ad_manager_access', 'ad_manager_access_desc'),
       (13, 3, 'manage_template_access', 'manage_template_access_desc'),
       (14, 3, 'group_moderation', 'group_moderation_desc'),
       (15, 3, 'web_config_access', 'web_config_access_desc'),
       (16, 1, 'view_channels', 'view_channels_desc'),
       (17, 1, 'playlist_access', 'playlist_access_desc'),
       (18, 2, 'allow_channel_bg', 'allow_channel_bg_desc'),
       (19, 4, 'private_msg_access', 'private_msg_access_desc'),
       (20, 4, 'edit_video', 'edit_video_desc'),
       (21, 4, 'download_video', 'download_video_desc'),
       (22, 3, 'admin_del_access', 'admin_del_access_desc'),
       (23, 3, 'photos_moderation', 'photos_moderation_desc'),
       (24, 3, 'collection_moderation', 'collection_moderation_desc'),
       (25, 3, 'plugins_moderation', 'plugins_moderation_desc'),
       (26, 3, 'tool_box', 'tool_box_desc'),
       (27, 3, 'allow_manage_user_level', 'allow_manage_user_level_desc'),
       (28, 2, 'allow_create_collection', 'allow_create_collection_desc'),
       (29, 2, 'allow_create_playlist', 'allow_create_playlist_desc'),
       (30, 4, 'enable_channel_page', 'enable_channel_page_desc'),
       (31, 3, 'email_template_management', 'email_template_management_desc'),
       (32, 1, 'allow_public_video_page', 'allow_public_video_page'),
       (33, 4, 'default_homepage', 'default_homepage_desc');

INSERT INTO `{tbl_prefix}user_levels_permissions_values` (`user_level_id`, `id_user_levels_permission`, `permission_value`)
VALUES (1, 1, 'yes'),
       (1, 2, 'yes'),
       (1, 3, 'yes'),
       (1, 4, 'yes'),
       (1, 5, 'yes'),
       (1, 6, 'yes'),
       (1, 7, 'yes'),
       (1, 8, 'yes'),
       (1, 9, 'yes'),
       (1, 10, 'yes'),
       (1, 11, 'yes'),
       (1, 12, 'yes'),
       (1, 13, 'yes'),
       (1, 14, 'yes'),
       (1, 15, 'yes'),
       (1, 16, 'yes'),
       (1, 17, 'yes'),
       (1, 18, 'yes'),
       (1, 19, 'yes'),
       (1, 20, 'yes'),
       (1, 21, 'yes'),
       (1, 22, 'yes'),
       (1, 23, 'yes'),
       (1, 24, 'yes'),
       (1, 25, 'yes'),
       (1, 26, 'yes'),
       (1, 27, 'yes'),
       (1, 28, 'yes'),
       (1, 29, 'yes'),
       (1, 30, 'yes'),
       (1, 31, 'yes'),
       (1, 32, 'no'),
       (1, 33, 'homepage'),

       (2, 1, 'no'),
       (2, 2, 'yes'),
       (2, 3, 'yes'),
       (2, 4, 'yes'),
       (2, 5, 'yes'),
       (2, 6, 'yes'),
       (2, 7, 'yes'),
       (2, 8, 'yes'),
       (2, 9, 'yes'),
       (2, 10, 'no'),
       (2, 11, 'no'),
       (2, 12, 'no'),
       (2, 13, 'no'),
       (2, 14, 'no'),
       (2, 15, 'no'),
       (2, 16, 'yes'),
       (2, 17, 'yes'),
       (2, 18, 'yes'),
       (2, 19, 'yes'),
       (2, 20, 'yes'),
       (2, 21, 'yes'),
       (2, 22, 'no'),
       (2, 23, 'no'),
       (2, 24, 'no'),
       (2, 25, 'no'),
       (2, 26, 'no'),
       (2, 27, 'no'),
       (2, 28, 'yes'),
       (2, 29, 'yes'),
       (2, 30, 'yes'),
       (2, 31, 'no'),
       (2, 33, 'homepage'),
       (3, 1, 'no'),
       (3, 2, 'no'),
       (3, 3, 'yes'),
       (3, 4, 'yes'),
       (3, 5, 'yes'),
       (3, 6, 'yes'),
       (3, 7, 'yes'),
       (3, 8, 'yes'),
       (3, 9, 'no'),
       (3, 10, 'no'),
       (3, 11, 'no'),
       (3, 12, 'no'),
       (3, 13, 'no'),
       (3, 14, 'no'),
       (3, 15, 'no'),
       (3, 16, 'yes'),
       (3, 17, 'yes'),
       (3, 18, 'yes'),
       (3, 19, 'yes'),
       (3, 20, 'yes'),
       (3, 21, 'yes'),
       (3, 22, 'no'),
       (3, 23, 'no'),
       (3, 24, 'no'),
       (3, 25, 'no'),
       (3, 26, 'no'),
       (3, 27, 'no'),
       (3, 28, 'yes'),
       (3, 29, 'yes'),
       (3, 30, 'yes'),
       (3, 31, 'no'),
       (3, 33, 'homepage'),
       (4, 1, 'no'),
       (4, 2, 'no'),
       (4, 3, 'no'),
       (4, 4, 'yes'),
       (4, 5, 'yes'),
       (4, 6, 'yes'),
       (4, 7, 'yes'),
       (4, 8, 'yes'),
       (4, 9, 'no'),
       (4, 10, 'no'),
       (4, 11, 'no'),
       (4, 12, 'no'),
       (4, 13, 'no'),
       (4, 14, 'no'),
       (4, 15, 'no'),
       (4, 16, 'yes'),
       (4, 17, 'yes'),
       (4, 18, 'no'),
       (4, 19, 'no'),
       (4, 20, 'no'),
       (4, 21, 'yes'),
       (4, 22, 'no'),
       (4, 23, 'no'),
       (4, 24, 'no'),
       (4, 25, 'no'),
       (4, 26, 'no'),
       (4, 27, 'no'),
       (4, 28, 'no'),
       (4, 29, 'no'),
       (4, 30, 'no'),
       (4, 31, 'no'),
       (4, 33, 'homepage'),
       (5, 1, 'yes'),
       (5, 2, 'yes'),
       (5, 3, 'yes'),
       (5, 4, 'yes'),
       (5, 5, 'yes'),
       (5, 6, 'yes'),
       (5, 7, 'yes'),
       (5, 8, 'yes'),
       (5, 9, 'yes'),
       (5, 10, 'yes'),
       (5, 11, 'yes'),
       (5, 12, 'no'),
       (5, 13, 'no'),
       (5, 14, 'no'),
       (5, 15, 'no'),
       (5, 16, 'yes'),
       (5, 17, 'yes'),
       (5, 18, 'yes'),
       (5, 19, 'yes'),
       (5, 20, 'yes'),
       (5, 21, 'yes'),
       (5, 22, 'no'),
       (5, 23, 'no'),
       (5, 24, 'no'),
       (5, 25, 'no'),
       (5, 26, 'no'),
       (5, 27, 'no'),
       (5, 28, 'yes'),
       (5, 29, 'yes'),
       (5, 30, 'yes'),
       (5, 31, 'no'),
       (5, 33, 'homepage'),
       (6, 1, 'no'),
       (6, 2, 'yes'),
       (6, 3, 'yes'),
       (6, 4, 'no'),
       (6, 5, 'yes'),
       (6, 6, 'yes'),
       (6, 7, 'no'),
       (6, 8, 'no'),
       (6, 9, 'yes'),
       (6, 10, 'no'),
       (6, 11, 'no'),
       (6, 12, 'no'),
       (6, 13, 'no'),
       (6, 14, 'no'),
       (6, 15, 'no'),
       (6, 16, 'no'),
       (6, 17, 'no'),
       (6, 18, 'yes'),
       (6, 19, 'no'),
       (6, 20, 'no'),
       (6, 21, 'yes'),
       (6, 22, 'no'),
       (6, 23, 'no'),
       (6, 24, 'no'),
       (6, 25, 'no'),
       (6, 26, 'no'),
       (6, 27, 'no'),
       (6, 28, 'yes'),
       (6, 29, 'yes'),
       (6, 30, 'yes'),
       (6, 31, 'no'),
       (6, 32, 'no'),
       (6, 33, 'homepage');
