-- $Id$

INSERT INTO `{tbl_prefix}config` (
`name` ,
`value`
)
VALUES
('default_country_iso2', 'PK'),
('channel_comments', '1'),
('max_profile_pic_size', '25'),
('max_profile_pic_height', ''),
('max_profile_pic_width', '140'),
('gravatars', 'yes'),
('picture_url', 'yes'),
('picture_upload', 'yes'),
('background_url', 'yes'),
('background_upload', 'yes'),
('max_bg_size', '25'),
('max_bg_width', ''),
('max_bg_height', '600'),
('background_color', 'yes'),
('send_comment_notification', 'no'),
('approve_video_notification', 'yes'),
('keep_mp4_as_is', 'yes'),
('hq_output', 'yes'),
('grp_categories', '3'),
('grps_items_search_page', '24'),
('grp_thumb_height', '140'),
('grp_thumb_width', '140'),
('grp_max_title', '20'),
('grp_max_desc', '500'),
('quick_conv', 'yes'),
('server_friendly_conversion', 'yes'),
('max_conversion', '2'),
('max_time_wait', '7200'),
('allow_unicode_usernames', 'yes'),
('min_username', '3'),
('max_username', '15');


INSERT INTO `{tbl_prefix}email_templates` (`email_template_name`, `email_template_code`, `email_template_subject`, `email_template`, `email_template_allowed_tags`)
VALUES
('Group Invitation', 'group_invitation', '[{website_title}] {sender} has invited you to join group &#8220;{group_name}&#8221;', '{sender} invited you to join the {website_title} group "{group_name}".\r\n\r\n{group_description}\r\n\r\nTo see more details and confirm this group invitation, follow the link below:\r\n<a href="{group_url}">{group_url}</a>\r\n\r\nThanks,\r\n{website_title}', 'sender,reciever,group_name,group_url'),
('Contact Form', 'contact_form', '[{website_title} - Contact] {reason} from {name}', 'Name : {name}\r\nEmail : {email}\r\nReason : {reason}\r\n\r\nMessage:\r\n{message}\r\n\r\n===============\r\nIp : {ip_address}\r\ndate : {now}', ''),
('Video Acitvation Email', 'video_activation_email', '[{website_title}] - Your video has been activated', 'Hell {username},\r\nYour video has been reviewed and activated by one of our staff, thanks for uploading this video. You can view this video here.\r\n{video_link}\r\n\r\nThanks\r\n{website_title} Team', ''),
('User Comment Email', 'user_comment_email', '[{website_title}] {username} made comment on your {obj}', '{username} has commented on your {obj}\r\n"{comment}"\r\n\r\n<a href="{obj_link}">{obj_link}</a>\r\n\r\n{website_title} team', '');



DELETE FROM `{tbl_prefix}phrases` WHERE lang_iso ='en' ;

INSERT INTO `{tbl_prefix}phrases` (`id`, `lang_iso`, `varname`, `text`) VALUES
(3338, 'en', 'ad_name_error', 'Please enter a name for the Advertisment'),
(3339, 'en', 'ad_code_error', 'Error : Please enter a code for the Advertisement'),
(3340, 'en', 'ad_exists_error1', 'Advertisement does not exist'),
(3341, 'en', 'ad_exists_error2', 'Error : Advertisement with this name already exist'),
(3342, 'en', 'ad_add_msg', 'Advertisment was added succesfully'),
(3343, 'en', 'ad_msg', 'Ad Has Been '),
(3344, 'en', 'ad_update_msg', 'Advertisment has been Updated'),
(3345, 'en', 'ad_del_msg', 'Advertisement has been Deleted'),
(3346, 'en', 'ad_deactive', 'Deactivated'),
(3347, 'en', 'ad_active', 'Activated'),
(3348, 'en', 'ad_placment_delete_msg', 'Placement has been Removed'),
(3349, 'en', 'ad_placement_err1', 'Placement already exists'),
(3350, 'en', 'ad_placement_err2', 'Please Enter a name for the Placement'),
(3351, 'en', 'ad_placement_err3', 'Please Enter a Code for the Placement'),
(3352, 'en', 'ad_placement_msg', 'Placement has been Added'),
(3353, 'en', 'cat_img_error', 'Please Upload JPEG, GIF or PNG image only'),
(3354, 'en', 'cat_exist_error', 'Category doesn&#8217;t exist'),
(3355, 'en', 'cat_add_msg', 'Category has been added successfully'),
(3356, 'en', 'cat_update_msg', 'Category has been updated'),
(3357, 'en', 'grp_err', 'Group Doesn&#8217;t Exist'),
(3358, 'en', 'grp_fr_msg', 'Group has been set as featured'),
(3359, 'en', 'grp_fr_msg1', 'Selected Groups Have Been Removed From The Featured List'),
(3360, 'en', 'grp_ac_msg', 'Selected Groups Have Been Activated'),
(3361, 'en', 'grp_dac_msg', 'Selected Groups Have Been Dectivated'),
(3362, 'en', 'grp_del_msg', 'Group has been deleted'),
(3363, 'en', 'editor_pic_up', 'Video Has Been Moved Up'),
(3364, 'en', 'editor_pic_down', 'Video Has Been Moved Down'),
(3365, 'en', 'plugin_install_msg', 'Plugin has been installed'),
(3366, 'en', 'plugin_no_file_err', 'No file was found'),
(3367, 'en', 'plugin_file_detail_err', 'Unknown plugin details found'),
(3368, 'en', 'plugin_installed_err', 'Plugin already installed'),
(3369, 'en', 'plugin_no_install_err', 'Plugin is not installed'),
(3370, 'en', 'grp_name_error', 'Please enter group name'),
(3371, 'en', 'grp_name_error1', 'Group Name Already Exists'),
(3372, 'en', 'grp_des_error', 'Please Enter A Little Description For The Group'),
(3373, 'en', 'grp_tags_error', 'Please Enter Tags For The Group'),
(3374, 'en', 'grp_url_error', 'Please enter valid url for the Group'),
(3375, 'en', 'grp_url_error1', 'Please enter Valid URL name'),
(3376, 'en', 'grp_url_error2', 'Group URL Already Exists, Please Choose a Different URL'),
(3377, 'en', 'grp_tpc_error', 'Please enter a topic to add'),
(3378, 'en', 'grp_comment_error', 'You must enter a comment'),
(3379, 'en', 'grp_join_error', 'You have already joined this group'),
(3380, 'en', 'grp_prvt_error', 'This Group Is Private, Please Login to View this Group'),
(3381, 'en', 'grp_inact_error', 'This Group Is Inactive, Please Contact Administrator for the problem'),
(3382, 'en', 'grp_join_error1', 'You Have Not Joined This Group Yet'),
(3383, 'en', 'grp_exist_error', 'Sorry, Group Doesn&#8217;t Exist'),
(3384, 'en', 'grp_tpc_error1', 'This Topic is not approved by the Group Owner'),
(3385, 'en', 'grp_cat_error', 'Please Select A Category For Your group'),
(3386, 'en', 'grp_tpc_error2', 'Please enter a topic to add'),
(3387, 'en', 'grp_tpc_error3', 'Your Topic Requires Approval From The Owner Of This Group'),
(3388, 'en', 'grp_tpc_msg', 'Topic has been added'),
(3389, 'en', 'grp_comment_msg', 'Comment has been added'),
(3390, 'en', 'grp_vdo_msg', 'Videos Deleted'),
(3391, 'en', 'grp_vdo_msg1', 'Videos Added Successfully'),
(3392, 'en', 'grp_vdo_msg2', 'Videos Have Been Approved'),
(3393, 'en', 'grp_mem_msg', 'Member Has Been Deleted'),
(3394, 'en', 'grp_mem_msg1', 'Member Has Been Approved'),
(3395, 'en', 'grp_inv_msg', 'Your Invitation Has Been Sent'),
(3396, 'en', 'grp_tpc_msg1', 'Topic has been deleted'),
(3397, 'en', 'grp_tpc_msg2', 'Topic Has Been Approved'),
(3398, 'en', 'grp_fr_msg2', 'Group has been removed from featured list'),
(3399, 'en', 'grp_inv_msg1', 'Has Invited You To Join '),
(3400, 'en', 'grp_av_msg', 'Group has been activated'),
(3401, 'en', 'grp_da_msg', 'Group has been deactivated'),
(3402, 'en', 'grp_post_msg', 'Post Has Been Deleted'),
(3403, 'en', 'grp_update_msg', 'Group has been updated'),
(3404, 'en', 'grp_owner_err', 'Only Owner Can Add Videos To This Group'),
(3405, 'en', 'grp_owner_err1', 'You are not owner of this group'),
(3406, 'en', 'grp_owner_err2', 'You are the owner of this group. You cannot leave your group.'),
(3407, 'en', 'grp_prvt_err1', 'This group is private, you need invitiation from its owner in order to join'),
(3408, 'en', 'grp_rmv_msg', 'Selected Groups Have Been Removed From Your Account'),
(3409, 'en', 'grp_tpc_err4', 'Sorry, Topic Doesn&#8217;t Exist'),
(3410, 'en', 'grp_title_topic', 'Groups - Topic - '),
(3411, 'en', 'grp_add_title', '- Add Video'),
(3412, 'en', 'usr_sadmin_err', 'You Cannot Set SuperAdmin Username as Blank'),
(3413, 'en', 'usr_cpass_err', 'Confirm Password Doesn&#8217;t Match'),
(3414, 'en', 'usr_pass_err', 'Old password is incorrect'),
(3415, 'en', 'usr_email_err', 'Please Provide A Valid Email Address'),
(3416, 'en', 'usr_cpass_err1', 'Confirm password is incorrect'),
(3417, 'en', 'usr_pass_err1', 'Password is Incorrect'),
(3418, 'en', 'usr_cmt_err', 'You Must Login First To Comment'),
(3419, 'en', 'usr_cmt_err1', 'Please Type Something In the Comment Box'),
(3420, 'en', 'usr_cmt_err2', 'You cannot comment on your video'),
(3421, 'en', 'usr_cmt_err3', 'You Have Already Posted a Comment on this channel.'),
(3422, 'en', 'usr_cmt_err4', 'Comment Has Been Added'),
(3423, 'en', 'usr_cmt_del_msg', 'Comment Has Been Deleted'),
(3424, 'en', 'usr_cmt_del_err', 'An Error Occured While deleting a Comment'),
(3425, 'en', 'usr_cnt_err', 'You Cannot Add Yourself as a Contact'),
(3426, 'en', 'usr_cnt_err1', 'You Have Already Added This User To Your Contact List'),
(3427, 'en', 'usr_sub_err', 'You are already subscribed to %s'),
(3428, 'en', 'usr_exist_err', 'User Doesnt Exist'),
(3429, 'en', 'usr_ccode_err', 'You Have Entered Wrong Confirmation Code'),
(3430, 'en', 'usr_exist_err1', 'Sorry, No User Exists With This Email'),
(3431, 'en', 'usr_exist_err2', 'Sorry , User Doesn’t Exist'),
(3432, 'en', 'usr_uname_err', 'Username is empty'),
(3433, 'en', 'usr_uname_err2', 'Username already exists'),
(3434, 'en', 'usr_pass_err2', 'Password Is Empty'),
(3435, 'en', 'usr_email_err1', 'Email is Empty'),
(3436, 'en', 'usr_email_err2', 'Please Enter A Valid Email Address'),
(3437, 'en', 'usr_email_err3', 'Email Address Is Already In Use'),
(3438, 'en', 'usr_pcode_err', 'Postal Codes Only Contain Numbers'),
(3439, 'en', 'usr_fname_err', 'First Name Is Empty'),
(3440, 'en', 'usr_lname_err', 'Last Name Is Empty'),
(3441, 'en', 'usr_uname_err3', 'Username Contains Unallowed Characters'),
(3442, 'en', 'usr_pass_err3', 'Passwords MisMatched'),
(3443, 'en', 'usr_dob_err', 'Please Select Date Of Birth'),
(3444, 'en', 'usr_ament_err', 'Sorry, you need to agree to the terms of use and privacy policy to create an account'),
(3445, 'en', 'usr_reg_err', 'Sorry, Registrations Are Temporarily Not Allowed, Please Try Again Later'),
(3446, 'en', 'usr_ban_err', 'User account is banned, please contact website administrator'),
(3447, 'en', 'usr_login_err', 'Username and Password Didn&#8217;t Match'),
(3448, 'en', 'usr_sadmin_msg', 'Super Admin Has Been Updated'),
(3449, 'en', 'usr_pass_msg', 'Your Password Has Been Changed'),
(3450, 'en', 'usr_cnt_msg', 'This User Has Been Added To Your Contact List'),
(3451, 'en', 'usr_sub_msg', 'You are now subsribed to %s'),
(3452, 'en', 'usr_uname_email_msg', 'We Have Sent you an Email containing Your Username, Please Check It'),
(3453, 'en', 'usr_rpass_email_msg', 'An Email Has Been Sent To You. Please Follow the Instructions there to Reset Your Password'),
(3454, 'en', 'usr_pass_email_msg', 'Password has been changed successfully'),
(3455, 'en', 'usr_email_msg', 'Email Settings Has Been Updated'),
(3456, 'en', 'usr_del_msg', 'User has been deleted'),
(3457, 'en', 'usr_dels_msg', 'Selected Users Have Been Deleted'),
(3458, 'en', 'usr_ac_msg', 'User has been activated'),
(3459, 'en', 'usr_dac_msg', 'User has been deactivated'),
(3460, 'en', 'usr_mem_ac', 'Selected Members Have Been Activated'),
(3461, 'en', 'usr_mems_ac', 'Selected Members Have Been Deactivated'),
(3462, 'en', 'usr_fr_msg', 'User Has Been Made a Featured Member'),
(3463, 'en', 'usr_ufr_msg', 'User Has Been Unfeatured'),
(3464, 'en', 'usr_frs_msg', 'Selected Users Have Been Set As Featured'),
(3465, 'en', 'usr_ufrs_msg', 'Selected Users Have Been Removed From The Featured List'),
(3466, 'en', 'usr_uban_msg', 'User Has Been Banned'),
(3467, 'en', 'usr_uuban_msg', 'User Has Been Unbanned'),
(3468, 'en', 'usr_ubans_msg', 'Selected Members Have Been Banned'),
(3469, 'en', 'usr_uubans_msg', 'Selected Members Have Been Unbanned'),
(3470, 'en', 'usr_pass_reset_conf', 'Password Reset Confirmation'),
(3471, 'en', 'usr_dear_user', 'Dear User'),
(3472, 'en', 'usr_pass_reset_msg', 'You Requested A Password Reset, Follow The Link To Reset Your Password'),
(3473, 'en', 'usr_rpass_msg', 'Password Has Been Reset'),
(3474, 'en', 'usr_rpass_req_msg', 'You Requested A Password Reset, Here is your new password : '),
(3475, 'en', 'usr_uname_req_msg', 'You Requested to Recover Your Username, Here is your username: '),
(3476, 'en', 'usr_uname_recovery', 'Username Recovery Email'),
(3477, 'en', 'usr_add_succ_msg', 'User Has Been Added'),
(3478, 'en', 'usr_upd_succ_msg', 'User has been updated'),
(3479, 'en', 'usr_activation_msg', 'Your account has been activated. Now you can login to your account and upload videos'),
(3480, 'en', 'usr_activation_err', 'This user is already activated'),
(3481, 'en', 'usr_activation_em_msg', 'We have sent you an email containing your activation code, please check your mail box'),
(3482, 'en', 'usr_activation_em_err', 'Email Doesn&#8217;t Exist or a User With This Email is already Activated'),
(3483, 'en', 'usr_no_msg_del_err', 'No Message Was Selected To Delete'),
(3484, 'en', 'usr_sel_msg_del_msg', 'Selected Messages Have Been Deleted'),
(3485, 'en', 'usr_pof_upd_msg', 'Profile has been updated'),
(3486, 'en', 'usr_arr_no_ans', 'no answer'),
(3487, 'en', 'usr_arr_elementary', 'Elementary'),
(3488, 'en', 'usr_arr_hi_school', 'High School'),
(3489, 'en', 'usr_arr_some_colg', 'Some College'),
(3490, 'en', 'usr_arr_assoc_deg', 'Associates Degree'),
(3491, 'en', 'usr_arr_bach_deg', 'Bachelor&#8217;s Degree'),
(3492, 'en', 'usr_arr_mast_deg', 'Master&#8217;s Degree'),
(3493, 'en', 'usr_arr_phd', 'Ph.D.'),
(3494, 'en', 'usr_arr_post_doc', 'Postdoctoral'),
(3495, 'en', 'usr_arr_single', 'Single'),
(3496, 'en', 'usr_arr_married', 'Married'),
(3497, 'en', 'usr_arr_comitted', 'Comitted'),
(3498, 'en', 'usr_arr_open_marriage', 'Open Marriage'),
(3499, 'en', 'usr_arr_open_relate', 'Open Relationship'),
(3500, 'en', 'title_crt_new_msg', 'Compose New Message'),
(3501, 'en', 'title_forgot', 'Forgot Something? Find it now !'),
(3502, 'en', 'title_inbox', ' - Inbox'),
(3503, 'en', 'title_sent', ' - Sent Folder'),
(3504, 'en', 'title_usr_contact', '&#8217;s Contact List'),
(3505, 'en', 'title_usr_fav_vids', '%&#8217;s Favorite Videos'),
(3506, 'en', 'title_view_channel', '&#8217;s Channel'),
(3507, 'en', 'title_edit_video', 'Edit Video - '),
(3508, 'en', 'vdo_title_err', 'Please Enter Video Title'),
(3509, 'en', 'vdo_des_err', 'Please Enter Video Description'),
(3510, 'en', 'vdo_tags_err', 'Please Enter Tags For The Video'),
(3511, 'en', 'vdo_cat_err', 'Please Choose Atleast 1 Category'),
(3512, 'en', 'vdo_cat_err1', 'You Can Only Choose Up to 3 Categories'),
(3513, 'en', 'vdo_sub_email_msg', ' and therefore this message is sent to you automatically that '),
(3514, 'en', 'vdo_has_upload_nv', 'Has Uploaded New Video'),
(3515, 'en', 'vdo_del_selected', 'Selected Videos Have Been Deleted'),
(3516, 'en', 'vdo_cheat_msg', 'Please Don’t Try To Cheat'),
(3517, 'en', 'vdo_limits_warn_msg', 'Please Don’t Try To Cross Your Limits'),
(3518, 'en', 'vdo_cmt_del_msg', 'Comment Has Been Deleted'),
(3519, 'en', 'vdo_iac_msg', 'Video Is Inactive - Please Contact Admin For Details'),
(3520, 'en', 'vdo_is_in_process', 'Video Is Being Processed - Please Contact Administrator for further details'),
(3521, 'en', 'vdo_upload_allow_err', 'Uploading Is Not Allowed By Website Owner'),
(3522, 'en', 'vdo_download_allow_err', 'Video Downloading Is Not Allowed'),
(3523, 'en', 'vdo_edit_owner_err', 'You Are Not Video Owner'),
(3524, 'en', 'vdo_embed_code_wrong', 'Embed Code Was Wrong'),
(3525, 'en', 'vdo_seconds_err', 'Wrong Value Entered For Seconds Field'),
(3526, 'en', 'vdo_mins_err', 'Wrong Value Entered For Minutes Field'),
(3527, 'en', 'vdo_thumb_up_err', 'Error In Uploading Thumb'),
(3528, 'en', 'class_error_occured', 'Sorry, An Error Occured'),
(3529, 'en', 'class_cat_del_msg', 'Category has been deleted'),
(3530, 'en', 'class_vdo_del_msg', 'Video has been deleted'),
(3531, 'en', 'class_vdo_fr_msg', 'Video has been marked as &#8220;Featured Video&#8221;'),
(3532, 'en', 'class_fr_msg1', 'Video has been removed from &#8220;Featured Videos&#8221;'),
(3533, 'en', 'class_vdo_act_msg', 'Video has been activated'),
(3534, 'en', 'class_vdo_act_msg1', 'Vidoe has been deactivated'),
(3535, 'en', 'class_vdo_update_msg', 'Video details have been updated'),
(3536, 'en', 'class_comment_err', 'You Must Login Before Postings Comments'),
(3537, 'en', 'class_comment_err1', 'Please Type Something In The Comment Box'),
(3538, 'en', 'class_comment_err2', 'You Cannot Post a Comment on  Your Own Video'),
(3539, 'en', 'class_comment_err3', 'You Have Already Posted a Comment, Please Wait for the others.'),
(3540, 'en', 'class_comment_err4', 'You Have Already Replied To That a Comment, Please Wait for the others.'),
(3541, 'en', 'class_comment_err5', 'You Cannot Post a Reply To Yourself'),
(3542, 'en', 'class_comment_msg', 'Comment Has Been Added'),
(3543, 'en', 'class_comment_err6', 'Please login to rate comment'),
(3544, 'en', 'class_comment_err7', 'You have already rated this comment'),
(3545, 'en', 'class_vdo_fav_err', 'This Video is Already Added To Your Favorites'),
(3546, 'en', 'class_vdo_fav_msg', 'This Video Has Been Added To Your Favorites'),
(3547, 'en', 'class_vdo_flag_err', 'You Have Already Flagged This Video'),
(3548, 'en', 'class_vdo_flag_msg', 'This Video Has Been Flagged As Inappropriate'),
(3549, 'en', 'class_vdo_flag_rm', 'Flag(s) Has/Have Been Removed'),
(3550, 'en', 'class_send_msg_err', 'Please Enter a Username or Select any User to Send Message'),
(3551, 'en', 'class_invalid_user', 'Invalid Username'),
(3552, 'en', 'class_subj_err', 'Message subject was empty'),
(3553, 'en', 'class_msg_err', 'Please Type Something In Message Box'),
(3554, 'en', 'class_sent_you_msg', 'Sent You A Message'),
(3555, 'en', 'class_sent_prvt_msg', 'Sent You A Private Message on '),
(3556, 'en', 'class_click_inbox', 'Please Click here To View Your Inbox'),
(3557, 'en', 'class_click_login', 'Click Here To Login'),
(3558, 'en', 'class_email_notify', 'Email Notification'),
(3559, 'en', 'class_msg_has_sent_to', 'Message Has Been Sent To '),
(3560, 'en', 'class_inbox_del_msg', 'Message Has Been Delete From Inbox '),
(3561, 'en', 'class_sent_del_msg', 'Message Has Been Delete From Sent Folder'),
(3562, 'en', 'class_msg_exist_err', 'Message Doesn’t Exist'),
(3563, 'en', 'class_vdo_del_err', 'Video does not exist'),
(3564, 'en', 'class_unsub_msg', 'You have been unsubscribed sucessfully'),
(3565, 'en', 'class_sub_exist_err', 'Subscription Does Not Exist'),
(3566, 'en', 'class_vdo_rm_fav_msg', 'Video Has Been Removed From Favourites'),
(3567, 'en', 'class_vdo_fav_err1', 'This Video Is Not In Your Favourites List'),
(3568, 'en', 'class_cont_del_msg', 'Contact Has Been Deleted'),
(3569, 'en', 'class_cot_err', 'Sorry, This Contact Is Not In Your Contact List'),
(3570, 'en', 'class_vdo_ep_add_msg', 'Video Has Been Added To Editor&#8217;s Pick'),
(3571, 'en', 'class_vdo_ep_err', 'Video Is Already In The Editor&#8217;s Pick'),
(3572, 'en', 'class_vdo_ep_err1', 'You Have Already Picked 10 Videos Please Delete Alteast One to Add More'),
(3573, 'en', 'class_vdo_ep_msg', 'Video Has Been Removed From Editor&#8217;s Pick'),
(3574, 'en', 'class_vdo_exist_err', 'Sorry, Video Doesn’t Exist'),
(3575, 'en', 'class_img_gif_err', 'Please Upload Gif Image Only'),
(3576, 'en', 'class_img_png_err', 'Please Upload Png Image Only'),
(3577, 'en', 'class_img_jpg_err', 'Please Upload Jpg Image Only'),
(3578, 'en', 'class_logo_msg', 'Logo Has Been Changed. Please Clear Cache If You Are Not Able To See the Changed Logo'),
(3579, 'en', 'com_forgot_username', 'Forgot Username | Password'),
(3580, 'en', 'com_join_now', 'Join Now'),
(3581, 'en', 'com_my_account', 'My Account'),
(3582, 'en', 'com_manage_vids', 'Manage Videos'),
(3583, 'en', 'com_view_channel', 'View My Channel'),
(3584, 'en', 'com_my_inbox', 'My Inbox'),
(3585, 'en', 'com_welcome', 'Welcome'),
(3586, 'en', 'com_top_mem', 'Top Members '),
(3587, 'en', 'com_vidz', 'Videos'),
(3588, 'en', 'com_sign_up_now', 'Sign Up Now !'),
(3589, 'en', 'com_my_videos', 'My Videos'),
(3590, 'en', 'com_my_channel', 'My Channel'),
(3591, 'en', 'com_my_subs', 'My Subscriptions'),
(3592, 'en', 'com_user_no_contacts', 'User Does Not Have Any Contact'),
(3593, 'en', 'com_user_no_vides', 'User Does Not Have Any Favourite Video'),
(3594, 'en', 'com_user_no_vid_com', 'User Has No Video Comments'),
(3595, 'en', 'com_view_all_contacts', 'View All Contacts of'),
(3596, 'en', 'com_view_fav_all_videos', 'View All Favourite Videos Of'),
(3597, 'en', 'com_login_success_msg', 'You Have Been Successfully Logged In.'),
(3598, 'en', 'com_logout_success_msg', 'You Have Been Successfully Logged Out.'),
(3599, 'en', 'com_not_redirecting', 'You are now Redirecting .'),
(3600, 'en', 'com_not_redirecting_msg', 'if your are not redirecting'),
(3601, 'en', 'com_manage_contacts', 'Manage Contacts '),
(3602, 'en', 'com_send_message', 'Send Message'),
(3603, 'en', 'com_manage_fav', 'Manage Favorites '),
(3604, 'en', 'com_manage_subs', 'Manage Subscriptions'),
(3605, 'en', 'com_subscribe_to', 'Subscribe to %s&#8217;s channel'),
(3606, 'en', 'com_total_subs', 'Total Subscribtions'),
(3607, 'en', 'com_total_vids', 'Total Videos'),
(3608, 'en', 'com_date_subscribed', 'Date Subscribed'),
(3609, 'en', 'com_search_results', 'Search Results'),
(3610, 'en', 'com_advance_results', 'Advanced Search'),
(3611, 'en', 'com_search_results_in', 'Search Results In'),
(3612, 'en', 'videos_being_watched', 'Recently Viewed...'),
(3613, 'en', 'latest_added_videos', 'Recent Additions'),
(3614, 'en', 'most_viewed', 'Most Viewed'),
(3615, 'en', 'recently_added', 'Recently Added'),
(3616, 'en', 'featured', 'Featured'),
(3617, 'en', 'highest_rated', 'Highest Rated'),
(3618, 'en', 'most_discussed', 'Most Discussed'),
(3619, 'en', 'style_change', 'Style Change'),
(3620, 'en', 'rss_feed_latest_title', 'RSS Feed for Most Recent Videos'),
(3621, 'en', 'rss_feed_featured_title', 'RSS Feed for Featured Videos'),
(3622, 'en', 'rss_feed_most_viewed_title', 'RSS Feed for Most Popular Videos'),
(3623, 'en', 'lang_folder', 'en'),
(3624, 'en', 'reg_closed', 'Registration Closed'),
(3625, 'en', 'reg_for', 'Registration for'),
(3626, 'en', 'is_currently_closed', 'is currently closed'),
(3627, 'en', 'about_us', 'About Us'),
(3628, 'en', 'account', 'Account'),
(3629, 'en', 'added', 'Added'),
(3630, 'en', 'advertisements', 'Advertisements'),
(3631, 'en', 'all', 'All'),
(3632, 'en', 'active', 'Active'),
(3633, 'en', 'activate', 'Activate'),
(3634, 'en', 'age', 'Age'),
(3635, 'en', 'approve', 'Approve'),
(3636, 'en', 'approved', 'Approved'),
(3637, 'en', 'approval', 'Approval'),
(3638, 'en', 'books', 'Books'),
(3639, 'en', 'browse', 'Browse'),
(3640, 'en', 'by', 'by'),
(3641, 'en', 'cancel', 'Cancel'),
(3642, 'en', 'categories', 'Categories'),
(3643, 'en', 'category', 'Category'),
(3644, 'en', 'channels', 'channels'),
(3645, 'en', 'check_all', 'Check All'),
(3646, 'en', 'click_here', 'Click Here'),
(3647, 'en', 'comments', 'Comments'),
(3648, 'en', 'community', 'Community'),
(3649, 'en', 'companies', 'Companies'),
(3650, 'en', 'contacts', 'Contacts'),
(3651, 'en', 'contact_us', 'Contact Us'),
(3652, 'en', 'country', 'Country'),
(3653, 'en', 'created', 'Created'),
(3654, 'en', 'date', 'Date'),
(3655, 'en', 'date_added', 'Date Added'),
(3656, 'en', 'date_joined', 'Date Joined'),
(3657, 'en', 'dear', 'Dear'),
(3658, 'en', 'delete', 'Delete'),
(3659, 'en', 'delete_selected', 'Delete Selected'),
(3660, 'en', 'des_title', 'Description:'),
(3661, 'en', 'duration', 'Duration'),
(3662, 'en', 'education', 'Education'),
(3663, 'en', 'email', 'email'),
(3664, 'en', 'embed', 'Embed'),
(3665, 'en', 'embed_code', 'Embed Code'),
(3666, 'en', 'favourite', 'Favorite'),
(3667, 'en', 'favourited', 'Favorited'),
(3668, 'en', 'favourites', 'Favorites'),
(3669, 'en', 'female', 'Female'),
(3670, 'en', 'filter', 'Filter'),
(3671, 'en', 'forgot', 'Forgot'),
(3672, 'en', 'friends', 'Friends'),
(3673, 'en', 'from', 'From'),
(3674, 'en', 'gender', 'Gender'),
(3675, 'en', 'groups', 'Groups'),
(3676, 'en', 'hello', 'Hello'),
(3677, 'en', 'help', 'Help'),
(3678, 'en', 'hi', 'Hi'),
(3679, 'en', 'hobbies', 'Hobbies'),
(3680, 'en', 'Home', 'Home'),
(3681, 'en', 'inbox', 'Inbox'),
(3682, 'en', 'interests', 'Interests'),
(3683, 'en', 'join_now', 'Join Now'),
(3684, 'en', 'joined', 'Joined'),
(3685, 'en', 'join', 'Join'),
(3686, 'en', 'keywords', 'Keywords'),
(3687, 'en', 'latest', 'Latest'),
(3688, 'en', 'leave', 'Leave'),
(3689, 'en', 'location', 'Location'),
(3690, 'en', 'login', 'Login'),
(3691, 'en', 'logout', 'Logout'),
(3692, 'en', 'male', 'Male'),
(3693, 'en', 'members', 'Members'),
(3694, 'en', 'messages', 'Messages'),
(3695, 'en', 'message', 'Message'),
(3696, 'en', 'minutes', 'minutes'),
(3697, 'en', 'most_members', 'Most Members'),
(3698, 'en', 'most_recent', 'Most Recent'),
(3699, 'en', 'most_videos', 'Most Videos'),
(3700, 'en', 'music', 'Music'),
(3701, 'en', 'my_account', 'My Account'),
(3702, 'en', 'next', 'Next'),
(3703, 'en', 'no', 'No'),
(3704, 'en', 'no_user_exists', 'No User Exists'),
(3705, 'en', 'no_video_exists', 'No Video Exists'),
(3706, 'en', 'occupations', 'Occupations'),
(3707, 'en', 'optional', 'optional'),
(3708, 'en', 'owner', 'Owner'),
(3709, 'en', 'password', 'password'),
(3710, 'en', 'please', 'Please'),
(3711, 'en', 'privacy', 'Privacy'),
(3712, 'en', 'privacy_policy', 'Privacy Policy'),
(3713, 'en', 'random', 'Random'),
(3714, 'en', 'rate', 'Rate'),
(3715, 'en', 'request', 'Request'),
(3716, 'en', 'related', 'Related'),
(3717, 'en', 'reply', 'Reply'),
(3718, 'en', 'results', 'Results'),
(3719, 'en', 'relationship', 'Relationship'),
(3720, 'en', 'seconds', 'seconds'),
(3721, 'en', 'select', 'Select'),
(3722, 'en', 'send', 'Send'),
(3723, 'en', 'sent', 'Sent'),
(3724, 'en', 'signup', 'Signup'),
(3725, 'en', 'subject', 'Subject'),
(3726, 'en', 'tags', 'Tags'),
(3727, 'en', 'times', 'Times'),
(3728, 'en', 'to', 'To'),
(3729, 'en', 'type', 'Type'),
(3730, 'en', 'update', 'Update'),
(3731, 'en', 'upload', 'Upload'),
(3732, 'en', 'url', 'Url'),
(3733, 'en', 'verification', 'Verification'),
(3734, 'en', 'videos', 'Videos'),
(3735, 'en', 'viewing', 'Viewing'),
(3736, 'en', 'welcome', 'Welcome'),
(3737, 'en', 'website', 'Website'),
(3738, 'en', 'yes', 'Yes'),
(3739, 'en', 'of', 'of'),
(3740, 'en', 'on', 'on'),
(3741, 'en', 'previous', 'Previous'),
(3742, 'en', 'rating', 'Rating'),
(3743, 'en', 'ratings', 'Ratings'),
(3744, 'en', 'remote_upload', 'Remote Upload'),
(3745, 'en', 'remove', 'Remove'),
(3746, 'en', 'search', 'Search'),
(3747, 'en', 'services', 'Services'),
(3748, 'en', 'show_all', 'Show All'),
(3749, 'en', 'signupup', 'Sign Up'),
(3750, 'en', 'sort_by', 'Sort'),
(3751, 'en', 'subscriptions', 'Subscriptions'),
(3752, 'en', 'subscribers', 'Subscribers'),
(3753, 'en', 'tag_title', 'Tags'),
(3754, 'en', 'time', 'time'),
(3755, 'en', 'top', 'Top'),
(3756, 'en', 'tos_title', 'Terms of Use'),
(3757, 'en', 'username', 'Username'),
(3758, 'en', 'views', 'Views'),
(3759, 'en', 'proccession_wait', 'Processing, Please Wait'),
(3760, 'en', 'mostly_viewed', 'Most Viewed'),
(3761, 'en', 'most_comments', 'Most Comments'),
(3762, 'en', 'group', 'Group'),
(3763, 'en', 'not_logged_in', 'You are not logged in or you do not have permission to access this page. This could be due to one of several reasons:'),
(3764, 'en', 'fill_auth_form', 'You are not logged in. Fill in the form below and try again.'),
(3765, 'en', 'insufficient_privileges', 'You may not have sufficient privileges to access this page.'),
(3766, 'en', 'admin_disabled_you', 'The site administrator may have disabled your account, or it may be awaiting activation.'),
(3767, 'en', 'Recover_Password', 'Recover Password'),
(3768, 'en', 'Submit', 'Submit'),
(3769, 'en', 'Reset_Fields', 'Reset Fields'),
(3770, 'en', 'admin_reg_req', 'The administrator may have required you to register before you can view this page.'),
(3771, 'en', 'lang_change', 'Language Change'),
(3772, 'en', 'lang_changed', 'Your language has been changed'),
(3773, 'en', 'lang_choice', 'Language'),
(3774, 'en', 'if_not_redir', 'Click here to continue if you are not automatically redirected.'),
(3775, 'en', 'style_changed', 'Your style has been changed'),
(3776, 'en', 'style_choice', 'Style'),
(3777, 'en', 'vdo_edit_vdo', 'Edit Video'),
(3778, 'en', 'vdo_stills', 'Video Stills'),
(3779, 'en', 'vdo_watch_video', 'Watch Video'),
(3780, 'en', 'vdo_video_details', 'Video Details'),
(3781, 'en', 'vdo_title', 'Title'),
(3782, 'en', 'vdo_desc', 'Description'),
(3783, 'en', 'vdo_cat', 'Video Category'),
(3784, 'en', 'vdo_cat_msg', 'You May Select Up To %s Categories'),
(3785, 'en', 'vdo_tags_msg', 'Tags are separated by commas ie Arslan Hassan, Awsome, ClipBucket'),
(3786, 'en', 'vdo_br_opt', 'Broadcast Options'),
(3787, 'en', 'vdo_br_opt1', 'Public - Share your video with Everyone! (Recommended)'),
(3788, 'en', 'vdo_br_opt2', 'Private - Viewable by you and your friends only.'),
(3789, 'en', 'vdo_date_loc', 'Date And Location'),
(3790, 'en', 'vdo_date_rec', 'Date Recorded'),
(3791, 'en', 'vdo_for_date', 'format MM / DD / YYYY '),
(3792, 'en', 'vdo_add_eg', 'e.g London Greenland, Sialkot Mubarak Pura'),
(3793, 'en', 'vdo_share_opt', 'Sharing Options'),
(3794, 'en', 'vdo_allow_comm', 'Allow Comments '),
(3795, 'en', 'vdo_dallow_comm', 'Do Not Allow Comments'),
(3796, 'en', 'vdo_comm_vote', 'Comments Voting'),
(3797, 'en', 'vdo_allow_com_vote', 'Allow Voting on Comments'),
(3798, 'en', 'vdo_dallow_com_vote', 'Do Not Allow on Comments'),
(3799, 'en', 'vdo_allow_rating', 'Yes, Allow Rating on this video'),
(3800, 'en', 'vdo_dallow_ratig', 'No, Do Not Allow Rating on this video'),
(3801, 'en', 'vdo_embedding', 'Embedding'),
(3802, 'en', 'vdo_embed_opt1', 'Yes, People can play this video on other websites'),
(3803, 'en', 'vdo_embed_opt2', 'No, People cannot play this video on other websites'),
(3804, 'en', 'vdo_update_title', 'Update'),
(3805, 'en', 'vdo_inactive_msg', 'Your Account is Inactive. Please Activate it to Upload Videos, To Activate your account Please'),
(3806, 'en', 'vdo_click_here', 'Click Here'),
(3807, 'en', 'vdo_continue_upload', 'Continue to Upload'),
(3808, 'en', 'vdo_upload_step1', 'Video Upload'),
(3809, 'en', 'vdo_upload_step2', 'Video Step %s/2'),
(3810, 'en', 'vdo_upload_step3', '(Step 2/2)'),
(3811, 'en', 'vdo_select_vdo', 'Select a video to upload.'),
(3812, 'en', 'vdo_enter_remote_url', 'Enter Url Of The Video.'),
(3813, 'en', 'vdo_enter_embed_code_msg', 'Enter Embed Video Code from other websites ie Youtube or Metacafe.'),
(3814, 'en', 'vdo_enter_embed_code', 'Enter Embed Code'),
(3815, 'en', 'vdo_enter_druation', 'Enter Duration'),
(3816, 'en', 'vdo_select_vdo_thumb', 'Select Video Thumb'),
(3817, 'en', 'vdo_having_trouble', 'Having Trouble?'),
(3818, 'en', 'vdo_if_having_problem', 'if you are having problems with the uploader'),
(3819, 'en', 'vdo_clic_to_manage_all', 'Click Here To Manage All Videos'),
(3820, 'en', 'vdo_manage_vdeos', 'Manage Videos '),
(3821, 'en', 'vdo_status', 'Status'),
(3822, 'en', 'vdo_rawfile', 'RawFile'),
(3823, 'en', 'vdo_video_upload_complete', 'Video Upload - Upload Complete'),
(3824, 'en', 'vdo_thanks_you_upload_complete_1', 'Thank you! Your upload is complete'),
(3825, 'en', 'vdo_thanks_you_upload_complete_2', 'This video will be available in'),
(3826, 'en', 'vdo_after_it_has_process', 'after it has finished processing.'),
(3827, 'en', 'vdo_embed_this_video_on_web', 'Embed this video on your website.'),
(3828, 'en', 'vdo_copy_and_paste_the_code', 'Copy and paste the code below to embed this video.'),
(3829, 'en', 'vdo_upload_another_video', 'Upload Another Video'),
(3830, 'en', 'vdo_goto_my_videos', 'Goto My Videos'),
(3831, 'en', 'vdo_sperate_emails_by', 'seperate emails by commas'),
(3832, 'en', 'vdo_personal_msg', 'Personal Message'),
(3833, 'en', 'vdo_related_tags', 'Related Tags'),
(3834, 'en', 'vdo_reply_to_this', 'Reply To This '),
(3835, 'en', 'vdo_add_reply', 'Add Reply'),
(3836, 'en', 'vdo_share_video', 'Share Video'),
(3837, 'en', 'vdo_about_this_video', 'About This Video'),
(3838, 'en', 'vdo_post_to_a_services', 'Post to an Aggregating Service'),
(3839, 'en', 'vdo_commentary', 'Commentary'),
(3840, 'en', 'vdo_post_a_comment', 'Post A Comment'),
(3841, 'en', 'grp_add_vdo_msg', 'Add Videos To Group '),
(3842, 'en', 'grp_no_vdo_msg', 'You Don&#8217;t Have Any Video'),
(3843, 'en', 'grp_add_to', 'Add To Group'),
(3844, 'en', 'grp_add_vdos', 'Add Videos'),
(3845, 'en', 'grp_name_title', 'Group name'),
(3846, 'en', 'grp_tag_title', 'Tags:'),
(3847, 'en', 'grp_des_title', 'Description:'),
(3848, 'en', 'grp_tags_msg', 'Enter one or more tags, separated by spaces.'),
(3849, 'en', 'grp_tags_msg1', 'Enter one or more tags, separated by spaces. Tags  are keywords used to describe your group so it can be easily found by  other users. For example, if you have a group for surfers, you might  tag it: surfing, beach, waves.'),
(3850, 'en', 'grp_url_title', 'Choose a unique group name URL:'),
(3851, 'en', 'grp_url_msg', 'Enter 3-18 characters with no spaces (such as &#8220;skateboarding skates&#8221;), that will become part of your group&#8217;s web address. Please note, the group name URL you pick is permanent and can&#8217;t be changed.'),
(3852, 'en', 'grp_cat_tile', 'Group Category:'),
(3853, 'en', 'grp_vdo_uploads', 'Video Uploads:'),
(3854, 'en', 'grp_forum_posting', 'Forum Posting:'),
(3855, 'en', 'grp_join_opt1', 'Public, anyone can join.'),
(3856, 'en', 'grp_join_opt2', 'Protected, requires founder approval to join.'),
(3857, 'en', 'grp_join_opt3', 'Private, by founder invite only, only members can view group details.'),
(3858, 'en', 'grp_vdo_opt1', 'Post videos immediately.'),
(3859, 'en', 'grp_vdo_opt2', 'Founder approval required before video is available.'),
(3860, 'en', 'grp_vdo_opt3', 'Only Founder can add new videos.'),
(3861, 'en', 'grp_post_opt1', 'Post topics immediately.'),
(3862, 'en', 'grp_post_opt2', 'Founder approval required before topic is available.'),
(3863, 'en', 'grp_post_opt3', 'Only Founder can create a new topic.'),
(3864, 'en', 'grp_crt_grp', 'Create Group'),
(3865, 'en', 'grp_thumb_title', 'Group Thumb'),
(3866, 'en', 'grp_upl_thumb', 'Upload Group Thumb'),
(3867, 'en', 'grp_must_be', 'Must Be'),
(3868, 'en', 'grp_90x90', '90  x 90 Ratio Will Give Best Quality'),
(3869, 'en', 'grp_thumb_warn', 'Do Not Upload Vulgar or Copyrighted Material'),
(3870, 'en', 'grp_del_confirm', 'Are You Sure You Want To Delete This Group'),
(3871, 'en', 'grp_del_success', 'You Have Successfully Deleted'),
(3872, 'en', 'grp_click_go_grps', 'Click Here To Go To Groups'),
(3873, 'en', 'grp_edit_grp_title', 'Edit Group'),
(3874, 'en', 'grp_manage_vdos', 'Manage Videos'),
(3875, 'en', 'grp_manage_mems', 'Manage Members'),
(3876, 'en', 'grp_del_group_title', 'Delete Group'),
(3877, 'en', 'grp_add_vdos_title', 'Add Videos'),
(3878, 'en', 'grp_join_grp_title', 'Join Group'),
(3879, 'en', 'grp_leave_group_title', 'Leave Group'),
(3880, 'en', 'grp_invite_grp_title', 'Invite Members'),
(3881, 'en', 'grp_view_mems', 'View Members'),
(3882, 'en', 'grp_view_vdos', 'View Videos'),
(3883, 'en', 'grp_create_grp_title', 'Create A New Group'),
(3884, 'en', 'grp_most_members', 'Most Members'),
(3885, 'en', 'grp_most_discussed', 'Most Discussed'),
(3886, 'en', 'grp_invite_msg', 'Invite Users To This Group'),
(3887, 'en', 'grp_invite_msg1', 'Has Invited You To Join'),
(3888, 'en', 'grp_invite_msg2', 'Enter Emails or Usernames (seperate by commas)'),
(3889, 'en', 'grp_url_title1', 'Group url'),
(3890, 'en', 'grp_invite_msg3', 'Send Invitation'),
(3891, 'en', 'grp_join_confirm_msg', 'Are You Sure You Want To Join This Group'),
(3892, 'en', 'grp_join_msg_succ', 'You have successfully joined group'),
(3893, 'en', 'grp_click_here_to_go', 'Click Here To Go To'),
(3894, 'en', 'grp_leave_confirm', 'Are You Sure You Want To Leave This Group'),
(3895, 'en', 'grp_leave_succ_msg', 'You have left the group'),
(3896, 'en', 'grp_manage_members_title', 'Manage Members '),
(3897, 'en', 'grp_for_approval', 'For Approval'),
(3898, 'en', 'grp_rm_videos', 'Remove Videos'),
(3899, 'en', 'grp_rm_mems', 'Remove Members'),
(3900, 'en', 'grp_groups_title', 'Manage Groups'),
(3901, 'en', 'grp_remove_group', 'Remove Group'),
(3902, 'en', 'grp_bo_grp_found', 'No Group Found'),
(3903, 'en', 'grp_joined_groups', 'Joined Groups'),
(3904, 'en', 'grp_owned_groups', 'Owned Groups'),
(3905, 'en', 'grp_edit_this_grp', 'Edit This Group'),
(3906, 'en', 'grp_topics_title', 'Topics'),
(3907, 'en', 'grp_topic_title', 'Topic'),
(3908, 'en', 'grp_posts_title', 'Posts'),
(3909, 'en', 'grp_discus_title', 'Discussions'),
(3910, 'en', 'grp_author_title', 'Author'),
(3911, 'en', 'grp_replies_title', 'Replies'),
(3912, 'en', 'grp_last_post_title', 'Last Post '),
(3913, 'en', 'grp_viewl_all_videos', 'View All Videos of This Group'),
(3914, 'en', 'grp_add_new_topic', 'Add New Topic'),
(3915, 'en', 'grp_attach_video', 'Attach Video '),
(3916, 'en', 'grp_add_topic', 'Add Topic'),
(3917, 'en', 'grp_please_login', 'Please login to post topics'),
(3918, 'en', 'grp_please_join', 'Please Join This Group To Post Topics'),
(3919, 'en', 'grp_inactive_account', 'Your Account Is Inactive And Requires Activation From The Group Owner'),
(3920, 'en', 'grp_about_this_grp', 'About This Group '),
(3921, 'en', 'grp_no_vdo_err', 'This Group Has No Vidoes'),
(3922, 'en', 'grp_posted_by', 'Posted by'),
(3923, 'en', 'grp_add_new_comment', 'Add New Comment'),
(3924, 'en', 'grp_add_comment', 'Add Comment'),
(3925, 'en', 'grp_pls_login_comment', 'Please Login To Post Comments'),
(3926, 'en', 'grp_pls_join_comment', 'Please Join This Group To Post Comments'),
(3927, 'en', 'usr_activation_title', 'User Activation'),
(3928, 'en', 'usr_actiavation_msg', 'Enter Your Username and Activation Code that has been sent to your email.'),
(3929, 'en', 'usr_actiavation_msg1', 'Request Activation Code'),
(3930, 'en', 'usr_activation_code_tl', 'Activation Code'),
(3931, 'en', 'usr_compose_msg', 'Compose Message'),
(3932, 'en', 'usr_inbox_title', 'Inbox'),
(3933, 'en', 'usr_sent_title', 'Sent'),
(3934, 'en', 'usr_to_title', 'To: (Enter Username)'),
(3935, 'en', 'usr_or_select_frm_list', 'or select from contact list'),
(3936, 'en', 'usr_attach_video', 'Attach Video'),
(3937, 'en', 'user_attached_video', 'Attached Video'),
(3938, 'en', 'usr_send_message', 'Send Message'),
(3939, 'en', 'user_no_message', 'No Message'),
(3940, 'en', 'user_delete_message_msg', 'Delete This Message'),
(3941, 'en', 'user_forgot_message', 'Forgot password'),
(3942, 'en', 'user_forgot_message_2', 'Dont Worry, recover it now'),
(3943, 'en', 'user_pass_reset_msg', 'Password Reset'),
(3944, 'en', 'user_pass_forgot_msg', 'if you have forgot your password, please enter you username and verification code in the box, and password reset instructions will be sent to your mail box.'),
(3945, 'en', 'user_veri_code', 'Verification Code'),
(3946, 'en', 'user_reocover_user', 'Recover Username'),
(3947, 'en', 'user_user_forgot_msg', 'Forgot Username?'),
(3948, 'en', 'user_recover', 'Recover'),
(3949, 'en', 'user_reset', 'Reset'),
(3950, 'en', 'user_inactive_msg', 'Your Account is Inactive. Please Activate it , To Activate your account Please'),
(3951, 'en', 'user_dashboard', 'Dash Board'),
(3952, 'en', 'user_manage_prof_chnnl', 'Manage Profile &amp; Channel'),
(3953, 'en', 'user_manage_friends', 'Manage Friends &amp; Contacts'),
(3954, 'en', 'user_prof_channel', 'Profile/Channel'),
(3955, 'en', 'user_message_box', 'Message Box'),
(3956, 'en', 'user_new_messages', 'New Messages'),
(3957, 'en', 'user_goto_inbox', 'Go to Inbox'),
(3958, 'en', 'user_goto_sentbox', 'Go to Sent Box'),
(3959, 'en', 'user_compose_new', 'Compose New Messages'),
(3960, 'en', 'user_total_subs_users', 'Total Subscribed Users'),
(3961, 'en', 'user_you_have', 'You Have'),
(3962, 'en', 'user_fav_videos', 'Favorite Videos'),
(3963, 'en', 'user_your_vids_watched', 'Your Videos Watched'),
(3964, 'en', 'user_times', 'Times'),
(3965, 'en', 'user_you_have_watched', 'You Have Watched'),
(3966, 'en', 'user_channel_profiles', 'Channel &amp; Profile'),
(3967, 'en', 'user_channel_views', 'Channel Views'),
(3968, 'en', 'user_channel_comm', 'Channel Comments '),
(3969, 'en', 'user_manage_prof', 'Manage Profile / Channel'),
(3970, 'en', 'user_you_created', 'You Have Created'),
(3971, 'en', 'user_you_joined', 'You Have Joined'),
(3972, 'en', 'user_create_group', 'Create New Group'),
(3973, 'en', 'user_manage_my_account', 'Manage My Account '),
(3974, 'en', 'user_manage_my_videos', 'Manage My Videos'),
(3975, 'en', 'user_manage_my_channel', 'Manage My Channel'),
(3976, 'en', 'user_sent_box', 'My sent items'),
(3977, 'en', 'user_manage_channel', 'Manage Channel'),
(3978, 'en', 'user_manage_my_contacts', 'Manage My Contacts'),
(3979, 'en', 'user_manage_contacts', 'Manage Contacts'),
(3980, 'en', 'user_manage_favourites', 'Manage Favourite Videos'),
(3981, 'en', 'user_mem_login', 'Members Login'),
(3982, 'en', 'user_already_have', 'Please Login Here if You Already have an account of'),
(3983, 'en', 'user_forgot_username', 'Forgot Username'),
(3984, 'en', 'user_forgot_password', 'Forgot Password'),
(3985, 'en', 'user_create_your', 'Create Your '),
(3986, 'en', 'user_all_fields_req', 'All Fields Are Required'),
(3987, 'en', 'user_valid_email_addr', 'Valid Email Address'),
(3988, 'en', 'user_allowed_format', 'Letters A-Z or a-z , Numbers 0-9 and Underscores _'),
(3989, 'en', 'user_confirm_pass', 'Confirm Password'),
(3990, 'en', 'user_reg_msg_0', 'Register as '),
(3991, 'en', 'user_reg_msg_1', 'member, its free and easy just fill out the form below'),
(3992, 'en', 'user_date_of_birth', 'Date Of Birth'),
(3993, 'en', 'user_enter_text_as_img', 'Enter Text As Seen In The Image'),
(3994, 'en', 'user_refresh_img', 'Refresh Image'),
(3995, 'en', 'user_i_agree_to_the', 'I Agree to  <a href="%s" target="_blank">Terms of Service</a> and <a href="%s" target="_blank" >Privacy Policy'),
(3996, 'en', 'user_thanks_for_reg', 'Thank You For Registering on '),
(3997, 'en', 'user_email_has_sent', 'An email has been sent to your inbox containing Your Account'),
(3998, 'en', 'user_and_activation', '&amp; Activation'),
(3999, 'en', 'user_details_you_now', 'Details. You may now do the following things on our network'),
(4000, 'en', 'user_upload_share_vds', 'Upload, Share Videos'),
(4001, 'en', 'user_make_friends', 'Make Friends'),
(4002, 'en', 'user_send_messages', 'Send Messages'),
(4003, 'en', 'user_grow_your_network', 'Grow Your Networks by Inviting more Friends'),
(4004, 'en', 'user_rate_comment', 'Rate and Comment Videos'),
(4005, 'en', 'user_make_customize', 'Make and Customize Your Channel'),
(4006, 'en', 'user_to_upload_vid', 'To Upload Video, You Need to Activate your account first, activation details has been sent to your email account, it may take sometimes to reach your inbox'),
(4007, 'en', 'user_click_to_login', 'Click here To Login To Your Account'),
(4008, 'en', 'user_view_my_channel', 'View My Channel'),
(4009, 'en', 'user_change_pass', 'Change Password'),
(4010, 'en', 'user_email_settings', 'Email Settings'),
(4011, 'en', 'user_profile_settings', 'Profile Settings'),
(4012, 'en', 'user_usr_prof_chnl_edit', 'User Profile &amp; Channel Edit'),
(4013, 'en', 'user_personal_info', 'Personal Information'),
(4014, 'en', 'user_fname', 'First Name'),
(4015, 'en', 'user_lname', 'Last Name'),
(4016, 'en', 'user_gender', 'Gender'),
(4017, 'en', 'user_relat_status', 'Relationship Status'),
(4018, 'en', 'user_display_age', 'Display Age'),
(4019, 'en', 'user_about_me', 'About Me'),
(4020, 'en', 'user_website_url', 'Website Url'),
(4021, 'en', 'user_eg_website', 'e.g www.cafepixie.com'),
(4022, 'en', 'user_prof_info', 'Professional Information'),
(4023, 'en', 'user_education', 'Education'),
(4024, 'en', 'user_school_colleges', 'Schools / Colleges'),
(4025, 'en', 'user_occupations', 'Occupation(s)'),
(4026, 'en', 'user_companies', 'Companies'),
(4027, 'en', 'user_sperate_by_commas', 'seperate with commas'),
(4028, 'en', 'user_interests_hobbies', 'Interests and Hobbies'),
(4029, 'en', 'user_fav_movs_shows', 'Favorite Movies &amp; Shows'),
(4030, 'en', 'user_fav_music', 'Favorite Music'),
(4031, 'en', 'user_fav_books', 'Favorite Books'),
(4032, 'en', 'user_user_avatar', 'User Avatar'),
(4033, 'en', 'user_upload_avatar', 'Upload Avatar'),
(4034, 'en', 'user_channel_info', 'Channel Info'),
(4035, 'en', 'user_channel_title', 'Channel Title'),
(4036, 'en', 'user_channel_description', 'Channel Description'),
(4037, 'en', 'user_channel_permission', 'Channel Permissions'),
(4038, 'en', 'user_allow_comments_msg', 'users can comment'),
(4039, 'en', 'user_dallow_comments_msg', 'users cannot comment'),
(4040, 'en', 'user_allow_rating', 'Allow Rating'),
(4041, 'en', 'user_dallow_rating', 'Do Not Allow Rating'),
(4042, 'en', 'user_allow_rating_msg1', 'users can rate'),
(4043, 'en', 'user_dallow_rating_msg1', 'users cannot rate'),
(4044, 'en', 'user_channel_feature_vid', 'Channel Featured Video'),
(4045, 'en', 'user_select_vid_for_fr', 'Select Video To set as Featured'),
(4046, 'en', 'user_chane_channel_bg', 'Change Channel Background'),
(4047, 'en', 'user_remove_bg', 'Remove Background'),
(4048, 'en', 'user_currently_you_d_have_pic', 'Currently You Don&#8217;t Have a Background Picture'),
(4049, 'en', 'user_change_email', 'Change Email'),
(4050, 'en', 'user_email_address', 'Email Address'),
(4051, 'en', 'user_new_email', 'New Email'),
(4052, 'en', 'user_notify_me', 'Notify Me When User Sends Me A Message'),
(4053, 'en', 'user_old_pass', 'Old Password'),
(4054, 'en', 'user_new_pass', 'New Password'),
(4055, 'en', 'user_c_new_pass', 'Confirm New Password'),
(4056, 'en', 'user_doesnt_exist', 'User Doesn&#8217;t Exist'),
(4057, 'en', 'user_do_not_have_contact', 'User Does Not Have Any Contacts'),
(4058, 'en', 'user_no_fav_video_exist', 'User does not have any Favorite Videos selected'),
(4059, 'en', 'user_have_no_vide', 'User doesn’t have any videos'),
(4060, 'en', 'user_s_channel', '%s&#8217;s Channel '),
(4061, 'en', 'user_last_login', 'Last Login'),
(4062, 'en', 'user_send_message', 'Send Message'),
(4063, 'en', 'user_add_contact', 'Add Contact'),
(4064, 'en', 'user_dob', 'DoB'),
(4065, 'en', 'user_movies_shows', 'Movies &amp; Shows'),
(4066, 'en', 'user_add_comment', 'Add Comment '),
(4067, 'en', 'user_view_all_comments', 'View All Comments'),
(4068, 'en', 'user_no_fr_video', 'User Has Not Selected Any Video To Set As Featured'),
(4069, 'en', 'user_view_all_video_of', 'View All Videos of '),
(4070, 'en', 'menu_home', 'Home'),
(4071, 'en', 'menu_videos', 'Videos'),
(4072, 'en', 'menu_upload', 'Upload'),
(4073, 'en', 'menu_signup', 'SignUp'),
(4074, 'en', 'menu_account', 'Account'),
(4075, 'en', 'menu_groups', 'Groups'),
(4076, 'en', 'menu_channels', 'Channels'),
(4077, 'en', 'menu_community', 'Community'),
(4078, 'en', 'menu_inbox', 'Inbox'),
(4079, 'en', 'vdo_cat_err2', 'You cannot select more than %d categories'),
(4080, 'en', 'user_subscribe_message', 'Hello %subscriber%\nYou Have Subscribed To %user% and therefore this message is sent to you automatically, because %user% Has Uploaded a New Video\n\n%website_title%'),
(4081, 'en', 'user_subscribe_subject', '%user% has uploaded a new video'),
(4082, 'en', 'you_already_logged', 'You are already logged in'),
(4083, 'en', 'you_not_logged_in', 'You are not logged in'),
(4084, 'en', 'invalid_user', 'Invalid User'),
(4085, 'en', 'vdo_cat_err3', 'Please select at least 1 category'),
(4086, 'en', 'embed_code_invalid_err', 'Invalid video embed code'),
(4087, 'en', 'invalid_duration', 'Invalid duration'),
(4088, 'en', 'vid_thumb_changed', 'Video default thumb has been changed'),
(4089, 'en', 'vid_thumb_change_err', 'Video thumbnail was not found'),
(4090, 'en', 'upload_vid_thumbs_msg', 'All video thumbs have been uploaded'),
(4091, 'en', 'video_thumb_delete_msg', 'Video thumb has been deleted'),
(4092, 'en', 'video_thumb_delete_err', 'Could not delete video thumb'),
(4093, 'en', 'no_comment_del_perm', 'You dont have permission to delete this comment'),
(4094, 'en', 'my_text_context', 'My test context'),
(4095, 'en', 'user_contains_disallow_err', 'Username contains disallowed characters'),
(4096, 'en', 'add_cat_erro', 'Category already exists'),
(4097, 'en', 'add_cat_no_name_err', 'Please enter a name for the category'),
(4098, 'en', 'cat_default_err', 'Default cannot be deleted, please choose another category as &#8220;default&#8221; and then delete this one'),
(4099, 'en', 'pic_upload_vali_err', 'Please upload valid JPG, GIF or PNG image'),
(4100, 'en', 'cat_dir_make_err', 'Unable to create the category thumb directory'),
(4101, 'en', 'cat_set_default_ok', 'Category has been set as default'),
(4102, 'en', 'vid_thumb_removed_msg', 'Video thumbs have been removed'),
(4103, 'en', 'vid_files_removed_msg', 'Video files have been removed'),
(4104, 'en', 'vid_log_delete_msg', 'Video log has been deleted'),
(4105, 'en', 'vdo_multi_del_erro', 'Videos has have been deleted'),
(4106, 'en', 'add_fav_message', 'This %s has been added to your favorites'),
(4107, 'en', 'obj_not_exists', '%s does not exist'),
(4108, 'en', 'already_fav_message', 'This %s is already added to your favorites'),
(4109, 'en', 'obj_report_msg', 'this %s has been reported'),
(4110, 'en', 'obj_report_err', 'You have already reported this %s'),
(4111, 'en', 'user_no_exist_wid_username', '&#8216;%s&#8217; does not exist'),
(4112, 'en', 'share_video_no_user_err', 'Please enter usernames or emails to send this %s'),
(4113, 'en', 'uploaded', 'Uploaded'),
(4114, 'en', 'today', 'Today'),
(4115, 'en', 'yesterday', 'Yesterday'),
(4116, 'en', 'thisweek', 'This Week'),
(4117, 'en', 'lastweek', 'Last Week'),
(4118, 'en', 'thismonth', 'This Month'),
(4119, 'en', 'lastmonth', 'Last Month'),
(4120, 'en', 'thisyear', 'This Year'),
(4121, 'en', 'lastyear', 'Last Year'),
(4122, 'en', 'favorites', 'Favorites'),
(4123, 'en', 'alltime', 'All Time'),
(4124, 'en', 'insufficient_privileges_loggin', 'You cannot access this page Click Here to Login or Register'),
(4125, 'en', 'profile_title', 'Profile Title'),
(4126, 'en', 'show_dob', 'Show Date of Birth'),
(4127, 'en', 'profile_tags', 'Profile Tags'),
(4128, 'en', 'profile_desc', 'Profile Description'),
(4129, 'en', 'online_status', 'User Status'),
(4130, 'en', 'show_profile', 'Show Profile'),
(4131, 'en', 'allow_ratings', 'Allow Profile Ratings'),
(4132, 'en', 'postal_code', 'Postal Code'),
(4133, 'en', 'temp_file_load_err', 'Unable to load tempalte file &#8216;%s&#8217; in directory &#8216;%s&#8217;'),
(4134, 'en', 'no_date_provided', 'No date provided'),
(4135, 'en', 'second', 'second'),
(4136, 'en', 'minute', 'minute'),
(4137, 'en', 'bad_date', 'Never'),
(4138, 'en', 'users_videos', '%s&#8217;s Videos'),
(4139, 'en', 'please_login_subscribe', 'Please login to Subsribe %s'),
(4140, 'en', 'users_subscribers', '%s&#8217;s Subscribers'),
(4141, 'en', 'user_no_subscribers', '%s has no subsribers'),
(4142, 'en', 'user_subscriptions', '%s&#8217;s Subscriptions'),
(4143, 'en', 'user_no_subscriptions', '%s has no subscriptions'),
(4144, 'en', 'usr_avatar_bg_update', 'User avatar and background have been updated'),
(4145, 'en', 'user_email_confirm_email_err', 'Confirm email mismatched'),
(4146, 'en', 'email_change_msg', 'Email has been changed successfully'),
(4147, 'en', 'no_edit_video', 'You cannot edit this video'),
(4148, 'en', 'confirm_del_video', 'Are you sure you want to delete this video ?'),
(4149, 'en', 'remove_fav_video_confirm', 'Are you sure you want to remove this video from your favorites ?'),
(4150, 'en', 'fav_remove_msg', '%s has been removed from your favorites'),
(4151, 'en', 'unknown_favorite', 'Unknown favorite %s'),
(4152, 'en', 'vdo_multi_del_fav_msg', 'Videos have been removed from your favorites'),
(4153, 'en', 'unknown_sender', 'Unknown Sender'),
(4154, 'en', 'please_enter_message', 'Please enter something for message'),
(4155, 'en', 'unknown_reciever', 'Unknown reciever'),
(4156, 'en', 'no_pm_exist', 'Private message does not exist'),
(4157, 'en', 'pm_sent_success', 'Private message has been sent successfully'),
(4158, 'en', 'msg_delete_inbox', 'Message has been deleted from inbox'),
(4159, 'en', 'msg_delete_outbox', 'Message has been deleted from your outbox'),
(4160, 'en', 'private_messags_deleted', 'Private messages have been deleted'),
(4161, 'en', 'ban_users', 'Ban Users'),
(4162, 'en', 'spe_users_by_comma', 'separate usernames by comma'),
(4163, 'en', 'user_ban_msg', 'Users have been banned successfully'),
(4164, 'en', 'no_user_ban_msg', 'No user is banned from your account!'),
(4165, 'en', 'thnx_sharing_msg', 'Thanks for sharing this %s'),
(4166, 'en', 'no_own_commen_rate', 'You cannot rate your own comment'),
(4167, 'en', 'no_comment_exists', 'Comment does not exist'),
(4168, 'en', 'thanks_rating_comment', 'Thanks for rating comment'),
(4169, 'en', 'please_login_create_playlist', 'Please login to creat playlists'),
(4170, 'en', 'play_list_with_this_name_arlready_exists', 'Playlist with name &#8216;%s&#8217; already exists'),
(4171, 'en', 'please_enter_playlist_name', 'Please enter playlist name'),
(4172, 'en', 'new_playlist_created', 'New playlist has been created'),
(4173, 'en', 'playlist_not_exist', 'Playlist does not exist'),
(4174, 'en', 'playlist_item_not_exist', 'Playlist item does not exist'),
(4175, 'en', 'playlist_item_delete', 'Playlist item has been deleted'),
(4176, 'en', 'play_list_updated', 'Playlist has been updated'),
(4177, 'en', 'you_dont_hv_permission_del_playlist', 'You do not have permission to delete the playlist'),
(4178, 'en', 'playlist_delete_msg', 'Playlist has been deleted'),
(4179, 'en', 'playlist_name', 'Playlist Name'),
(4180, 'en', 'add_new_playlist', 'Add Playlist'),
(4181, 'en', 'this_thing_added_playlist', 'This %s has been added to playlist'),
(4182, 'en', 'this_already_exist_in_pl', 'This %s already exists in your playlist'),
(4183, 'en', 'edit_playlist', 'Edit Playlist'),
(4184, 'en', 'remove_playlist_item_confirm', 'Are you sure you want to remove this from your playlist'),
(4185, 'en', 'remove_playlist_confirm', 'Are you sure you want to delete this playlist?'),
(4186, 'en', 'avcode_incorrect', 'Activation code is incorrect'),
(4187, 'en', 'group_join_login_err', 'Please login in order to join this group'),
(4188, 'en', 'manage_playlist', 'Manage playlist'),
(4189, 'en', 'my_notifications', 'My notifications');
INSERT INTO `cb_phrases` (`id`, `lang_iso`, `varname`, `text`) VALUES
(4190, 'en', 'users_contacts', '%s&#8217;s contacts'),
(4191, 'en', 'type_flags_removed', '%s flags have been removed'),
(4192, 'en', 'terms_of_serivce', 'Terms of services'),
(4193, 'en', 'users', 'Users'),
(4194, 'en', 'login_to_mark_as_spam', 'Please login to mark as spam'),
(4195, 'en', 'no_own_commen_spam', 'You cannot mark your own comment as spam'),
(4196, 'en', 'already_spammed_comment', 'You have already marked this comment as spam'),
(4197, 'en', 'spam_comment_ok', 'Comment has been marked as spam'),
(4198, 'en', 'arslan_hassan', 'Arslan Hassan'),
(4199, 'en', 'you_not_allowed_add_grp_vids', 'You are not member of this group so cannot add videos'),
(4200, 'en', 'sel_vids_updated', 'Selected videos have been updated'),
(4201, 'en', 'unable_find_download_file', 'Unable to find download file'),
(4202, 'en', 'you_cant_edit_group', 'You cannot edit this group'),
(4203, 'en', 'you_cant_invite_mems', 'You cannot invite members'),
(4204, 'en', 'you_cant_moderate_group', 'You cannot moderate this group'),
(4205, 'en', 'page_doesnt_exist', 'Page does not exist'),
(4206, 'en', 'pelase_select_img_file_for_vdo', 'Please select image file for video thumb'),
(4207, 'en', 'new_mem_added', 'New member has been added'),
(4208, 'en', 'this_vdo_not_working', 'This video might not work properly'),
(4209, 'en', 'email_template_not_exist', 'Email template does not exist'),
(4210, 'en', 'email_subj_empty', 'Email subject was empty'),
(4211, 'en', 'email_msg_empty', 'Email message was empty'),
(4212, 'en', 'email_tpl_has_updated', 'Email Template has been updated'),
(4213, 'en', 'page_name_empty', 'Page name was empty'),
(4214, 'en', 'page_title_empty', 'Page title was empty'),
(4215, 'en', 'page_content_empty', 'Page content was empty'),
(4216, 'en', 'new_page_added_successfully', 'New page has been added successfully'),
(4217, 'en', 'page_updated', 'Page has been updated'),
(4218, 'en', 'page_deleted', 'Page has been deleted successfully'),
(4219, 'en', 'page_activated', 'Page has been activated'),
(4220, 'en', 'page_deactivated', 'Page has been deactivated'),
(4221, 'en', 'you_cant_delete_this_page', 'You cannot delete this page'),
(4222, 'en', 'ad_placement_err4', 'Placement does not exist'),
(4223, 'en', 'grp_details_updated', 'Group details have been updated'),
(4224, 'en', 'you_cant_del_topic', 'You cannot delete this topic'),
(4225, 'en', 'you_cant_del_user_topics', 'You cannot delete user topics'),
(4226, 'en', 'topics_deleted', 'Topics have been deleted'),
(4227, 'en', 'you_cant_delete_grp_topics', 'You cannot delete group topics'),
(4228, 'en', 'you_not_allowed_post_topics', 'You are not allowed to post topics'),
(4229, 'en', 'you_cant_add_this_vdo', 'You cannot add this video'),
(4230, 'en', 'video_added', 'Video has been added'),
(4231, 'en', 'you_cant_del_this_vdo', 'You cannot remove this video'),
(4232, 'en', 'video_removed', 'Video has been removed'),
(4233, 'en', 'user_not_grp_mem', 'User is not group member'),
(4234, 'en', 'user_already_group_mem', 'User has already joined this group'),
(4235, 'en', 'invitations_sent', 'Invitations have been sent'),
(4236, 'en', 'you_not_grp_mem', 'You are not a member of this group'),
(4237, 'en', 'you_cant_delete_this_grp', 'You cannot delete this group'),
(4238, 'en', 'grp_deleted', 'Group has been deleted'),
(4239, 'en', 'you_cant_del_grp_mems', 'You cannot delete group members'),
(4240, 'en', 'mems_deleted', 'Members have been deleted'),
(4241, 'en', 'you_cant_del_grp_vdos', 'You cannot delete group videos'),
(4242, 'en', 'thnx_for_voting', 'Thanks for voting'),
(4243, 'en', 'you_hv_already_rated_vdo', 'You have already rated this video'),
(4244, 'en', 'please_login_to_rate', 'Please login to rate'),
(4245, 'en', 'you_not_subscribed', 'You are not subscribed'),
(4246, 'en', 'you_cant_delete_this_user', 'You cannot delete this user&#8221;'),
(4247, 'en', 'you_dont_hv_perms', 'You don’t have sufficient permissions'),
(4248, 'en', 'user_subs_hv_been_removed', 'User subscriptions have been removed'),
(4249, 'en', 'user_subsers_hv_removed', 'User subscribers have been removed'),
(4250, 'en', 'you_already_sent_frend_request', 'You have already sent friend request'),
(4251, 'en', 'friend_added', 'Friend has been added'),
(4252, 'en', 'friend_request_sent', 'Friend request has been sent'),
(4253, 'en', 'friend_confirm_error', 'Either the user has not requested your friend request or you have already confirmed it'),
(4254, 'en', 'friend_confirmed', 'Friend has been confirmed'),
(4255, 'en', 'friend_request_not_found', 'No friend request found'),
(4256, 'en', 'you_cant_confirm_this_request', 'You cannot confirm this request'),
(4257, 'en', 'friend_request_already_confirmed', 'Friend request is already confirmed'),
(4258, 'en', 'user_no_in_contact_list', 'User is not in your contact list'),
(4259, 'en', 'user_removed_from_contact_list', 'User has been removed from your contact list'),
(4260, 'en', 'cant_find_level', 'Cannot find level'),
(4261, 'en', 'please_enter_level_name', 'Please enter level name'),
(4262, 'en', 'level_updated', 'Level has been updated'),
(4263, 'en', 'level_del_sucess', 'User level has been deleted, all users of this level has been transfered to %s'),
(4264, 'en', 'level_not_deleteable', 'This level is not deletable'),
(4265, 'en', 'pass_mismatched', 'Passwords Mismatched'),
(4266, 'en', 'user_blocked', 'User has been blocked'),
(4267, 'en', 'user_already_blocked', 'User is already blocked'),
(4268, 'en', 'you_cant_del_user', 'You cannot block this user'),
(4269, 'en', 'user_vids_hv_deleted', 'User videos have been deleted'),
(4270, 'en', 'user_contacts_hv_removed', 'User contacts have been removed'),
(4271, 'en', 'all_user_inbox_deleted', 'All User inbox messages have been deleted'),
(4272, 'en', 'all_user_sent_messages_deleted', 'All user sent messages have been deleted'),
(4273, 'en', 'pelase_enter_something_for_comment', 'Please enter something as comment'),
(4274, 'en', 'please_enter_your_name', 'Please enter your name'),
(4275, 'en', 'please_enter_your_email', 'Please enter your email'),
(4276, 'en', 'template_activated', 'Template has been activated'),
(4277, 'en', 'error_occured_changing_template', 'An error occured while changing the template'),
(4278, 'en', 'phrase_code_empty', 'Phrase code was empty'),
(4279, 'en', 'phrase_text_empty', 'Phrase text was empty'),
(4280, 'en', 'language_does_not_exist', 'Language does not exist'),
(4281, 'en', 'name_has_been_added', '%s has been added'),
(4282, 'en', 'name_already_exists', '&#8216;%s&#8217; already exist'),
(4283, 'en', 'lang_doesnt_exist', 'language does not exist'),
(4284, 'en', 'no_file_was_selected', 'No file was selected'),
(4285, 'en', 'err_reading_file_content', 'Error reading file content'),
(4286, 'en', 'cant_find_lang_name', 'Cant find language name'),
(4287, 'en', 'cant_find_lang_code', 'Cant find language code'),
(4288, 'en', 'no_phrases_found', 'No phrases were found'),
(4289, 'en', 'language_already_exists', 'Language already exists'),
(4290, 'en', 'lang_added', 'Language has been added successfully'),
(4291, 'en', 'error_while_upload_file', 'Error occured while uploading language file'),
(4292, 'en', 'default_lang_del_error', 'This is the default language, please select another language as &#8220;default&#8221; and then delete this pack'),
(4293, 'en', 'lang_deleted', 'Language pack has been deleted'),
(4294, 'en', 'lang_name_empty', 'Language name was empty'),
(4295, 'en', 'lang_code_empty', 'Language code was empty'),
(4296, 'en', 'lang_regex_empty', 'Language regular expression was empty'),
(4297, 'en', 'lang_code_already_exist', 'Language code already exists'),
(4298, 'en', 'lang_updated', 'Language has been updated'),
(4299, 'en', 'player_activated', 'Player has been activated'),
(4300, 'en', 'error_occured_while_activating_player', 'An error occured while activating player'),
(4301, 'en', 'plugin_has_been_s', 'Plugin has been %s'),
(4302, 'en', 'plugin_uninstalled', 'Plugin has been Uninstalled'),
(4303, 'en', 'perm_code_empty', 'Permission code is empty'),
(4304, 'en', 'perm_name_empty', 'Permission name is empty'),
(4305, 'en', 'perm_already_exist', 'Permission already exists'),
(4306, 'en', 'perm_type_not_valid', 'Permission type is not valid'),
(4307, 'en', 'perm_added', 'New Permission has been added'),
(4308, 'en', 'perm_deleted', 'Permission has been deleted'),
(4309, 'en', 'perm_doesnt_exist', 'Permission does not exist'),
(4310, 'en', 'acitvation_html_message', 'Please enter your username and activation code in order to activate your account, please check your inbox for the Activation code, if you didn’t get one, please request it by filling the next form'),
(4311, 'en', 'acitvation_html_message2', 'Please enter your email address to request your activation code'),
(4312, 'en', 'admin_panel', 'Admin Panel'),
(4313, 'en', 'moderate_videos', 'Moderate Videos'),
(4314, 'en', 'moderate_users', 'Moderate Users'),
(4315, 'en', 'revert_back_to_admin', 'Revert back to admin'),
(4316, 'en', 'more_options', 'More Options'),
(4317, 'en', 'downloading_string', 'Downloading %s ...'),
(4318, 'en', 'download_redirect_msg', '<a href="%s">click here if you don''t redirect automatically</a> - <a href="%s"> Click Here to Go Back to Video Page</a>'),
(4319, 'en', 'account_details', 'Account Details'),
(4320, 'en', 'profile_details', 'Profile Details'),
(4321, 'en', 'update_profile', 'Update Profile'),
(4322, 'en', 'please_select_img_file', 'Please select image file'),
(4323, 'en', 'or', 'or'),
(4324, 'en', 'pelase_enter_image_url', 'Please Enter Image URL'),
(4325, 'en', 'user_bg', 'Channel Background'),
(4326, 'en', 'user_bg_img', 'Channel Background Image'),
(4327, 'en', 'please_enter_bg_color', 'Please Enter Background Color'),
(4328, 'en', 'bg_repeat_type', 'Background Repeat Type (if using image as a background)'),
(4329, 'en', 'fix_bg', 'Fix Background'),
(4330, 'en', 'delete_this_img', 'Delete this image'),
(4331, 'en', 'current_email', 'Current Email'),
(4332, 'en', 'confirm_new_email', 'Confirm New Email'),
(4333, 'en', 'no_subs_found', 'No subscription found'),
(4334, 'en', 'video_info_all_fields_req', 'Video Information - All fields are required'),
(4335, 'en', 'update_group', 'Update Group'),
(4336, 'en', 'default', 'Default'),
(4337, 'en', 'grp_info_all_fields_req', 'Group Information - All Fields Are Required'),
(4338, 'en', 'date_recorded_location', 'Date recorded &amp; Location'),
(4339, 'en', 'update_video', 'Update Video'),
(4340, 'en', 'click_here_to_recover_user', 'Click here to recover username'),
(4341, 'en', 'click_here_reset_pass', 'Click here to reset password'),
(4342, 'en', 'remember_me', 'Remember Me'),
(4343, 'en', 'howdy_user', 'Howdy %s'),
(4344, 'en', 'notifications', 'Notifications'),
(4345, 'en', 'playlists', 'Playlists'),
(4346, 'en', 'friend_requests', 'Friend Requests'),
(4347, 'en', 'after_meny_guest_msg', 'Welcome Guest ! Please <a href="%s">Login</a> or <a href="%s">Register</a>'),
(4348, 'en', 'being_watched', 'Being Watched'),
(4349, 'en', 'change_style_of_listing', 'Change Style of Listing'),
(4350, 'en', 'website_members', '%s Members'),
(4351, 'en', 'guest_homeright_msg', 'Watch, Upload, Share and more'),
(4352, 'en', 'reg_for_free', 'Register for free'),
(4353, 'en', 'rand_vids', 'Random Videos'),
(4354, 'en', 't_10_users', 'Top 10 Users'),
(4355, 'en', 'pending', 'Pending'),
(4356, 'en', 'confirm', 'Confirm'),
(4357, 'en', 'no_contacts', 'No Contacts'),
(4358, 'en', 'you_dont_hv_any_grp', 'You do not have any groups'),
(4359, 'en', 'leave_groups', 'Leave Groups'),
(4360, 'en', 'manage_grp_mems', 'Manage Group Members'),
(4361, 'en', 'pending_mems', 'Pending Members'),
(4362, 'en', 'active_mems', 'Active Members'),
(4363, 'en', 'disapprove', 'Disapprove'),
(4364, 'en', 'manage_grp_vids', 'Manage Group Videos'),
(4365, 'en', 'pending_vids', 'Pending Videos'),
(4366, 'en', 'no_pending_vids', 'No Pending Videos'),
(4367, 'en', 'no_active_videos', 'No Active Videos'),
(4368, 'en', 'active_videos', 'Active Videos'),
(4369, 'en', 'manage_playlists', 'Manage Playlists'),
(4370, 'en', 'total_items', 'Total Items'),
(4371, 'en', 'play_now', 'PLAY NOW'),
(4372, 'en', 'no_video_in_playlist', 'This playlist has no video'),
(4373, 'en', 'view', 'View'),
(4374, 'en', 'you_dont_hv_fav_vids', 'You do not have any favorite videos'),
(4375, 'en', 'private_messages', 'Private Messages'),
(4376, 'en', 'new_private_msg', 'New private message'),
(4377, 'en', 'search_for_s', 'Search For %s'),
(4378, 'en', 'signup_success_usr_ok', '<h2 style="margin: 5px 5px 8px; font-family: Arial,Verdana,sans-serif;">Just One More Step</h2>     	<p style="margin: 0px 5px; line-height: 18px; font-size: 11px;">Your are just one step behind from becoming an official memeber of our website.  Please check your email, we have sent you a confirmation email which contains a confirmation link from our website, Please click it to complete your registration.</p>'),
(4379, 'en', 'signup_success_usr_emailverify', '<h2 style="font-family:Arial,Verdana,sans-serif; margin:5px 5px 8px;">Welcome To our community</h2>\r\n    	<p style="margin:0px 5px; line-height:18px; font-size:11px;">Your email has been confirmed, Please <strong><a href="%s">click here to login</a></strong> and continue as our registered member.</p>'),
(4380, 'en', 'if_you_already_hv_account', 'if you already have an account, please login here '),
(4381, 'en', 'signup_message_under_login', ' <p>Our website is the home for video online:</p>\r\n          \r\n            <ul><li><strong>Watch</strong> millions  of videos</li><li><strong>Share favorites</strong> with friends and family</li>\r\n            <li><strong>Connect with other users</strong> who share your interests</li><li><strong>Upload your videos</strong> to a worldwide audience\r\n\r\n</li></ul>'),
(4382, 'en', 'new_mems_signup_here', 'New Members Signup Here'),
(4383, 'en', 'register_as_our_website_member', 'Register as a member, it’s free and easy just '),
(4384, 'en', 'video_complete_msg', '<h2>Video Upload Has Been Completed</h2>\r\n<span class="header1">Thank you! Your upload is complete.</span><br>\r\n<span class="tips">This video will be available in <a href="%s"><strong>My Videos</strong></a> after it has finished processing.</span>  \r\n<div class="upload_link_button" align="center">\r\n    <ul>\r\n        <li><a href="%s" >Upload Another Video</a></li>\r\n        <li><a href="%s" >Go to My Videos</a></li>\r\n    </ul>\r\n<div class=''clearfix''></div>\r\n</div>\r\n'),
(4385, 'en', 'upload_right_guide', ' <div>\r\n            <div>\r\n              <p>\r\n                <strong>\r\n                <strong>Important:</strong>\r\n                Do not upload any TV shows, music videos, music concerts, or  commercials without permission unless they consist entirely of content  you created yourself.</strong></p>\r\n                <p>The \r\n                <a href="#">Copyright Tips page</a> and the \r\n                <a href="#">Community Guidelines</a> can help you determine whether your video infringes someone else''s copyright.</p>\r\n                <p>By clicking "Upload Video", you are representing that this video does not violate Our website''s \r\n                <a id="terms-of-use-link" href="#">Terms of Use</a> \r\n                and that you own all copyrights in this video or have authorization to upload it.</p>\r\n            </div>\r\n        </div>'),
(4386, 'en', 'report_this_user', 'Report This User'),
(4387, 'en', 'add_to_favs', 'Add to Favorites'),
(4388, 'en', 'report_this', 'Report this!'),
(4389, 'en', 'share_this', 'Share This'),
(4390, 'en', 'add_to_playlist', 'Add to Playlist'),
(4391, 'en', 'view_profile', 'View Profile'),
(4392, 'en', 'subscribe', 'Subscribe'),
(4393, 'en', 'uploaded_by_s', 'Uploaded by %s'),
(4394, 'en', 'more', 'More'),
(4395, 'en', 'link_this_video', 'Link This Video'),
(4396, 'en', 'click_to_download_video', 'Click Here To Download This Video'),
(4397, 'en', 'name', 'Name'),
(4398, 'en', 'email_wont_display', 'Email (Wont’ display)'),
(4399, 'en', 'please_login_to_comment', 'Please login to comment'),
(4400, 'en', 'marked_as_spam_comment_by_user', 'Marked as spam, commented by <em>%s</em>'),
(4401, 'en', 'spam', 'Spam'),
(4402, 'en', 'user_commented_time', '<a href="%s">%s</a> commented %s'),
(4403, 'en', 'no_comments', 'No Comments'),
(4404, 'en', 'view_video', 'View Video'),
(4405, 'en', 'topic_icon', 'Topic Icon'),
(4406, 'en', 'group_options', 'Group option'),
(4407, 'en', 'info', 'Info'),
(4408, 'en', 'basic_info', 'Basic Info'),
(4409, 'en', 'group_owner', 'Group Owner'),
(4410, 'en', 'total_mems', 'Total Members'),
(4411, 'en', 'total_topics', 'Total Topics'),
(4412, 'en', 'grp_url', 'Group URL'),
(4413, 'en', 'more_details', 'More Details<'),
(4414, 'en', 'view_all_mems', 'View All Members'),
(4415, 'en', 'view_all_vids', 'View All Videos'),
(4416, 'en', 'topic_title', 'Topic Title'),
(4417, 'en', 'last_reply', 'Last Reply'),
(4418, 'en', 'topic_by_user', '<a href="%s">%s</a></span> by <a href="%s">%s</a>'),
(4419, 'en', 'no_topics', 'No Topics'),
(4420, 'en', 'last_post_time_by_user', '%s<br />\r\nby <a href="%s">%s'),
(4421, 'en', 'profile_views', 'Profile views'),
(4422, 'en', 'last_logged_in', 'Last logged in'),
(4423, 'en', 'last_active', 'Last active'),
(4424, 'en', 'total_logins', 'Total logins'),
(4425, 'en', 'total_videos_watched', 'Total videos watched'),
(4426, 'en', 'view_group', 'View Group'),
(4427, 'en', 'you_dont_hv_any_pm', 'No messages to display'),
(4428, 'en', 'date_sent', 'Date sent'),
(4429, 'en', 'show_hide', 'show - hide'),
(4430, 'en', 'quicklists', 'Quicklists'),
(4431, 'en', 'are_you_sure_rm_grp', 'Are you sure you want to remove this group ?'),
(4432, 'en', 'are_you_sure_del_grp', 'Are you sure you want to delete this group?'),
(4433, 'en', 'change_avatar', 'Change Avatar'),
(4434, 'en', 'change_bg', 'Change Background'),
(4435, 'en', 'uploaded_videos', 'Uploaded Videos'),
(4436, 'en', 'video_playlists', 'Video Playlists'),
(4437, 'en', 'add_contact_list', 'Add Contact List'),
(4438, 'en', 'topic_post', 'Topic Post'),
(4439, 'en', 'invite', 'Invite'),
(4440, 'en', 'time_ago', '%s %s ago'),
(4441, 'en', 'from_now', '%s %s from now'),
(4442, 'en', 'lang_has_been_activated', 'Language has been activated'),
(4443, 'en', 'lang_has_been_deactivated', 'Language has been deactivated'),
(4444, 'en', 'lang_default_no_actions', 'Language is default so you cannot perform actions on it'),
(4445, 'en', 'private_video_error', 'This video is private, only uploader friends can view this video'),
(4446, 'en', 'email_send_confirm', 'An email has been sent to our web administrator, we will respond you soon'),
(4447, 'en', 'name_was_empty', 'Name was empty'),
(4448, 'en', 'invalid_email', 'Invalid Email'),
(4449, 'en', 'pelase_enter_reason', 'Please enter reason for contact'),
(4450, 'en', 'please_enter_something_for_message', 'Please enter something in message box'),
(4451, 'en', 'comm_disabled_for_vid', 'Comments Disabled For This Video'),
(4452, 'en', 'coments_disabled_profile', 'Comments disabled for this profile'),
(4453, 'en', 'file_size_exceeds', 'File size exceeds ''%s kbs'''),
(4454, 'en', 'vid_rate_disabled', 'Video rating is disabled'),
(4455, 'en', 'chane_lang', '- Change Language -'),
(4456, 'en', 'recent', 'Recent'),
(4457, 'en', 'viewed', 'Viewed'),
(4458, 'en', 'top_rated', 'Top Rated'),
(4459, 'en', 'commented', 'Commented'),
(4460, 'en', 'searching_keyword_in_obj', 'Searchin ''%s'' in %s'),
(4461, 'en', 'no_results_found', 'No results found'),
(4462, 'en', 'please_enter_val_bw_min_max', 'Please enter ''%s'' value between ''%s'' and ''%s'''),
(4461, 'en', 'no_results_found', 'No results found'),
(4462, 'en', 'please_enter_val_bw_min_max', 'Please enter ''%s'' value between ''%s'' and ''%s'''),
(4463, 'en', 'no_new_subs_video', 'No new videos found in subscriptions'),
(4464, 'en', 'inapp_content', 'Inappropriate Content'),
(4465, 'en', 'copyright_infring', 'Copyright infringement'),
(4466, 'en', 'sexual_content', 'Sexual Content'),
(4467, 'en', 'violence_replusive_content', 'Violence or repulsive content'),
(4468, 'en', 'disturbing', 'Disturbing'),
(4469, 'en', 'other', 'Other');

ALTER TABLE `{tbl_prefix}phrases`  ORDER BY `id`;
ALTER TABLE `{tbl_prefix}languages` ADD `language_active` ENUM( "yes", "no" ) NOT NULL DEFAULT 'yes' AFTER `language_regex` ;

UPDATE `{tbl_prefix}config` SET `name` =  'allow_registration'  WHERE `name` = 'allow_registeration' LIMIT 1 ;