CREATE TABLE IF NOT EXISTS `cb_admin_notes` (
  `note_id` int(225) NOT NULL AUTO_INCREMENT,
  `note` text CHARACTER SET ucs2 NOT NULL,
  `date_added` datetime NOT NULL,
  `userid` int(225) NOT NULL,
  PRIMARY KEY (`note_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;


CREATE TABLE IF NOT EXISTS `cb_pages` (
  `page_id` int(11) NOT NULL AUTO_INCREMENT,
  `page_name` varchar(225) NOT NULL,
  `page_title` varchar(225) NOT NULL,
  `page_content` text NOT NULL,
  `userid` int(225) NOT NULL,
  `active` enum('yes','no') NOT NULL,
  `delete_able` enum('yes','no') NOT NULL DEFAULT 'yes',
  `date_added` datetime NOT NULL,
  PRIMARY KEY (`page_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=5 ;

--
-- Dumping data for table `cb_pages`
--

INSERT INTO `cb_pages` (`page_id`, `page_name`, `page_title`, `page_content`, `userid`, `active`, `delete_able`, `date_added`) VALUES
(1, 'About us', 'About us', '<div style="margin: auto; width: 98%;"><font style="font-weight: bold;" size="4">About Us</font><hr noshade="noshade" size="1">\r\n  \r\n  \r\n    <p><span style="font-weight: bold;">ClipBucket </span>is one of the world''s best video sites . We specialize in short-form\r\noriginal content - from new, emerging talents and established Hollywood\r\nheavyweights alike. We''re committed to delivering an exceptional\r\nentertainment experience, and we do so by engaging and empowering our\r\naudience every step of the way.</p>\r\n      <p>Everyone can Watch Videos\r\non <span style="font-weight: bold;">ClipBucket</span>. People can see first-hand accounts of current events, find\r\nvideos about their hobbies and interests, and discover the\r\nquirky and unusual. As more people capture special moments on\r\nvideo,<span style="font-weight: bold;">ClipBucket </span>is empowering them to become the broadcasters of\r\ntomorrow.</p>\r\n      <p><span style="font-weight: bold;">ClipBucket </span>not only a video sharing website but\r\nalso has social network features, you can make friends,\r\nand send them videos and private messages. <span style="font-weight: bold;">ClipBucket </span><span style="font-weight: bold;"></span> also has built in\r\nrating system and comment system so that people can discuss on there\r\ninterested videos, not only comment but also, people can rate Comments.</p></div>', 1, 'yes', 'no', '2010-01-01 08:47:56'),
(2, 'Privacy Policy', 'Privacy Policy', '<h1>ClipBucket Privacy Notice - YT Version\r\n</h1>\r\n<h2>Personal Information</h2>\r\n<ul>\r\n  <li><strong>Browsing ClipBucket</strong> You can watch videos on ClipBucket without having a ClipBucket Account or a  PHPBucket Account. You also can contact us through the ClipBucket Help Center  or by emailing us directly without having to register for an account.</li>\r\n  <li><strong>Your ClipBucket Account.</strong> For some activities on ClipBucket, like uploading videos, posting  comments, flagging videos, or watching restricted videos, you need a  ClipBucket or PHPBucket Account. We ask for some personal information when  you create an account, including your email address and a password,  which is used to protect your account from unauthorized access. A  PHPBucket Account, additionally, allows you to access other PHPBucket  services that require registration.</li>\r\n  <li><strong>Usage Information.</strong> When you use ClipBucket, we may record information about your usage of the  site, such as the channels, groups and favorites you subscribe to,  which other users you communicate with, the videos you watch, the  frequency and size of data transfers, and information you display about  yourself as well as information you click on in ClipBucket (including UI  elements, settings). If you are logged in, we may associate that  information with your ClipBucket Account. In order to ensure the quality  of our service to you, we may place a tag (also called a "web beacon")  in HTML-based customer support emails or other communications with you  in order to confirm delivery.</li>\r\n  <li><strong>Content Uploaded to Site.</strong> Any personal information or video content that you voluntarily disclose  online (e.g., video comments, your profile page) may be collected and  used by others. If you download the ClipBucket Uploader, your copy  includes a unique application number. This number, and information  about your installation of the Uploader (version number, language) will  be sent to ClipBucket when the Uploader automatically checks for updates  and will be used to update your version of the Uploader.</li>\r\n</ul>\r\n<h2>Uses</h2>\r\n<ul>\r\n  <li>If  you submit personal information to ClipBucket, we may use that information  to operate, maintain, and improve the features and functionality of  ClipBucket, and to process any flagging activity or other communication  you send to us.</li>\r\n  <li>We do not use your  email address or other personal information to send commercial or  marketing messages without your consent. We may use your email address  without further consent for non-marketing or administrative purposes  (such as notifying you of major ClipBucket changes or for customer service  purposes). You also can choose how often ClipBucket sends you email  updates in your ClipBucket Account settings page.</li>\r\n  <li>We  use cookies, web beacons, and log file information to: (a) store  information so that you will not have to re-enter it during your visit  or the next time you visit ClipBucket; (b) provide custom, personalized  content and information; (c) monitor the effectiveness of our marketing  campaigns; (d) monitor aggregate metrics such as total number of  visitors and pages viewed; and (e) track your entries, submissions, and  status in promotions, sweepstakes, and contests.</li>\r\n</ul>\r\n<h2>Information That is Publicly Available</h2>\r\n<ul>\r\n  <li>When  you create a ClipBucket Account, some information about your ClipBucket  Account and your account activity will be provided to other users of  ClipBucket. This may include the date you opened your ClipBucket Account, the  date you last logged into your ClipBucket Account, your age (if you choose  to make it public), the country and the number of videos you have  watched.</li>\r\n  <li>Your ClipBucket Account name,  not your email address, is displayed to other users when you engage in  certain activities on ClipBucket, such as when you upload videos or send  messages through ClipBucket. Other users can contact you by leaving a  message or comment on the site.</li>\r\n  <li>Any  videos that you submit to ClipBucket may be redistributed through the  internet and other media channels, and may be viewed by other ClipBucket  users or the general public. </li>\r\n  <li>You  may also choose to add personal information which may include your  name, gender, profile picture or other details, that will be visible to  other users on your ClipBucket Account channel page. If you choose to add  certain features to your ClipBucket Account channel page, then these  features and your activity associated with these features will be  displayed to other users and may be aggregated and shared with your  friends or other users. Such shared activity may include your favorite  videos, videos you rated and videos that you have uploaded.</li>\r\n</ul>\r\n<h2>Your Choices</h2>\r\n<ul>\r\n  <li>If  you have a ClipBucket Account, you may update or correct your personal  profile information, email preferences and privacy settings at any time  by visiting your account profile page. </li>\r\n  <li>You  may control the information that is available to other users and your  confirmed friends at any time by editing your ClipBucket Account and the  features that are included on your channel page. If you have enabled  Active Sharing, other users may see that you, as identified by your  account name, not your email address, are watching the same video.</li>\r\n  <li>You  may, of course, decline to submit personal information through ClipBucket,  in which case you can still view videos and explore ClipBucket, but  ClipBucket may not be able to provide certain services to you. Some  advanced ClipBucket features may use other PHPBucket services like PHPBucket  Checkout or AdSense. The privacy notices of those services govern the  use of your personal information associated with them.</li>\r\n</ul>\r\n', 1, 'yes', 'no', '2010-01-01 08:52:46'),
(3, 'Terms of Serivce', 'Terms of Service', 'Write your own terms of service...', 1, 'yes', 'no', '2010-01-01 08:53:57'),
(4, 'Help', 'Help', '<span style="font-weight: bold;">How to use ClipBucket</span><br><ol><li>Articles will be written pretty soon</li></ol>', 1, 'yes', 'no', '2010-01-01 09:17:36');



INSERT INTO `config` (`configid`, `name`, `value`) VALUES
(84, 'videos_items_grp_page', '12'),
(85, 'videos_items_hme_page', '20'),
(86, 'videos_items_columns', '9'),
(87, 'videos_items_ufav_page', '25'),
(88, 'videos_items_uvid_page', '25'),
(89, 'videos_items_search_page', '30'),
(90, 'videos_item_channel_page', '10'),
(91, 'users_items_subscriptions', '5'),
(92, 'users_items_subscibers', '5'),
(93, 'users_items_contacts_channel', '5'),
(94, 'users_items_search_page', '12'),
(95, 'users_items_group_page', '15'),
(96, 'cbhash', 'PGRpdiBhbGlnbj0iY2VudGVyIj48IS0tIERvIG5vdCByZW1vdmUgdGhpcyBjb3B5cmlnaHQgbm90aWNlIC0tPg0KUG93ZXJlZCBieSA8YSBocmVmPSJodHRwOi8vY2xpcC1idWNrZXQuY29tLyI+Q2xpcEJ1Y2tldDwvYT4gdjIuMC4xPGJyPg0KQ29weXJpZ2h0IMKpMjAwNyAtIDIwMTAsIENsaXBCdWNrZXQNCjwhLS0gRG8gbm90IHJlbW92ZSB0aGlzIGNvcHlyaWdodCBub3RpY2UgLS0+PC9kaXY+'),
(97, 'min_video_title', '4'),
(98, 'max_video_title', '60'),
(99, 'min_video_desc', '5'),
(100, 'max_video_desc', '300'),
(101, 'video_categories', '4'),
(102, 'min_video_tags', '3'),
(103, 'max_video_tags', '30'),
(104, 'video_codec', 'flv'),
(105, 'date_released', '01-05-2010'),
(106, 'date_installed', '01-05-2010'),
(107, 'date_updated', now());



UPDATE `config` SET `name` = 'flvtool2path' WHERE `config`.`configid` =12 LIMIT 1 ;

UPDATE `config` SET `name` = 'mp4boxpath',
`value` = '/usr/bin/Mp4Box' WHERE `config`.`configid` =13 LIMIT 1 ;



ALTER TABLE `video` ADD `uploader_ip` VARCHAR( 20 ) NOT NULL;

DROP TABLE IF EXISTS `user_levels`;
CREATE TABLE `user_levels` (
  `user_level_id` int(20) NOT NULL AUTO_INCREMENT,
  `user_level_active` enum('yes','no') CHARACTER SET latin1 NOT NULL DEFAULT 'yes',
  `user_level_name` varchar(100) CHARACTER SET latin1 NOT NULL,
  `user_level_is_default` enum('yes','no') NOT NULL DEFAULT 'no',
  PRIMARY KEY (`user_level_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=16 ;

--
-- Dumping data for table `user_levels`
--

INSERT INTO `user_levels` (`user_level_id`, `user_level_active`, `user_level_name`, `user_level_is_default`) VALUES
(4, 'yes', 'Guest', 'yes'),
(2, 'yes', 'Registered User', 'yes'),
(3, 'yes', 'Inactive User', 'yes'),
(1, 'yes', 'Administrator', 'yes'),
(5, 'yes', 'Global Moderator', 'yes');

-- --------------------------------------------------------

--
-- Table structure for table `user_levels_permissions`
--

DROP TABLE IF EXISTS `user_levels_permissions`;
CREATE TABLE `user_levels_permissions` (
  `user_level_permission_id` int(22) NOT NULL AUTO_INCREMENT,
  `user_level_id` int(22) NOT NULL,
  `admin_access` enum('yes','no') NOT NULL DEFAULT 'no',
  `allow_video_upload` enum('yes','no') NOT NULL DEFAULT 'yes',
  `view_video` enum('yes','no') NOT NULL DEFAULT 'yes',
  `view_channel` enum('yes','no') NOT NULL DEFAULT 'yes',
  `view_group` enum('yes','no') NOT NULL DEFAULT 'yes',
  `view_videos` enum('yes','no') NOT NULL DEFAULT 'yes',
  `avatar_upload` enum('yes','no') NOT NULL DEFAULT 'yes',
  `video_moderation` enum('yes','no') NOT NULL DEFAULT 'no',
  `member_moderation` enum('yes','no') NOT NULL DEFAULT 'no',
  `ad_manager_access` enum('yes','no') NOT NULL DEFAULT 'no',
  `manage_template_access` enum('yes','no') NOT NULL DEFAULT 'no',
  `group_moderation` enum('yes','no') NOT NULL DEFAULT 'no',
  `web_config_access` enum('yes','no') NOT NULL DEFAULT 'no',
  `view_channels` enum('yes','no') NOT NULL DEFAULT 'yes',
  `view_groups` enum('yes','no') NOT NULL DEFAULT 'yes',
  `playlist_access` enum('yes','no') NOT NULL DEFAULT 'yes',
  `allow_channel_bg` enum('yes','no') NOT NULL DEFAULT 'yes',
  `private_msg_access` enum('yes','no') NOT NULL DEFAULT 'yes',
  `edit_video` enum('yes','no') NOT NULL DEFAULT 'yes',
  `admin_del_access` enum('yes','no') NOT NULL DEFAULT 'yes',
  PRIMARY KEY (`user_level_permission_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=14 ;

--
-- Dumping data for table `user_levels_permissions`
--

INSERT INTO `user_levels_permissions` (`user_level_permission_id`, `user_level_id`, `admin_access`, `allow_video_upload`, `view_video`, `view_channel`, `view_group`, `view_videos`, `avatar_upload`, `video_moderation`, `member_moderation`, `ad_manager_access`, `manage_template_access`, `group_moderation`, `web_config_access`, `view_channels`, `view_groups`, `playlist_access`, `allow_channel_bg`, `private_msg_access`, `edit_video`, `admin_del_access`) VALUES
(5, 5, 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes'),
(2, 2, 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes'),
(3, 3, 'no', 'no', 'yes', 'yes', 'yes', 'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes'),
(1, 1, 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes'),
(4, 4, 'no', 'no', 'yes', 'yes', 'yes', 'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes');

-- --------------------------------------------------------

--
-- Table structure for table `user_permissions`
--

DROP TABLE IF EXISTS `user_permissions`;
CREATE TABLE `user_permissions` (
  `permission_id` int(225) NOT NULL AUTO_INCREMENT,
  `permission_type` int(225) NOT NULL,
  `permission_name` varchar(225) CHARACTER SET latin1 NOT NULL,
  `permission_code` varchar(225) CHARACTER SET latin1 NOT NULL,
  `permission_desc` mediumtext CHARACTER SET latin1 NOT NULL,
  `permission_default` enum('yes','no') CHARACTER SET latin1 NOT NULL DEFAULT 'yes',
  PRIMARY KEY (`permission_id`),
  UNIQUE KEY `permission_code` (`permission_code`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=33 ;

--
-- Dumping data for table `user_permissions`
--

INSERT INTO `user_permissions` (`permission_id`, `permission_type`, `permission_name`, `permission_code`, `permission_desc`, `permission_default`) VALUES
(12, 3, 'Admin Access', 'admin_access', 'User can access admin panel', 'no'),
(13, 1, 'View Video', 'view_video', 'User can view videos', 'yes'),
(11, 2, 'Allow Video Upload', 'allow_video_upload', 'Allow user to upload videos', 'yes'),
(14, 1, 'View Channel', 'view_channel', 'User Can View Channel', 'yes'),
(15, 1, 'View Group', 'view_group', 'User Can View Group', 'yes'),
(16, 1, 'View Videos Page', 'view_videos', 'User Can view videos page', 'yes'),
(17, 2, 'Allow Avatar Upload', 'avatar_upload', 'User can upload video', 'yes'),
(19, 3, 'Video Moderation', 'video_moderation', 'User Can Moderate Videos', 'no'),
(20, 3, 'Member Moderation', 'member_moderation', 'User Can Moderate Members', 'no'),
(21, 3, 'Advertisment Manager', 'ad_manager_access', 'User can change advertisment', 'no'),
(22, 3, 'Manage Templates', 'manage_template_access', 'User can manage website templates', 'no'),
(23, 3, 'Groups Moderation', 'group_moderation', 'User can moderate group', 'no'),
(24, 3, 'Website Configurations', 'web_config_access', 'User can change website settings', 'no'),
(25, 1, 'View channels', 'view_channels', 'User can channels', 'yes'),
(26, 1, 'View Groups', 'view_groups', 'User can view groups', 'yes'),
(28, 4, 'Playlist Access', 'playlist_access', 'User can access playlists', 'yes'),
(29, 2, 'Allow Channel Background', 'allow_channel_bg', 'Allow user to change channel background', 'yes'),
(30, 4, 'Private Messages', 'private_msg_access', 'User can use private messaging system', 'yes'),
(31, 4, 'Edit Video', 'edit_video', 'User can edit video', 'yes'),
(32, 3, 'Admin Delete Access', 'admin_del_access', 'User can delete comments if has admin access', 'no'); 



INSERT INTO `cb_pages` (`page_id`, `page_name`, `page_title`, `page_content`, `userid`, `active`, `delete_able`, `date_added`) VALUES (NULL, '403 Error', '403 Forbidden', '<h2>403 Access Denied</h2>
Sorry, you cannot access this page...', '1', 'yes', 'no', ''), (NULL, '404 Error', '404 Not Found', '<h2>404 Not Found</h2>
we are unable to find requested URL on server..', '1', 'yes', 'no', '');

INSERT INTO `config` ( `name`, `value`) VALUES
( 'support_email', 'support@website.tld'),
( 'website_email', 'email@website.td'),
( 'welcome_email', 'welcome@website.tld');

DROP TABLE IF EXISTS `phrases`;
CREATE TABLE `phrases` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `lang_iso` varchar(5) NOT NULL DEFAULT 'en',
  `varname` varchar(250) NOT NULL DEFAULT '',
  `text` text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=860 ;

ALTER TABLE `video` ADD `uploader_ip` VARCHAR( 20 ) NOT NULL;

DROP TABLE IF EXISTS `user_levels`;
CREATE TABLE `user_levels` (
  `user_level_id` int(20) NOT NULL AUTO_INCREMENT,
  `user_level_active` enum('yes','no') CHARACTER SET latin1 NOT NULL DEFAULT 'yes',
  `user_level_name` varchar(100) CHARACTER SET latin1 NOT NULL,
  `user_level_is_default` enum('yes','no') NOT NULL DEFAULT 'no',
  PRIMARY KEY (`user_level_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=16 ;

--
-- Dumping data for table `user_levels`
--

INSERT INTO `user_levels` (`user_level_id`, `user_level_active`, `user_level_name`, `user_level_is_default`) VALUES
(4, 'yes', 'Guest', 'yes'),
(2, 'yes', 'Registered User', 'yes'),
(3, 'yes', 'Inactive User', 'yes'),
(1, 'yes', 'Administrator', 'yes'),
(5, 'yes', 'Global Moderator', 'yes');

-- --------------------------------------------------------

--
-- Table structure for table `user_levels_permissions`
--

DROP TABLE IF EXISTS `user_levels_permissions`;
CREATE TABLE `user_levels_permissions` (
  `user_level_permission_id` int(22) NOT NULL AUTO_INCREMENT,
  `user_level_id` int(22) NOT NULL,
  `admin_access` enum('yes','no') NOT NULL DEFAULT 'no',
  `allow_video_upload` enum('yes','no') NOT NULL DEFAULT 'yes',
  `view_video` enum('yes','no') NOT NULL DEFAULT 'yes',
  `view_channel` enum('yes','no') NOT NULL DEFAULT 'yes',
  `view_group` enum('yes','no') NOT NULL DEFAULT 'yes',
  `view_videos` enum('yes','no') NOT NULL DEFAULT 'yes',
  `avatar_upload` enum('yes','no') NOT NULL DEFAULT 'yes',
  `video_moderation` enum('yes','no') NOT NULL DEFAULT 'no',
  `member_moderation` enum('yes','no') NOT NULL DEFAULT 'no',
  `ad_manager_access` enum('yes','no') NOT NULL DEFAULT 'no',
  `manage_template_access` enum('yes','no') NOT NULL DEFAULT 'no',
  `group_moderation` enum('yes','no') NOT NULL DEFAULT 'no',
  `web_config_access` enum('yes','no') NOT NULL DEFAULT 'no',
  `view_channels` enum('yes','no') NOT NULL DEFAULT 'yes',
  `view_groups` enum('yes','no') NOT NULL DEFAULT 'yes',
  `playlist_access` enum('yes','no') NOT NULL DEFAULT 'yes',
  `allow_channel_bg` enum('yes','no') NOT NULL DEFAULT 'yes',
  `private_msg_access` enum('yes','no') NOT NULL DEFAULT 'yes',
  `edit_video` enum('yes','no') NOT NULL DEFAULT 'yes',
  `admin_del_access` enum('yes','no') NOT NULL DEFAULT 'yes',
  PRIMARY KEY (`user_level_permission_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=14 ;

--
-- Dumping data for table `user_levels_permissions`
--

INSERT INTO `user_levels_permissions` (`user_level_permission_id`, `user_level_id`, `admin_access`, `allow_video_upload`, `view_video`, `view_channel`, `view_group`, `view_videos`, `avatar_upload`, `video_moderation`, `member_moderation`, `ad_manager_access`, `manage_template_access`, `group_moderation`, `web_config_access`, `view_channels`, `view_groups`, `playlist_access`, `allow_channel_bg`, `private_msg_access`, `edit_video`, `admin_del_access`) VALUES
(5, 5, 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes'),
(2, 2, 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes'),
(3, 3, 'no', 'no', 'yes', 'yes', 'yes', 'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes'),
(1, 1, 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes'),
(4, 4, 'no', 'no', 'yes', 'yes', 'yes', 'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes');

-- --------------------------------------------------------

--
-- Table structure for table `user_permissions`
--

DROP TABLE IF EXISTS `user_permissions`;
CREATE TABLE `user_permissions` (
  `permission_id` int(225) NOT NULL AUTO_INCREMENT,
  `permission_type` int(225) NOT NULL,
  `permission_name` varchar(225) CHARACTER SET latin1 NOT NULL,

  `permission_code` varchar(225) CHARACTER SET latin1 NOT NULL,
  `permission_desc` mediumtext CHARACTER SET latin1 NOT NULL,
  `permission_default` enum('yes','no') CHARACTER SET latin1 NOT NULL DEFAULT 'yes',
  PRIMARY KEY (`permission_id`),
  UNIQUE KEY `permission_code` (`permission_code`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=33 ;

--
-- Dumping data for table `user_permissions`
--

INSERT INTO `user_permissions` (`permission_id`, `permission_type`, `permission_name`, `permission_code`, `permission_desc`, `permission_default`) VALUES
(12, 3, 'Admin Access', 'admin_access', 'User can access admin panel', 'no'),
(13, 1, 'View Video', 'view_video', 'User can view videos', 'yes'),
(11, 2, 'Allow Video Upload', 'allow_video_upload', 'Allow user to upload videos', 'yes'),
(14, 1, 'View Channel', 'view_channel', 'User Can View Channel', 'yes'),
(15, 1, 'View Group', 'view_group', 'User Can View Group', 'yes'),
(16, 1, 'View Videos Page', 'view_videos', 'User Can view videos page', 'yes'),
(17, 2, 'Allow Avatar Upload', 'avatar_upload', 'User can upload video', 'yes'),
(19, 3, 'Video Moderation', 'video_moderation', 'User Can Moderate Videos', 'no'),
(20, 3, 'Member Moderation', 'member_moderation', 'User Can Moderate Members', 'no'),
(21, 3, 'Advertisment Manager', 'ad_manager_access', 'User can change advertisment', 'no'),
(22, 3, 'Manage Templates', 'manage_template_access', 'User can manage website templates', 'no'),
(23, 3, 'Groups Moderation', 'group_moderation', 'User can moderate group', 'no'),
(24, 3, 'Website Configurations', 'web_config_access', 'User can change website settings', 'no'),
(25, 1, 'View channels', 'view_channels', 'User can channels', 'yes'),
(26, 1, 'View Groups', 'view_groups', 'User can view groups', 'yes'),
(28, 4, 'Playlist Access', 'playlist_access', 'User can access playlists', 'yes'),
(29, 2, 'Allow Channel Background', 'allow_channel_bg', 'Allow user to change channel background', 'yes'),
(30, 4, 'Private Messages', 'private_msg_access', 'User can use private messaging system', 'yes'),
(31, 4, 'Edit Video', 'edit_video', 'User can edit video', 'yes'),
(32, 3, 'Admin Delete Access', 'admin_del_access', 'User can delete comments if has admin access', 'no'); 

INSERT INTO `cb_pages` (`page_id`, `page_name`, `page_title`, `page_content`, `userid`, `active`, `delete_able`, `date_added`) VALUES (NULL, '403 Error', '403 Forbidden', '<h2>403 Access Denied</h2>
Sorry, you cannot access this page...', '1', 'yes', 'no', ''), (NULL, '404 Error', '404 Not Found', '<h2>404 Not Found</h2>
we are unable to find requested URL on server..', '1', 'yes', 'no', '');

INSERT INTO `config` ( `name`, `value`) VALUES
( 'support_email', 'support@website.tld'),
( 'website_email', 'email@website.td'),
( 'welcome_email', 'welcome@website.tld');

DROP TABLE IF EXISTS `phrases`;
CREATE TABLE `phrases` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `lang_iso` varchar(5) NOT NULL DEFAULT 'en',
  `varname` varchar(250) NOT NULL DEFAULT '',
  `text` text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=860 ;

DROP TABLE IF EXISTS `cb_stats`;
CREATE TABLE `cb_stats` (
  `stat_id` int(255) NOT NULL AUTO_INCREMENT,
  `date_added` date NOT NULL,
  `video_stats` text NOT NULL,
  `user_stats` text NOT NULL,
  `group_stats` text NOT NULL,
  PRIMARY KEY (`stat_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

    DROP TABLE `stats` ;
	DROP TABLE `editors_picks` ;
    RENAME TABLE  `cb_admin_notes`  TO `admin_notes` ;
    RENAME TABLE  `cb_pages`  TO `pages` ;
    RENAME TABLE  `cb_playlists`  TO `playlists` ;
    RENAME TABLE  `cb_playlist_items`  TO `playlist_items ` ;
	RENAME TABLE  `cb_editors_picks`  TO `editors_picks ` ;
    RENAME TABLE  `cb_stats`  TO `stats ` ;

    RENAME TABLE  `action_log`  TO `{tbl_prefix}action_log` ;
    RENAME TABLE  `admin_notes`  TO `{tbl_prefix}admin_notes` ;
    RENAME TABLE  `ads_data`  TO `{tbl_prefix}ads_data` ;
    RENAME TABLE  `ads_placements`  TO `{tbl_prefix}ads_placements` ;
    RENAME TABLE  `comments`  TO `{tbl_prefix}comments` ;
    RENAME TABLE  `config`  TO `{tbl_prefix}config` ;
    RENAME TABLE  `contacts`  TO `{tbl_prefix}contacts` ;
    RENAME TABLE  `conversion_queue`  TO `{tbl_prefix}conversion_queue` ;
    RENAME TABLE  `countries`  TO `{tbl_prefix}countries` ;
    RENAME TABLE  `editors_picks`  TO `{tbl_prefix}editors_picks` ;
    RENAME TABLE  `email_settings`  TO `{tbl_prefix}email_settings` ;
    RENAME TABLE  `email_templates`  TO `{tbl_prefix}email_templates` ;
    RENAME TABLE  `favorites`  TO `{tbl_prefix}favorites` ;
    RENAME TABLE  `flags`  TO `{tbl_prefix}flags` ;
    RENAME TABLE  `groups`  TO `{tbl_prefix}groups` ;
    RENAME TABLE  `group_categories`  TO `{tbl_prefix}group_categories` ;
    RENAME TABLE  `groups`  TO `{tbl_prefix}groups` ;
    RENAME TABLE  `group_members`  TO `{tbl_prefix}group_members` ;
    RENAME TABLE  `group_posts`  TO `{tbl_prefix}group_posts` ;
    RENAME TABLE  `group_topics`  TO `{tbl_prefix}group_topics` ;
    RENAME TABLE  `group_videos`  TO `{tbl_prefix}group_videos` ;
	RENAME TABLE  `group_invitations`  TO `{tbl_prefix}group_invitations` ;
    RENAME TABLE  `languages`  TO `{tbl_prefix}languages` ;
    RENAME TABLE  `messages`  TO `{tbl_prefix}messages` ;
    RENAME TABLE  `modules`  TO `{tbl_prefix}modules` ;
    RENAME TABLE  `pages`  TO `{tbl_prefix}pages` ;
    RENAME TABLE  `phrases`  TO `{tbl_prefix}phrases` ;
    RENAME TABLE  `playlists`  TO `{tbl_prefix}playlists` ;
    RENAME TABLE  `playlist_items`  TO `{tbl_prefix}playlist_items` ;
    RENAME TABLE  `plugins`  TO `{tbl_prefix}plugins` ;
    RENAME TABLE  `plugin_config`  TO `{tbl_prefix}plugin_config` ;
    RENAME TABLE  `sessions`  TO `{tbl_prefix}sessions` ;
    RENAME TABLE  `stats`  TO `{tbl_prefix}stats` ;
    RENAME TABLE  `subscriptions`  TO `{tbl_prefix}subscriptions` ;
    RENAME TABLE  `template`  TO `{tbl_prefix}template` ;
    RENAME TABLE  `users`  TO `{tbl_prefix}users` ;
    RENAME TABLE  `user_categories`  TO `{tbl_prefix}user_categories` ;
    RENAME TABLE  `user_levels`  TO `{tbl_prefix}user_levels` ;
    RENAME TABLE  `user_levels_permissions`  TO `{tbl_prefix}user_levels_permissions` ;
    RENAME TABLE  `user_permissions`  TO `{tbl_prefix}user_permissions` ;
    RENAME TABLE  `user_permission_types`  TO `{tbl_prefix}user_permission_types` ;
    RENAME TABLE  `user_profile`  TO `{tbl_prefix}user_profile` ;
    RENAME TABLE  `validation_re`  TO `{tbl_prefix}validation_re` ;
    RENAME TABLE  `video`  TO `{tbl_prefix}video` ;
    RENAME TABLE  `video_categories`  TO `{tbl_prefix}video_categories` ;
    RENAME TABLE  `video_favourites`  TO `{tbl_prefix}video_favourites` ;
    RENAME TABLE  `video_files`  TO `{tbl_prefix}video_files` ;

    ALTER TABLE `{tbl_prefix}video` ADD `refer_url` TEXT NOT NULL AFTER `embed_code` ;
    ALTER TABLE `{tbl_prefix}video` ADD `downloads` BIGINT( 255 ) NOT NULL AFTER `refer_url`;
    ALTER TABLE `{tbl_prefix}users` ADD `total_downloads` BIGINT( 255 ) NOT NULL AFTER `welcome_email_sent`;
    
    ALTER TABLE `{tbl_prefix}video_categories` ADD `category_order` INT( 5 ) NOT NULL DEFAULT '1' AFTER `category_name` ;
    ALTER TABLE `{tbl_prefix}user_categories` ADD `category_order` INT( 5 ) NOT NULL DEFAULT '1' AFTER `category_name` ;
    ALTER TABLE `{tbl_prefix}group_categories` ADD `category_order` INT( 5 ) NOT NULL DEFAULT '1' AFTER `category_name` ;
    
    ALTER TABLE `{tbl_prefix}comments` ADD `type_owner_id` INT( 255 ) NOT NULL AFTER `type_id` ;
    ALTER TABLE `{tbl_prefix}users` ADD `total_subscriptions` BIGINT( 255 ) NOT NULL AFTER `subscribers` ;
    
    INSERT INTO `{tbl_prefix}config` (`configid` ,`name` ,`value`)
    VALUES (NULL , 'anonymous_id', '1'),
    (NULL , 'date_format', 'd-m-Y'),
    ( NULL , 'default_time_zone', '5'),
    (NULL , 'autoplay_video', 'yes');
	
	TRUNCATE TABLE `{tbl_prefix}phrases` ;
	ALTER TABLE `{tbl_prefix}conversion_queue` ADD `time_started` VARCHAR( 32 ) NOT NULL AFTER `date_added` ,
ADD `time_completed` VARCHAR( 32 ) NOT NULL AFTER `time_started`;
	
INSERT INTO `{tbl_prefix}phrases` (`id`, `lang_iso`, `varname`, `text`) VALUES
(1, 'en', 'ad_name_error', 'Please Enter Name For The Advertisments'),
(2, 'en', 'ad_code_error', 'Error : Please Enter Code For Advertisement'),
(3, 'en', 'ad_exists_error1', 'Add Does not exists'),
(4, 'en', 'ad_exists_error2', 'Error : Advertisement With This Name Already Exists'),
(5, 'en', 'ad_add_msg', 'Advertisment Has Been Added'),
(6, 'en', 'ad_msg', 'Ad Has Been '),
(7, 'en', 'ad_update_msg', 'Advertisment Has Been Updated'),
(8, 'en', 'ad_del_msg', 'Advertisement Has Been Deleted'),
(9, 'en', 'ad_deactive', 'Deactivated'),
(10, 'en', 'ad_active', 'Activated'),
(11, 'en', 'ad_placment_delete_msg', 'Placement Has Been Removed'),
(12, 'en', 'ad_placement_err1', 'Placement already exists'),
(13, 'en', 'ad_placement_err2', 'Please Enter Name For Placement'),
(14, 'en', 'ad_placement_err3', 'Please Enter Code For Placement'),
(15, 'en', 'ad_placement_msg', 'Placement Has Been Added'),
(16, 'en', 'cat_img_error', 'Please Upload JPEG, GIF or PNG image only'),
(17, 'en', 'cat_exist_error', 'Category doesn&#8217;t exist'),
(18, 'en', 'cat_add_msg', 'Category has been added successfully'),
(19, 'en', 'cat_update_msg', 'Category has been updated'),
(20, 'en', 'grp_err', 'Group Doesn&#8217;t Exist'),
(21, 'en', 'grp_fr_msg', 'Group has been set as featured'),
(22, 'en', 'grp_fr_msg1', 'Selected Groups Have Been Removed From The Featured List'),
(23, 'en', 'grp_ac_msg', 'Selected Groups Have Been Activated'),
(24, 'en', 'grp_dac_msg', 'Selected Groups Have Been Dectivated'),
(25, 'en', 'grp_del_msg', 'Group has been deleted'),
(26, 'en', 'editor_pic_up', 'Video Has Been Moved Up'),
(27, 'en', 'editor_pic_down', 'Video Has Been Moved Down'),
(28, 'en', 'plugin_install_msg', 'Plugin has been installed'),
(29, 'en', 'plugin_no_file_err', 'No file was found'),
(30, 'en', 'plugin_file_detail_err', 'Unknown plugin details found'),
(31, 'en', 'plugin_installed_err', 'Plugin already installed'),
(32, 'en', 'plugin_no_install_err', 'Plugin is not installed'),
(33, 'en', 'grp_name_error', 'Please enter group name'),
(34, 'en', 'grp_name_error1', 'Group Name Already Exists'),
(35, 'en', 'grp_des_error', 'Please Enter Little Description For Group'),
(36, 'en', 'grp_tags_error', 'Please Enter Tags For Group'),
(37, 'en', 'grp_url_error', 'Please enter valid url for Group'),
(38, 'en', 'grp_url_error1', 'Please enter Valid URL name'),
(39, 'en', 'grp_url_error2', 'Group URL Already Exists, Please Choose a Different URL'),
(40, 'en', 'grp_tpc_error', 'Please enter a topic to add'),
(41, 'en', 'grp_comment_error', 'You must enter a comment'),
(42, 'en', 'grp_join_error', 'You have already joined this group'),
(43, 'en', 'grp_prvt_error', 'This Group Is Private, Please Login to View this Group'),
(44, 'en', 'grp_inact_error', 'This Group Is Inactive, Please Contact Administrator for the problem'),
(45, 'en', 'grp_join_error1', 'You Have Not Joined This Group Yet'),
(46, 'en', 'grp_exist_error', 'Sorry, Group Doesn&#8217;t Exist'),
(47, 'en', 'grp_tpc_error1', 'This Topic Is Not Approved By The Group Owner'),
(48, 'en', 'grp_cat_error', 'Please Select A Category For Your group'),
(49, 'en', 'grp_tpc_error2', 'Please enter topic to add'),
(50, 'en', 'grp_tpc_error3', 'Your Topic Requires Approval From Owner Of This Group'),
(51, 'en', 'grp_tpc_msg', 'Topic has been added'),
(52, 'en', 'grp_comment_msg', 'Comment has been added'),
(53, 'en', 'grp_vdo_msg', 'Videos Have Been Deleted'),
(54, 'en', 'grp_vdo_msg1', 'Videos Has Been Added Successfully'),
(55, 'en', 'grp_vdo_msg2', 'Videos Have Been Approved'),
(56, 'en', 'grp_mem_msg', 'Member Has Been Deleted'),
(57, 'en', 'grp_mem_msg1', 'Member Has Been Approved'),
(58, 'en', 'grp_inv_msg', 'Your Invitation Has Been Sent'),
(59, 'en', 'grp_tpc_msg1', 'Topic has been deleted'),
(60, 'en', 'grp_tpc_msg2', 'Topic Has Been Approved'),
(61, 'en', 'grp_fr_msg2', 'Group has been removed from featured list'),
(62, 'en', 'grp_inv_msg1', 'Has Invited You To Join '),
(63, 'en', 'grp_av_msg', 'Group has been activated'),
(64, 'en', 'grp_da_msg', 'Group has been deactivated'),
(65, 'en', 'grp_post_msg', 'Post Has Been Delete'),
(66, 'en', 'grp_update_msg', 'Group has been updated'),
(67, 'en', 'grp_owner_err', 'Only Owner Can Add Videos To This Group'),
(68, 'en', 'grp_owner_err1', 'You are not owner of this group'),
(69, 'en', 'grp_owner_err2', 'You Are Group Owner , You Cannot Leave Your Group'),
(70, 'en', 'grp_prvt_err1', 'This group is private, you need invitiation from its owner in order to join this group'),
(71, 'en', 'grp_rmv_msg', 'Selected Groups Have Been Removed From Your Account'),
(72, 'en', 'grp_tpc_err4', 'Sorry, Topic Doesn&#8217;t Exist'),
(73, 'en', 'grp_title_topic', 'Groups - Topic - '),
(74, 'en', 'grp_add_title', '- Add Video'),
(75, 'en', 'usr_sadmin_err', 'You Cannot Set SuperAdmin Username as Blank'),
(76, 'en', 'usr_cpass_err', 'Confirm Password Doesn&#8217;t Match'),
(77, 'en', 'usr_pass_err', 'Old password is incorrect'),
(78, 'en', 'usr_email_err', 'Please Provide A Valid Email Address'),
(79, 'en', 'usr_cpass_err1', 'Confirm password is incorrect'),
(80, 'en', 'usr_pass_err1', 'Password is Incorrect'),
(81, 'en', 'usr_cmt_err', 'You Must Login First To Comment'),
(82, 'en', 'usr_cmt_err1', 'Please Type Something In Comment Box'),
(83, 'en', 'usr_cmt_err2', 'You cannot comment on your video"'),
(84, 'en', 'usr_cmt_err3', 'You Have Already Posted a Comment on this channel.'),
(85, 'en', 'usr_cmt_err4', 'Comment Has Been Added'),
(86, 'en', 'usr_cmt_del_msg', 'Comment Has Been Deleted'),
(87, 'en', 'usr_cmt_del_err', 'An Error Occured While deleting a Comment'),
(88, 'en', 'usr_cnt_err', 'You Cannot Add Yourself as a Contact'),
(89, 'en', 'usr_cnt_err1', 'You Have Already Added This User To Your Contact List'),
(90, 'en', 'usr_sub_err', 'You are already subsctibed to %s'),
(91, 'en', 'usr_exist_err', 'User Doesnt Exist'),
(92, 'en', 'usr_ccode_err', 'You Have Entered Wrong Confirmation Code'),
(93, 'en', 'usr_exist_err1', 'Sorry, No User Exists With This Email'),
(94, 'en', 'usr_exist_err2', 'Sorry , User Doesnt Exists'),
(95, 'en', 'usr_uname_err', 'Username is empty'),
(96, 'en', 'usr_uname_err2', 'Username already exists'),
(97, 'en', 'usr_pass_err2', 'Password Is Empty'),
(98, 'en', 'usr_email_err1', 'Email is Empty'),
(99, 'en', 'usr_email_err2', 'Please Enter A Valid Email Address'),
(100, 'en', 'usr_email_err3', 'Email Address Is Already In Use'),
(101, 'en', 'usr_pcode_err', 'Postal Code Only Contains Number'),
(102, 'en', 'usr_fname_err', 'First Name Is Empty'),
(103, 'en', 'usr_lname_err', 'Last Name Is Empty'),
(104, 'en', 'usr_uname_err3', 'Username Contains Unallowed Characters'),
(105, 'en', 'usr_pass_err3', 'Passwords MisMatched'),
(106, 'en', 'usr_dob_err', 'Please Select Date Of Birth'),
(107, 'en', 'usr_ament_err', 'Sorry, you need to agree to the terms of use and privacy policy to create an account'),
(108, 'en', 'usr_reg_err', 'Sorry, Registrations Are Temporarily Not Allowed, Please Try Again Later'),
(109, 'en', 'usr_ban_err', 'User account is banned, please contact website administrator'),
(110, 'en', 'usr_login_err', 'Username Password Didn&#8217;t Match'),
(111, 'en', 'usr_sadmin_msg', 'Super Admin Has Been Updated'),
(112, 'en', 'usr_pass_msg', 'Your Password Has Been Changed'),
(113, 'en', 'usr_cnt_msg', 'This User Has Been Added To Your Contact List'),
(114, 'en', 'usr_sub_msg', 'You are now subsribed to %s'),
(115, 'en', 'usr_uname_email_msg', 'We Have Sent you an Email containing Your Usename, Please Check It'),
(116, 'en', 'usr_rpass_email_msg', 'Email Has Sent To You Please Follow the Instructions to Reset Your Password'),
(117, 'en', 'usr_pass_email_msg', 'Password has been changed successfully'),
(118, 'en', 'usr_email_msg', 'Email Settings Has Been Updated'),
(119, 'en', 'usr_del_msg', 'User has been deleted'),
(120, 'en', 'usr_dels_msg', 'Selected Users Have Been Deleted'),
(121, 'en', 'usr_ac_msg', 'User has been activated'),
(122, 'en', 'usr_dac_msg', 'User has been deactivated'),
(123, 'en', 'usr_mem_ac', 'Selected Members Have Been Activated'),
(124, 'en', 'usr_mems_ac', 'Selected Members Have Been Dectivated'),
(125, 'en', 'usr_fr_msg', 'User Has Been Made Featured Member'),
(126, 'en', 'usr_ufr_msg', 'User Has Been Unfeatured'),
(127, 'en', 'usr_frs_msg', 'Selected Users Have Been Set As Featured'),
(128, 'en', 'usr_ufrs_msg', 'Selected Users Have Been Removed From The Featured List'),
(129, 'en', 'usr_uban_msg', 'User Has Been Banned'),
(130, 'en', 'usr_uuban_msg', 'User Has Been Unbanned'),
(131, 'en', 'usr_ubans_msg', 'Selected Members Have Been Banned'),
(132, 'en', 'usr_uubans_msg', 'Selected Members Have Been Unbanned'),
(133, 'en', 'usr_pass_reset_conf', 'Password Reset Confirmation'),
(134, 'en', 'usr_dear_user', 'Dear User'),
(135, 'en', 'usr_pass_reset_msg', 'You Requested A Password Reset, Follow The Link To Reset Your Password'),
(136, 'en', 'usr_rpass_msg', 'Password Has Been Reset'),
(137, 'en', 'usr_rpass_req_msg', 'You Requested A Password Reset, Here is your new password : '),
(138, 'en', 'usr_uname_req_msg', 'You Requested to Recover Your Username, Here is you username: '),
(139, 'en', 'usr_uname_recovery', 'Username Recovery Email'),
(140, 'en', 'usr_add_succ_msg', 'User Has Been Added, Successfully'),
(141, 'en', 'usr_upd_succ_msg', 'User has been updated'),
(142, 'en', 'usr_activation_msg', 'Your account has been activated, Now you can login to your account and upload videos'),
(143, 'en', 'usr_activation_err', 'This user is already activated'),
(144, 'en', 'usr_activation_em_msg', 'We have sent you an email containing activation code, please check your mail box'),
(145, 'en', 'usr_activation_em_err', 'Email Doesn&#8217;t Exist or User With This Email already Acitvated'),
(146, 'en', 'usr_no_msg_del_err', 'No Message Was Selected To Delete'),
(147, 'en', 'usr_sel_msg_del_msg', 'Selected Messages Have Been Deleted'),
(148, 'en', 'usr_pof_upd_msg', 'Profile has been updated'),
(149, 'en', 'usr_arr_no_ans', 'no answer'),
(150, 'en', 'usr_arr_elementary', 'Elementary'),
(151, 'en', 'usr_arr_hi_school', 'High School'),
(152, 'en', 'usr_arr_some_colg', 'Some College'),
(153, 'en', 'usr_arr_assoc_deg', 'Associates Degree'),
(154, 'en', 'usr_arr_bach_deg', 'Bachelor&#8217;s Degree'),
(155, 'en', 'usr_arr_mast_deg', 'Master&#8217;s Degree'),
(156, 'en', 'usr_arr_phd', 'Ph.D.'),
(157, 'en', 'usr_arr_post_doc', 'Postdoctoral'),
(158, 'en', 'usr_arr_single', 'Single'),
(159, 'en', 'usr_arr_married', 'Married'),
(160, 'en', 'usr_arr_comitted', 'Comitted'),
(161, 'en', 'usr_arr_open_marriage', 'Open Marriage'),
(162, 'en', 'usr_arr_open_relate', 'Open Relationship'),
(163, 'en', 'title_crt_new_msg', 'Compose new message'),
(164, 'en', 'title_forgot', 'Forgot Something? Find it now !'),
(165, 'en', 'title_inbox', ' - Inbox'),
(166, 'en', 'title_sent', ' - Sent Folder'),
(167, 'en', 'title_usr_contact', '&#8217;s Contact List'),
(168, 'en', 'title_usr_fav_vids', '%&#8217;s favorite videos'),
(169, 'en', 'title_view_channel', '&#8217;s Channel'),
(170, 'en', 'title_edit_video', 'Edit Video - '),
(171, 'en', 'vdo_title_err', 'Please Enter Video Title'),
(172, 'en', 'vdo_des_err', 'Please Enter Video Description'),
(173, 'en', 'vdo_tags_err', 'Please Enter Tags For The Video'),
(174, 'en', 'vdo_cat_err', 'Please Choose Atleast 1 Category'),
(175, 'en', 'vdo_cat_err1', 'You Can Only Choose Upto 3 Categories'),
(176, 'en', 'vdo_sub_email_msg', ' and therefore this message is sent to you automatically that '),
(177, 'en', 'vdo_has_upload_nv', 'Has Uploaded New Video'),
(178, 'en', 'vdo_del_selected', 'Selected Videos Have Been Deleted'),
(179, 'en', 'vdo_cheat_msg', 'Please Dont Try To Cheat'),
(180, 'en', 'vdo_limits_warn_msg', 'Please Dont Try To Cross Your Limits'),
(181, 'en', 'vdo_cmt_del_msg', 'Comment Has Been Deleted'),
(182, 'en', 'vdo_iac_msg', 'Video Is Inactive - Please Contact Admin For Details'),
(183, 'en', 'vdo_is_in_process', 'Video Is In Process - Please Contact Administrator for further details'),
(184, 'en', 'vdo_upload_allow_err', 'Uploading Is Not Allowed By Website Owner'),
(185, 'en', 'vdo_download_allow_err', 'Video Downloading Is Not Allowed'),
(186, 'en', 'vdo_edit_owner_err', 'You Are Not Video Owner'),
(187, 'en', 'vdo_embed_code_wrong', 'Embed Code Was Wrong'),
(188, 'en', 'vdo_seconds_err', 'Wrong Value Entered For Seconds Field'),
(189, 'en', 'vdo_mins_err', 'Wrong Value Entered For Minutes Field'),
(190, 'en', 'vdo_thumb_up_err', 'Error In Uploading Thumb'),
(191, 'en', 'class_error_occured', 'Sorry, An Error Occured'),
(192, 'en', 'class_cat_del_msg', 'Category has been deleted'),
(193, 'en', 'class_vdo_del_msg', 'Video has been deleted'),
(194, 'en', 'class_vdo_fr_msg', 'Video has been to &#8220;Featured Video&#8221;'),
(195, 'en', 'class_fr_msg1', 'Video has been removed from &#8220;Featured Videos&#8221;'),
(196, 'en', 'class_vdo_act_msg', 'Video has been activated'),
(197, 'en', 'class_vdo_act_msg1', 'Vidoe has been deactivated'),
(198, 'en', 'class_vdo_update_msg', 'Video details have been updated'),
(199, 'en', 'class_comment_err', 'You Must Login First To Comment'),
(200, 'en', 'class_comment_err1', 'Please Type Something In Comment Box'),
(201, 'en', 'class_comment_err2', 'You Cannot Post Comment on  Your Own Video'),
(202, 'en', 'class_comment_err3', 'You Have Already Posted a Comment, Please Wait for the others.'),
(203, 'en', 'class_comment_err4', 'You Have Already Replied To That a Comment, Please Wait for the others.'),
(204, 'en', 'class_comment_err5', 'You Cannot Post Reply To Yourself'),
(205, 'en', 'class_comment_msg', 'Comment Has Been Added'),
(206, 'en', 'class_comment_err6', 'Please login to rate comment'),
(207, 'en', 'class_comment_err7', 'You have already rated this comment'),
(208, 'en', 'class_vdo_fav_err', 'This Video is Already Added To Your Favourites'),
(209, 'en', 'class_vdo_fav_msg', 'This Video Has Been Added To Your Favourites'),
(210, 'en', 'class_vdo_flag_err', 'You Have Already Flagged This Video'),
(211, 'en', 'class_vdo_flag_msg', 'This Video Has Been Flagged As Inappropriate'),
(212, 'en', 'class_vdo_flag_rm', 'Flag(s) Has/Have Been Removed'),
(213, 'en', 'class_send_msg_err', 'Please Enter a Username or Select any User to Send Message'),
(214, 'en', 'class_invalid_user', 'Invalid Username'),
(215, 'en', 'class_subj_err', 'Message subject was empty'),
(216, 'en', 'class_msg_err', 'Please Type Something In Message Box'),
(217, 'en', 'class_sent_you_msg', 'Sent You A Message'),
(218, 'en', 'class_sent_prvt_msg', 'Sent You A Private Message on '),
(219, 'en', 'class_click_inbox', 'Please Click here To View Your Inbox'),
(220, 'en', 'class_click_login', 'Click Here To Login'),
(221, 'en', 'class_email_notify', 'Email Notification'),
(222, 'en', 'class_msg_has_sent_to', 'Message Has Been Sent To '),
(223, 'en', 'class_inbox_del_msg', 'Message Has Been Delete From Inbox '),
(224, 'en', 'class_sent_del_msg', 'Message Has Been Delete From Sent Folder'),
(225, 'en', 'class_msg_exist_err', 'Message Doesnt Exist'),
(226, 'en', 'class_vdo_del_err', 'Video does not exist'),
(227, 'en', 'class_unsub_msg', 'You have been unsubscribed sucessfully'),
(228, 'en', 'class_sub_exist_err', 'Subscription Does Not Exist'),
(229, 'en', 'class_vdo_rm_fav_msg', 'Video Has Been Removed From Favourites'),
(230, 'en', 'class_vdo_fav_err1', 'This Video Is Not In Your Favourite List'),
(231, 'en', 'class_cont_del_msg', 'Contact Has Been Delete'),
(232, 'en', 'class_cot_err', 'Sorry, This Contact Is Not In Your Contact List'),
(233, 'en', 'class_vdo_ep_add_msg', 'Video Has Been Added To Editor&#8217;s Pick'),
(234, 'en', 'class_vdo_ep_err', 'Video Is Already In The Editor&#8217;s Pick'),
(235, 'en', 'class_vdo_ep_err1', 'You Have Already Picked 10 Videos Please Delete Alteast One to Add More'),
(236, 'en', 'class_vdo_ep_msg', 'Video Has Been Removed From Editor&#8217;s Pick'),
(237, 'en', 'class_vdo_exist_err', 'Sorry, Video Doesnt Exist'),
(238, 'en', 'class_img_gif_err', 'Please Upload Gif Image Only'),
(239, 'en', 'class_img_png_err', 'Please Upload Png Image Only'),
(240, 'en', 'class_img_jpg_err', 'Please Upload Jpg Image Only'),
(241, 'en', 'class_logo_msg', 'Logo Has Been ChangedPlease Clear Cache If You Are Not Able To See Changed Logo'),
(242, 'en', 'com_forgot_username', 'Forgot Username | Password'),
(243, 'en', 'com_join_now', 'Join Now'),
(244, 'en', 'com_my_account', 'My Account'),
(245, 'en', 'com_manage_vids', 'Manage Videos'),
(246, 'en', 'com_view_channel', 'View My Channel'),
(247, 'en', 'com_my_inbox', 'My Inbox'),
(248, 'en', 'com_welcome', 'Welcome'),
(249, 'en', 'com_top_mem', 'Top Members '),
(250, 'en', 'com_vidz', 'Videos'),
(251, 'en', 'com_sign_up_now', 'Sign Up Now !'),
(252, 'en', 'com_my_videos', 'My Videos'),
(253, 'en', 'com_my_channel', 'My Channel'),
(254, 'en', 'com_my_subs', 'My Subscriptions'),
(255, 'en', 'com_user_no_contacts', 'User Does Not Have Any Contact'),
(256, 'en', 'com_user_no_vides', 'User Does Not Have Any Favourite Video'),
(257, 'en', 'com_user_no_vid_com', 'User Has No Video Comments'),
(258, 'en', 'com_view_all_contacts', 'View All Contacts of'),
(259, 'en', 'com_view_fav_all_videos', 'View All Favourite Videos Of'),
(260, 'en', 'com_login_success_msg', 'You Have Been Successfully Logged In.'),
(261, 'en', 'com_logout_success_msg', 'You Have Been Successfully Logged Out.'),
(262, 'en', 'com_not_redirecting', 'You are now Redirecting .'),
(263, 'en', 'com_not_redirecting_msg', 'if your are not redirecting'),
(264, 'en', 'com_manage_contacts', 'Manage Contacts '),
(265, 'en', 'com_send_message', 'Send Message'),
(266, 'en', 'com_manage_fav', 'Manage Favorites '),
(267, 'en', 'com_manage_subs', 'Manage Subscriptions'),
(268, 'en', 'com_subscribe_to', 'Subscribe to %s&#8217;s channel'),
(269, 'en', 'com_total_subs', 'Total Subscribtions'),
(270, 'en', 'com_total_vids', 'Total Videos'),
(271, 'en', 'com_date_subscribed', 'Date Subscribed'),
(272, 'en', 'com_search_results', 'Search Results'),
(273, 'en', 'com_advance_results', 'Advance Search'),
(274, 'en', 'com_search_results_in', 'Search Results In'),
(275, 'en', 'videos_being_watched', 'Recently Viewed...'),
(276, 'en', 'latest_added_videos', 'Recent Additions'),
(277, 'en', 'most_viewed', 'Most Viewed'),
(278, 'en', 'recently_added', 'Recently Added'),
(279, 'en', 'featured', 'Featured'),
(280, 'en', 'highest_rated', 'Highest Rated'),
(281, 'en', 'most_discussed', 'Most Discussed'),
(282, 'en', 'style_change', 'Style Change'),
(283, 'en', 'rss_feed_latest_title', 'RSS Feed for Most Recent Videos'),
(284, 'en', 'rss_feed_featured_title', 'RSS Feed for Featured Videos'),
(285, 'en', 'rss_feed_most_viewed_title', 'RSS Feed for Most Popular Videos'),
(286, 'en', 'lang_folder', 'en'),
(287, 'en', 'reg_closed', 'Registration Closed'),
(288, 'en', 'reg_for', 'Registration for'),
(289, 'en', 'is_currently_closed', 'is currently closed'),
(290, 'en', 'about_us', 'About Us'),
(291, 'en', 'account', 'Account'),
(292, 'en', 'added', 'Added'),
(293, 'en', 'advertisements', 'Advertisements'),
(294, 'en', 'all', 'All'),
(295, 'en', 'active', 'Active'),
(296, 'en', 'activate', 'Activate'),
(297, 'en', 'age', 'Age'),
(298, 'en', 'approve', 'Approve'),
(299, 'en', 'approved', 'Approved'),
(300, 'en', 'approval', 'Approval'),
(301, 'en', 'books', 'Books'),
(302, 'en', 'browse', 'Browse'),
(303, 'en', 'by', 'by'),
(304, 'en', 'cancel', 'Cancel'),
(305, 'en', 'categories', 'Categories'),
(306, 'en', 'category', 'Category'),
(307, 'en', 'channels', 'channels'),
(308, 'en', 'check_all', 'Check All'),
(309, 'en', 'click_here', 'Click Here'),
(310, 'en', 'comments', 'Comments'),
(311, 'en', 'community', 'Community'),
(312, 'en', 'companies', 'Companies'),
(313, 'en', 'contacts', 'Contacts'),
(314, 'en', 'contact_us', 'Contact Us'),
(315, 'en', 'country', 'Country'),
(316, 'en', 'created', 'Created'),
(317, 'en', 'date', 'Date'),
(318, 'en', 'date_added', 'Date Added'),
(319, 'en', 'date_joined', 'Date Joined'),
(320, 'en', 'dear', 'Dear'),
(321, 'en', 'delete', 'Delete'),
(322, 'en', 'delete_selected', 'Delete Selected'),
(323, 'en', 'des_title', 'Description:'),
(324, 'en', 'duration', 'Duration'),
(325, 'en', 'education', 'Education'),
(326, 'en', 'email', 'email'),
(327, 'en', 'embed', 'Embed'),
(328, 'en', 'embed_code', 'Embed Code'),
(329, 'en', 'favourite', 'Favorite'),
(330, 'en', 'favourited', 'Favorited'),
(331, 'en', 'favourites', 'Favorites'),
(332, 'en', 'female', 'Female'),
(333, 'en', 'filter', 'Filter'),
(334, 'en', 'forgot', 'Forgot'),
(335, 'en', 'friends', 'Friends'),
(336, 'en', 'from', 'From'),
(337, 'en', 'gender', 'Gender'),
(338, 'en', 'groups', 'Groups'),
(339, 'en', 'hello', 'Hello'),
(340, 'en', 'help', 'Help'),
(341, 'en', 'hi', 'Hi'),
(342, 'en', 'hobbies', 'Hobbies'),
(343, 'en', 'Home', 'Home'),
(344, 'en', 'inbox', 'inbox'),
(345, 'en', 'interests', 'Interests'),
(346, 'en', 'join_now', 'Join Now'),
(347, 'en', 'joined', 'Joined'),
(348, 'en', 'join', 'Join'),
(349, 'en', 'keywords', 'Keywords'),
(350, 'en', 'latest', 'Latest'),
(351, 'en', 'leave', 'Leave'),
(352, 'en', 'location', 'Location'),
(353, 'en', 'login', 'Login'),
(354, 'en', 'logout', 'Logout'),
(355, 'en', 'male', 'Male'),
(356, 'en', 'members', 'Members'),
(357, 'en', 'messages', 'Messages'),
(358, 'en', 'message', 'Message'),
(359, 'en', 'minutes', 'minutes'),
(360, 'en', 'most_members', 'Most Members'),
(361, 'en', 'most_recent', 'Most Recent'),
(362, 'en', 'most_videos', 'Most Videos'),
(363, 'en', 'music', 'Music'),
(364, 'en', 'my_account', 'My Account'),
(365, 'en', 'next', 'Next'),
(366, 'en', 'no', 'No'),
(367, 'en', 'no_user_exists', 'No User Exists'),
(368, 'en', 'no_video_exists', 'No Video Exists'),
(369, 'en', 'occupations', 'Occupations'),
(370, 'en', 'optional', 'optional'),
(371, 'en', 'owner', 'Owner'),
(372, 'en', 'password', 'password'),
(373, 'en', 'please', 'Please'),
(374, 'en', 'privacy', 'Privacy'),
(375, 'en', 'privacy_policy', 'Privacy Policy'),
(376, 'en', 'random', 'Random'),
(377, 'en', 'rate', 'Rate'),
(378, 'en', 'request', 'Request'),
(379, 'en', 'related', 'Related'),
(380, 'en', 'reply', 'Reply'),
(381, 'en', 'results', 'Results'),
(382, 'en', 'relationship', 'Relationship'),
(383, 'en', 'seconds', 'seconds'),
(384, 'en', 'select', 'Select'),
(385, 'en', 'send', 'Send'),
(386, 'en', 'sent', 'Sent'),
(387, 'en', 'signup', 'Signup'),
(388, 'en', 'subject', 'Subject'),
(389, 'en', 'tags', 'Tags'),
(390, 'en', 'times', 'Times'),
(391, 'en', 'to', 'To'),
(392, 'en', 'type', 'Type'),
(393, 'en', 'update', 'Update'),
(394, 'en', 'upload', 'Upload'),
(395, 'en', 'url', 'Url'),
(396, 'en', 'verification', 'Verification'),
(397, 'en', 'videos', 'Videos'),
(398, 'en', 'viewing', 'Viewing'),
(399, 'en', 'welcome', 'Welcome'),
(400, 'en', 'website', 'Website'),
(401, 'en', 'yes', 'Yes'),
(402, 'en', 'of', 'of'),
(403, 'en', 'on', 'on'),
(404, 'en', 'previous', 'Previous'),
(405, 'en', 'rating', 'Rating'),
(406, 'en', 'ratings', 'Ratings'),
(407, 'en', 'remote_upload', 'Remote Upload'),
(408, 'en', 'remove', 'Remove'),
(409, 'en', 'search', 'Search'),
(410, 'en', 'services', 'Services'),
(411, 'en', 'show_all', 'Show All'),
(412, 'en', 'signupup', 'Sign Up'),
(413, 'en', 'sort_by', 'Sort'),
(414, 'en', 'subscriptions', 'Subscriptions'),
(415, 'en', 'subscribers', 'Subscribers'),
(416, 'en', 'tag_title', 'Tags'),
(417, 'en', 'time', 'time'),
(418, 'en', 'top', 'Top'),
(419, 'en', 'tos_title', 'Terms of Use'),
(420, 'en', 'username', 'username'),
(421, 'en', 'views', 'Views'),
(422, 'en', 'proccession_wait', 'Processing, Please Wait'),
(423, 'en', 'mostly_viewed', 'Most Viewed'),
(424, 'en', 'most_comments', 'Most Comments'),
(425, 'en', 'group', 'Group'),
(426, 'en', 'not_logged_in', 'You are not logged in or you do not have permission to access this page. This could be due to one of several reasons:'),
(427, 'en', 'fill_auth_form', 'You are not logged in. Fill in the form below and try again.'),
(428, 'en', 'insufficient_privileges', 'You may not have sufficient privileges to access this page.'),
(429, 'en', 'admin_disabled_you', 'The site administrator may have disabled your account, or it may be awaiting activation.'),
(430, 'en', 'Recover_Password', 'Recover Password'),
(431, 'en', 'Submit', 'Submit'),
(432, 'en', 'Reset_Fields', 'Reset Fields'),
(433, 'en', 'admin_reg_req', 'The administrator may have required you to register before you can view this page.'),
(434, 'en', 'lang_change', 'Language Change'),
(435, 'en', 'lang_changed', 'Your language has been changed'),
(436, 'en', 'lang_choice', 'Language'),
(437, 'en', 'if_not_redir', 'Click here to continue if you are not automatically redirected.'),
(438, 'en', 'style_changed', 'Your style has been changed'),
(439, 'en', 'style_choice', 'Style'),
(440, 'en', 'vdo_edit_vdo', 'Edit Video'),
(441, 'en', 'vdo_stills', 'Video Stills'),
(442, 'en', 'vdo_watch_video', 'Watch Video'),
(443, 'en', 'vdo_video_details', 'Video Details'),
(444, 'en', 'vdo_title', 'Title'),
(445, 'en', 'vdo_desc', 'Description'),
(446, 'en', 'vdo_cat', 'Video Category'),
(447, 'en', 'vdo_cat_msg', 'You May Select Upto %s Categories'),
(448, 'en', 'vdo_tags_msg', 'Tags are separated by commas ie Arslan Hassan, Awsome, ClipBucket'),
(449, 'en', 'vdo_br_opt', 'Broadcast Options'),
(450, 'en', 'vdo_br_opt1', 'Public Share your video with the Everyone! (Recommended)'),
(451, 'en', 'vdo_br_opt2', 'Private Viewable by you and your friends only.'),
(452, 'en', 'vdo_date_loc', 'Date And Location'),
(453, 'en', 'vdo_date_rec', 'Date Recorded'),
(454, 'en', 'vdo_for_date', 'format MM / DD / YYYY '),
(455, 'en', 'vdo_add_eg', 'e.g London Greenland, Sialkot Mubarak Pura'),
(456, 'en', 'vdo_share_opt', 'Sharing Options'),
(457, 'en', 'vdo_allow_comm', 'Allow Comments '),
(458, 'en', 'vdo_dallow_comm', 'Do Not Allow Comments'),
(459, 'en', 'vdo_comm_vote', 'Comments Voting'),
(460, 'en', 'vdo_allow_com_vote', 'Allow Comments Voting '),
(461, 'en', 'vdo_dallow_com_vote', 'Do Not Allow Comments Voting '),
(462, 'en', 'vdo_allow_rating', 'Yes, Allow Rating on this video'),
(463, 'en', 'vdo_dallow_ratig', 'No, Do Not Allow Rating on this video'),
(464, 'en', 'vdo_embedding', 'Embedding'),
(465, 'en', 'vdo_embed_opt1', 'Yes, People can play this video on other websites'),
(466, 'en', 'vdo_embed_opt2', 'No, People cannot play this video on other websites'),
(467, 'en', 'vdo_update_title', 'Update'),
(468, 'en', 'vdo_inactive_msg', 'Your Account is Inactive Please Activate it to Upload Videos, To Activate your account Please'),
(469, 'en', 'vdo_click_here', 'Click Here'),
(470, 'en', 'vdo_continue_upload', 'Continue to Upload'),
(471, 'en', 'vdo_upload_step1', 'Video Upload'),
(472, 'en', 'vdo_upload_step2', 'Video Step %s/2'),
(473, 'en', 'vdo_upload_step3', '(Step 2/2)'),
(474, 'en', 'vdo_select_vdo', 'Select a video to upload.'),
(475, 'en', 'vdo_enter_remote_url', 'Enter Url Of The Video.'),
(476, 'en', 'vdo_enter_embed_code_msg', 'Enter Embed Video Code from other websites ie Youtube or Metacafe.'),
(477, 'en', 'vdo_enter_embed_code', 'Enter Embed Code'),
(478, 'en', 'vdo_enter_druation', 'Enter Duration'),
(479, 'en', 'vdo_select_vdo_thumb', 'Select Video Thumb'),
(480, 'en', 'vdo_having_trouble', 'Having Trouble?'),
(481, 'en', 'vdo_if_having_problem', 'if you having problem with the uploader'),
(482, 'en', 'vdo_clic_to_manage_all', 'Click Here To Manage All Videos'),
(483, 'en', 'vdo_manage_vdeos', 'Manage Videos '),
(484, 'en', 'vdo_status', 'Status'),
(485, 'en', 'vdo_rawfile', 'RawFile'),
(486, 'en', 'vdo_video_upload_complete', 'Video Upload - Upload Complete'),
(487, 'en', 'vdo_thanks_you_upload_complete_1', 'Thank you! Your upload is complete'),
(488, 'en', 'vdo_thanks_you_upload_complete_2', 'This video will be available in'),
(489, 'en', 'vdo_after_it_has_process', 'after it has finished processing.'),
(490, 'en', 'vdo_embed_this_video_on_web', 'Embed this video on your website.'),
(491, 'en', 'vdo_copy_and_paste_the_code', 'Copy and paste the code below to embed this video.'),
(492, 'en', 'vdo_upload_another_video', 'Upload Another Video'),
(493, 'en', 'vdo_goto_my_videos', 'Goto My Videos'),
(494, 'en', 'vdo_sperate_emails_by', 'seperate emails by commas'),
(495, 'en', 'vdo_personal_msg', 'Personal Message'),
(496, 'en', 'vdo_related_tags', 'Related Tags'),
(497, 'en', 'vdo_reply_to_this', 'Reply To This '),
(498, 'en', 'vdo_add_reply', 'Add Reply'),
(499, 'en', 'vdo_share_video', 'Share Video'),
(500, 'en', 'vdo_about_this_video', 'About This Video'),
(501, 'en', 'vdo_post_to_a_services', 'Post to an Aggregating Service'),
(502, 'en', 'vdo_commentary', 'Commentary'),
(503, 'en', 'vdo_post_a_comment', 'Post A Comment'),
(504, 'en', 'grp_add_vdo_msg', 'Add Videos To Group '),
(505, 'en', 'grp_no_vdo_msg', 'You Don&#8217;t Have Any Video'),
(506, 'en', 'grp_add_to', 'Add To Group'),
(507, 'en', 'grp_add_vdos', 'Add Videos'),
(508, 'en', 'grp_name_title', 'Group name'),
(509, 'en', 'grp_tag_title', 'Tags:'),
(510, 'en', 'grp_des_title', 'Description:'),
(511, 'en', 'grp_tags_msg', 'Enter one or more tags, separated by spaces.'),
(512, 'en', 'grp_tags_msg1', 'Enter one or more tags, separated by spaces. Tags  are keywords used to describe your group so it can be easily found by  other users. For example, if you have a group for surfers, you might  tag it: surfing, beach, waves.'),
(513, 'en', 'grp_url_title', 'Choose a unique group name URL:'),
(514, 'en', 'grp_url_msg', 'Enter 3-18 characters with no spaces (such as &#8220;skateboarding skates&#8221;), that will become part of your group&#8217;s web address. Please note, the group name URL you pick is permanent and can&#8217;t be changed.'),
(515, 'en', 'grp_cat_tile', 'Group Category:'),
(516, 'en', 'grp_vdo_uploads', 'Video Uploads:'),
(517, 'en', 'grp_forum_posting', 'Forums Posting:'),
(518, 'en', 'grp_join_opt1', 'Public, anyone can join.'),
(519, 'en', 'grp_join_opt2', 'Protected, requires founder approval to join.'),
(520, 'en', 'grp_join_opt3', 'Private, by founder invite only, only members can view group details.'),
(521, 'en', 'grp_vdo_opt1', 'Post videos immediately.'),
(522, 'en', 'grp_vdo_opt2', 'Founder approval required before video is available.'),
(523, 'en', 'grp_vdo_opt3', 'Only Founder can add new videos.'),
(524, 'en', 'grp_post_opt1', 'Post topics immediately.'),
(525, 'en', 'grp_post_opt2', 'Founder approval required before topic is available.'),
(526, 'en', 'grp_post_opt3', 'Only Founder can create a new topic.'),
(527, 'en', 'grp_crt_grp', 'Create Group'),
(528, 'en', 'grp_thumb_title', 'Group Thumb'),
(529, 'en', 'grp_upl_thumb', 'Upload Group Thumb'),
(530, 'en', 'grp_must_be', 'Must Be'),
(531, 'en', 'grp_90x90', '90  x 90 Ratio Will Give Best quality'),
(532, 'en', 'grp_thumb_warn', 'Do Not Upload Vulgur or Copyrighted Material'),
(533, 'en', 'grp_del_confirm', 'Are You Sure You Want To Delete This Group'),
(534, 'en', 'grp_del_success', 'You Have Successfully Deleted'),
(535, 'en', 'grp_click_go_grps', 'Click Here To Go To Groups'),
(536, 'en', 'grp_edit_grp_title', 'Edit Group'),
(537, 'en', 'grp_manage_vdos', 'Manage Videos'),
(538, 'en', 'grp_manage_mems', 'Manage Members'),
(539, 'en', 'grp_del_group_title', 'Delete Group'),
(540, 'en', 'grp_add_vdos_title', 'Add Videos'),
(541, 'en', 'grp_join_grp_title', 'Join Group'),
(542, 'en', 'grp_leave_group_title', 'Leave Group'),
(543, 'en', 'grp_invite_grp_title', 'Invite Members'),
(544, 'en', 'grp_view_mems', 'View Members'),
(545, 'en', 'grp_view_vdos', 'View Videos'),
(546, 'en', 'grp_create_grp_title', 'Create A New Group'),
(547, 'en', 'grp_most_members', 'Most Members'),
(548, 'en', 'grp_most_discussed', 'Most Discussed'),
(549, 'en', 'grp_invite_msg', 'Invite Users To This Group'),
(550, 'en', 'grp_invite_msg1', 'Has Invited You To Join'),
(551, 'en', 'grp_invite_msg2', 'Enter Emails or Usernames (seperate by commas)'),
(552, 'en', 'grp_url_title1', 'Group url'),
(553, 'en', 'grp_invite_msg3', 'Send Invitation'),
(554, 'en', 'grp_join_confirm_msg', 'Are You Sure You Want To Join This Group'),
(555, 'en', 'grp_join_msg_succ', 'You have successfully joined group'),
(556, 'en', 'grp_click_here_to_go', 'Click Here To Go To'),
(557, 'en', 'grp_leave_confirm', 'Are You Sure You Want To Leave This Group'),
(558, 'en', 'grp_leave_succ_msg', 'You have left the group'),
(559, 'en', 'grp_manage_members_title', 'Manage Members '),
(560, 'en', 'grp_for_approval', 'For Approval'),
(561, 'en', 'grp_rm_videos', 'Remove Videos'),
(562, 'en', 'grp_rm_mems', 'Remove Members'),
(563, 'en', 'grp_groups_title', 'Manage Groups'),
(564, 'en', 'grp_remove_group', 'Remove Group'),
(565, 'en', 'grp_bo_grp_found', 'No Group Found'),
(566, 'en', 'grp_joined_groups', 'Joined Groups'),
(567, 'en', 'grp_owned_groups', 'Owned Groups'),
(568, 'en', 'grp_edit_this_grp', 'Edit This Group'),
(569, 'en', 'grp_topics_title', 'Topics'),
(570, 'en', 'grp_topic_title', 'Topic'),
(571, 'en', 'grp_posts_title', 'Posts'),
(572, 'en', 'grp_discus_title', 'Discussions'),
(573, 'en', 'grp_author_title', 'Author'),
(574, 'en', 'grp_replies_title', 'Replies'),
(575, 'en', 'grp_last_post_title', 'Last Post '),
(576, 'en', 'grp_viewl_all_videos', 'View All Videos of This Group'),
(577, 'en', 'grp_add_new_topic', 'Add New Topic'),
(578, 'en', 'grp_attach_video', 'Attach Video '),
(579, 'en', 'grp_add_topic', 'Add Topic'),
(580, 'en', 'grp_please_login', 'Please login to post topics'),
(581, 'en', 'grp_please_join', 'Please Join This Group To Post Topics'),
(582, 'en', 'grp_inactive_account', 'Your Account Is Inactive And Required Activation From Group Owner'),
(583, 'en', 'grp_about_this_grp', 'About This Group '),
(584, 'en', 'grp_no_vdo_err', 'This Group Has No Vidoes'),
(585, 'en', 'grp_posted_by', 'Posted by'),
(586, 'en', 'grp_add_new_comment', 'Add New Comment'),
(587, 'en', 'grp_add_comment', 'Add Comment'),
(588, 'en', 'grp_pls_login_comment', 'Please Login To Post Comments'),
(589, 'en', 'grp_pls_join_comment', 'Please Join This Group To Post Comments'),
(590, 'en', 'usr_activation_title', 'User Activation'),
(591, 'en', 'usr_actiavation_msg', 'Enter Your Username and Activation Code that has been sent to your email.'),
(592, 'en', 'usr_actiavation_msg1', 'Request Activation Code'),
(593, 'en', 'usr_activation_code_tl', 'Activation Code'),
(594, 'en', 'usr_compose_msg', 'Compose Message'),
(595, 'en', 'usr_inbox_title', 'Inbox'),
(596, 'en', 'usr_sent_title', 'Sent'),
(597, 'en', 'usr_to_title', 'To: (Enter Username)'),
(598, 'en', 'usr_or_select_frm_list', 'or select from contact list'),
(599, 'en', 'usr_attach_video', 'Attach Video'),
(600, 'en', 'user_attached_video', 'Attached Video'),
(601, 'en', 'usr_send_message', 'Send Message'),
(602, 'en', 'user_no_message', 'No Message'),
(603, 'en', 'user_delete_message_msg', 'Delete This Message'),
(604, 'en', 'user_forgot_message', 'Forgot password'),
(605, 'en', 'user_forgot_message_2', 'Dont Worry, recover it now'),
(606, 'en', 'user_pass_reset_msg', 'Password Reset'),
(607, 'en', 'user_pass_forgot_msg', 'if you have forgot your password, please enter you username and verification code in the box, and password reset instructions will be sent to your mail box.'),
(608, 'en', 'user_veri_code', 'Verification Code'),
(609, 'en', 'user_reocover_user', 'Recover Username'),
(610, 'en', 'user_user_forgot_msg', 'Forgot Username?'),
(611, 'en', 'user_recover', 'Recover'),
(612, 'en', 'user_reset', 'Reset'),
(613, 'en', 'user_inactive_msg', 'Your Account is Inactive Please Activate it , To Activate your account Please'),
(614, 'en', 'user_dashboard', 'Dash Board'),
(615, 'en', 'user_manage_prof_chnnl', 'Manage Profile &amp; Channel'),
(616, 'en', 'user_manage_friends', 'Manage Friends &amp; Contacts'),
(617, 'en', 'user_prof_channel', 'Profile/Channel'),
(618, 'en', 'user_message_box', 'Message Box'),
(619, 'en', 'user_new_messages', 'New Messages'),
(620, 'en', 'user_goto_inbox', 'Goto Inbox'),
(621, 'en', 'user_goto_sentbox', 'Goto Sent Box'),
(622, 'en', 'user_compose_new', 'Compose New Messages'),
(623, 'en', 'user_total_subs_users', 'Total Subscribed Users'),
(624, 'en', 'user_you_have', 'You Have'),
(625, 'en', 'user_fav_videos', 'Favorite Videos'),
(626, 'en', 'user_your_vids_watched', 'Your Videos Watched'),
(627, 'en', 'user_times', 'Times'),
(628, 'en', 'user_you_have_watched', 'You Have Watched'),
(629, 'en', 'user_channel_profiles', 'Channel &amp; Profile'),
(630, 'en', 'user_channel_views', 'Channel Views'),
(631, 'en', 'user_channel_comm', 'Channel Comments '),
(632, 'en', 'user_manage_prof', 'Manage Profile / Channel'),
(633, 'en', 'user_you_created', 'You Have Created'),
(634, 'en', 'user_you_joined', 'You Have Joined'),
(635, 'en', 'user_create_group', 'Create New Group'),
(636, 'en', 'user_manage_my_account', 'Manage My Account '),
(637, 'en', 'user_manage_my_videos', 'Manage My Videos'),
(638, 'en', 'user_manage_my_channel', 'Manage My Channel'),
(639, 'en', 'user_sent_box', 'My sent items'),
(640, 'en', 'user_manage_channel', 'Manage Channel'),
(641, 'en', 'user_manage_my_contacts', 'Manage My Contacts'),
(642, 'en', 'user_manage_contacts', 'Manage Contacts'),
(643, 'en', 'user_manage_favourites', 'Manage Favourite Videos'),
(644, 'en', 'user_mem_login', 'Members Login'),
(645, 'en', 'user_already_have', 'Please Login Here if You Already have an account of'),
(646, 'en', 'user_forgot_username', 'Forgot Username'),
(647, 'en', 'user_forgot_password', 'Forgot Password'),
(648, 'en', 'user_create_your', 'Create Your '),
(649, 'en', 'user_all_fields_req', 'All Fields Are Required'),
(650, 'en', 'user_valid_email_addr', 'Valid Email Address'),
(651, 'en', 'user_allowed_format', 'Letters A-Z or a-z , Numbers 0-9 and Underscores _'),
(652, 'en', 'user_confirm_pass', 'Confirm Password'),
(653, 'en', 'user_reg_msg_0', 'Register as '),
(654, 'en', 'user_reg_msg_1', 'member, its free and easy just fill out the form below'),
(655, 'en', 'user_date_of_birth', 'Date Of Birth'),
(656, 'en', 'user_enter_text_as_img', 'Enter Text As Seen In The Image'),
(657, 'en', 'user_refresh_img', 'Refresh Image'),
(658, 'en', 'user_i_agree_to_the', 'I Agree to  <a href="%s" target="_blank">Terms of Service</a> and <a href="%s" target="_blank" >Privacy Policy'),
(659, 'en', 'user_thanks_for_reg', 'Thank You For Registering on '),
(660, 'en', 'user_email_has_sent', 'An email has been sent to your inbox containing Your Account'),
(661, 'en', 'user_and_activation', '&amp; Activation'),
(662, 'en', 'user_details_you_now', 'Details. You may now do the following things on our network'),
(663, 'en', 'user_upload_share_vds', 'Upload, Share Videos'),
(664, 'en', 'user_make_friends', 'Make Friends'),
(665, 'en', 'user_send_messages', 'Send Messages'),
(666, 'en', 'user_grow_your_network', 'Grow Your Networks by Inviting more Friends'),
(667, 'en', 'user_rate_comment', 'Rate and Comment Videos'),
(668, 'en', 'user_make_customize', 'Make and Customize Your Channel'),
(669, 'en', 'user_to_upload_vid', 'To Upload Video, You Need to Activate your account first, activation details has been sent to your email account, it may take sometimes to reach your inbox'),
(670, 'en', 'user_click_to_login', 'Click here To Login To Your Account'),
(671, 'en', 'user_view_my_channel', 'View My Channel'),
(672, 'en', 'user_change_pass', 'Change Password'),
(673, 'en', 'user_email_settings', 'Email Settings'),
(674, 'en', 'user_profile_settings', 'Profile Settings'),
(675, 'en', 'user_usr_prof_chnl_edit', 'User Profile &amp; Channel Edit'),
(676, 'en', 'user_personal_info', 'Personal Information'),
(677, 'en', 'user_fname', 'First Name'),
(678, 'en', 'user_lname', 'Last Name'),
(679, 'en', 'user_gender', 'Gender'),
(680, 'en', 'user_relat_status', 'Relationship Status'),
(681, 'en', 'user_display_age', 'Display Age'),
(682, 'en', 'user_about_me', 'About Me'),
(683, 'en', 'user_website_url', 'Website Url'),
(684, 'en', 'user_eg_website', 'e.g www.cafepixie.com'),
(685, 'en', 'user_prof_info', 'Professional Information'),
(686, 'en', 'user_education', 'Education'),
(687, 'en', 'user_school_colleges', 'Schools / Colleges'),
(688, 'en', 'user_occupations', 'Occupations'),
(689, 'en', 'user_companies', 'Companies'),
(690, 'en', 'user_sperate_by_commas', 'seperate with commas'),
(691, 'en', 'user_interests_hobbies', 'Interests and Hobbies'),
(692, 'en', 'user_fav_movs_shows', 'Favorite movies &amp; shows'),
(693, 'en', 'user_fav_music', 'Favorite music'),
(694, 'en', 'user_fav_books', 'Favorite books'),
(695, 'en', 'user_user_avatar', 'User Avatar'),
(696, 'en', 'user_upload_avatar', 'Upload Avatar'),
(697, 'en', 'user_channel_info', 'Channel Info'),
(698, 'en', 'user_channel_title', 'Channel Title'),
(699, 'en', 'user_channel_description', 'Channel Description'),
(700, 'en', 'user_channel_permission', 'Channel Permissions'),
(701, 'en', 'user_allow_comments_msg', 'users can comments'),
(702, 'en', 'user_dallow_comments_msg', 'users cannot comments'),
(703, 'en', 'user_allow_rating', 'Allow Rating'),
(704, 'en', 'user_dallow_rating', 'Do Not Allow Rating'),
(705, 'en', 'user_allow_rating_msg1', 'users can rate'),
(706, 'en', 'user_dallow_rating_msg1', 'users cannot rate'),
(707, 'en', 'user_channel_feature_vid', 'Channel Featured Video'),
(708, 'en', 'user_select_vid_for_fr', 'Select Video To set as Featured'),
(709, 'en', 'user_chane_channel_bg', 'Change Channel Background'),
(710, 'en', 'user_remove_bg', 'Remove Background'),
(711, 'en', 'user_currently_you_d_have_pic', 'Currently You Don&#8217;t Have Background Picture'),
(712, 'en', 'user_change_email', 'Change Email'),
(713, 'en', 'user_email_address', 'Email Address'),
(714, 'en', 'user_new_email', 'New Email'),
(715, 'en', 'user_notify_me', 'Notify Me When User Sends Me A Message'),
(716, 'en', 'user_old_pass', 'Old Password'),
(717, 'en', 'user_new_pass', 'New Password'),
(718, 'en', 'user_c_new_pass', 'Confirm New Password'),
(719, 'en', 'user_doesnt_exist', 'User Doesn&#8217;t Exist'),
(720, 'en', 'user_do_not_have_contact', 'User Does Not Have Any Contact'),
(721, 'en', 'user_no_fav_video_exist', 'User Does Not Have Favourite Video'),
(722, 'en', 'user_have_no_vide', 'User has no videos'),
(723, 'en', 'user_s_channel', '%s&#8217;s Channel '),
(724, 'en', 'user_last_login', 'Last Login'),
(725, 'en', 'user_send_message', 'Send Message'),
(726, 'en', 'user_add_contact', 'Add Contact'),
(727, 'en', 'user_dob', 'Dob'),
(728, 'en', 'user_movies_shows', 'Movies &amp; Shows'),
(729, 'en', 'user_add_comment', 'Add Comment '),
(730, 'en', 'user_view_all_comments', 'View All Comments'),
(731, 'en', 'user_no_fr_video', 'User Has Not Selected Any Video To Set As Featured'),
(732, 'en', 'user_view_all_video_of', 'View All Videos of '),
(733, 'en', 'menu_home', 'Home'),
(734, 'en', 'menu_videos', 'Videos'),
(735, 'en', 'menu_upload', 'Upload'),
(736, 'en', 'menu_signup', 'SignUp'),
(737, 'en', 'menu_account', 'Account'),
(738, 'en', 'menu_groups', 'Groups'),
(739, 'en', 'menu_channels', 'Channels'),
(740, 'en', 'menu_community', 'Community'),
(741, 'en', 'menu_inbox', 'Inbox'),
(742, 'en', 'vdo_cat_err2', 'You cannot select more than %d categories'),
(743, 'en', 'user_subscribe_message', 'Hello %subscriber%\nYou Have Subscribed To %user% and therefore this message is sent to you automatically that %user% Has Uploaded New Video\n\n%website_title%'),
(744, 'en', 'user_subscribe_subject', '%user% has uploaded new video'),
(745, 'en', 'you_already_logged', 'You are already logged in'),
(746, 'en', 'you_not_logged_in', 'You are not logged in'),
(747, 'en', 'invalid_user', 'Invalid User'),
(748, 'en', 'vdo_cat_err3', 'Please select atleast 1 category'),
(749, 'en', 'embed_code_invalid_err', 'Invalid video embed code'),
(750, 'en', 'invalid_duration', 'Invalid duration'),
(751, 'en', 'vid_thumb_changed', 'Video default thumb has been changed'),
(752, 'en', 'vid_thumb_change_err', 'Video thumbnail was not found'),
(753, 'en', 'upload_vid_thumbs_msg', 'All video thumbs have been uploaded'),
(754, 'en', 'video_thumb_delete_msg', 'Video thumb has been deleted'),
(755, 'en', 'video_thumb_delete_err', 'Could not delete video thumb'),
(756, 'en', 'no_comment_del_perm', 'You dont have permission to delete this comment'),
(757, 'en', 'my_text_context', 'My test context'),
(758, 'en', 'user_contains_disallow_err', 'Username contains disallowed characters'),
(759, 'en', 'add_cat_erro', 'Category already exists'),
(760, 'en', 'add_cat_no_name_err', 'Please enter name for category'),
(761, 'en', 'cat_default_err', 'Default cannot be deleted, please choose other category as &#8220;default&#8221; and then delete this'),
(762, 'en', 'pic_upload_vali_err', 'Please upload valid JPG, GIF or PNG image'),
(763, 'en', 'cat_dir_make_err', 'Unable to make category thumb directory'),
(764, 'en', 'cat_set_default_ok', 'Category has been set as default'),
(765, 'en', 'vid_thumb_removed_msg', 'Video thumbs have been removed'),
(766, 'en', 'vid_files_removed_msg', 'Video files have been removed'),
(767, 'en', 'vid_log_delete_msg', 'Video log has been deleted'),
(768, 'en', 'vdo_multi_del_erro', 'Videos has have been deleted'),
(769, 'en', 'add_fav_message', 'This %s has been added to your favorites'),
(770, 'en', 'obj_not_exists', '%s does not exist'),
(771, 'en', 'already_fav_message', 'This %s is already added to your favorites'),
(772, 'en', 'obj_report_msg', 'this %s has been reported'),
(773, 'en', 'obj_report_err', 'You have already reported this %s'),
(774, 'en', 'user_no_exist_wid_username', '&#8216;%s&#8217; does not exist'),
(775, 'en', 'share_video_no_user_err', 'Please enter usernames or emails to send this %s'),
(776, 'en', 'uploaded', 'Uploaded'),
(777, 'en', 'today', 'Today'),
(778, 'en', 'yesterday', 'Yesterday'),
(779, 'en', 'thisweek', 'This Week'),
(780, 'en', 'lastweek', 'Last Week'),
(781, 'en', 'thismonth', 'This Month'),
(782, 'en', 'lastmonth', 'Last Month'),
(783, 'en', 'thisyear', 'This Year'),
(784, 'en', 'lastyear', 'Last Year'),
(785, 'en', 'favorites', 'Favorites'),
(786, 'en', 'alltime', 'All Time'),
(787, 'en', 'insufficient_privileges_loggin', 'You cannot access this page Click Here to Login or Register'),
(788, 'en', 'profile_title', 'Profile Title'),
(789, 'en', 'show_dob', 'Show Date of birth'),
(790, 'en', 'profile_tags', 'Profile Tags'),
(791, 'en', 'profile_desc', 'Profile description'),
(792, 'en', 'online_status', 'User status'),
(793, 'en', 'show_profile', 'Show profile'),
(794, 'en', 'allow_ratings', 'Allow ratings on profile'),
(795, 'en', 'postal_code', 'Postal code'),
(796, 'en', 'temp_file_load_err', 'Unable to load tempalte file &#8216;%s&#8217; in directory &#8216;%s&#8217;'),
(797, 'en', 'no_date_provided', 'No date provided'),
(798, 'en', 'second', 'second'),
(799, 'en', 'minute', 'minute'),
(800, 'en', 'bad_date', 'Never'),
(801, 'en', 'users_videos', '%s&#8217;s videos'),
(802, 'en', 'please_login_subscribe', 'Please login to subsribe %s'),
(803, 'en', 'users_subscribers', '%s&#8217;s subscribers'),
(804, 'en', 'user_no_subscribers', '%s has no subsribers'),
(805, 'en', 'user_subscriptions', '%s&#8217;s subscriptions'),
(806, 'en', 'user_no_subscriptions', '%s has no subscriptions'),
(807, 'en', 'usr_avatar_bg_update', 'User avatar and background have been updated'),
(808, 'en', 'user_email_confirm_email_err', 'Confirm email mismatched'),
(809, 'en', 'email_change_msg', 'Email has been changed successfullyrnrn'),
(810, 'en', 'no_edit_video', 'You cannot edit this video'),
(811, 'en', 'confirm_del_video', 'Are you sure you want to delete this video ?'),
(812, 'en', 'remove_fav_video_confirm', 'Are you sure you want to remove this video from your favorites ?'),
(813, 'en', 'fav_remove_msg', '%s has been removed from your favorites'),
(814, 'en', 'unknown_favorite', 'Unknown favorite %s'),
(815, 'en', 'vdo_multi_del_fav_msg', 'Videos have been removed from your favorites'),
(816, 'en', 'unknown_sender', 'Unknown Sender'),
(817, 'en', 'please_enter_message', 'Please enter something for message'),
(818, 'en', 'unknown_reciever', 'Unknown reciever'),
(819, 'en', 'no_pm_exist', 'Private message does not exist'),
(820, 'en', 'pm_sent_success', 'Private message has been sent successfully'),
(821, 'en', 'msg_delete_inbox', 'Message has been deleted from inbox'),
(822, 'en', 'msg_delete_outbox', 'Message has been deleted from your outbox'),
(823, 'en', 'private_messags_deleted', 'Private messages have been deleted'),
(824, 'en', 'ban_users', 'Ban users'),
(825, 'en', 'spe_users_by_comma', 'separate usernames by comma'),
(826, 'en', 'user_ban_msg', 'Users have been banned successfully'),
(827, 'en', 'no_user_ban_msg', 'No user is banned from your account!'),
(828, 'en', 'thnx_sharing_msg', 'Thanks for sharing this %s'),
(829, 'en', 'no_own_commen_rate', 'You cannot rate your own comment'),
(830, 'en', 'no_comment_exists', 'Comment does not exist'),
(831, 'en', 'thanks_rating_comment', 'Thanks for rating comment'),
(832, 'en', 'please_login_create_playlist', 'Please login to creat playlists'),
(833, 'en', 'play_list_with_this_name_arlready_exists', 'Playlist with name &#8216;%s&#8217; already exists'),
(834, 'en', 'please_enter_playlist_name', 'Please enter playlist name'),
(835, 'en', 'new_playlist_created', 'New playlist has been created'),
(836, 'en', 'playlist_not_exist', 'Playlist does not exist'),
(837, 'en', 'playlist_item_not_exist', 'Playlist item does not exist'),
(838, 'en', 'playlist_item_delete', 'Playlist item has been deleted'),
(839, 'en', 'play_list_updated', 'Playlist has been updated'),
(840, 'en', 'you_dont_hv_permission_del_playlist', 'You do not have permission to delete playlist'),
(841, 'en', 'playlist_delete_msg', 'Playlsit has been deleted'),
(842, 'en', 'playlist_name', 'Playlist name'),
(843, 'en', 'add_new_playlist', 'Add new playlist'),
(844, 'en', 'this_thing_added_playlist', 'This %s has been added to playlist'),
(845, 'en', 'this_already_exist_in_pl', 'This %s already exists in your playlist'),
(846, 'en', 'edit_playlist', 'Edit Playlist'),
(847, 'en', 'remove_playlist_item_confirm', 'Are you sure you want to remove this from your playlist'),
(848, 'en', 'remove_playlist_confirm', 'Are you sure you want to delete this playlist?'),
(849, 'en', 'avcode_incorrect', 'Activation code is incorrect'),
(850, 'en', 'group_join_login_err', 'Please login in order to join this group'),
(851, 'en', 'manage_playlist', 'Manage playlist'),
(852, 'en', 'my_notifications', 'My notifications'),
(853, 'en', 'users_contacts', '%s&#8217;s contacts'),
(854, 'en', 'type_flags_removed', '%s flags have been removed'),
(855, 'en', 'terms_of_serivce', 'Terms of services'),
(856, 'en', 'users', 'Users'),
(857, 'en', 'login_to_mark_as_spam', 'Please login to mark as spam'),
(858, 'en', 'no_own_commen_spam', 'You cannot mark your own comment as spam'),
(859, 'en', 'already_spammed_comment', 'You have already marked this comment as spam'),
(860, 'en', 'spam_comment_ok', 'Comment has been marked as spam'),
(891, 'en', 'you_cant_delete_grp_topics', 'You cannot delete group topics'),
(890, 'en', 'topics_deleted', 'Topics have been deleted'),
(889, 'en', 'you_cant_del_user_topics', 'You cannot delete user topics'),
(888, 'en', 'you_cant_del_topic', 'You cannot delete this topic'),
(887, 'en', 'grp_details_updated', 'Group details have been updated'),
(886, 'en', 'ad_placement_err4', 'Placement does not exist'),
(885, 'en', 'you_cant_delete_this_page', 'You cannot delete this page'),
(884, 'en', 'page_deactivated', 'Page has been dectivated'),
(883, 'en', 'page_activated', 'Page has been activated'),
(882, 'en', 'page_deleted', 'Page has been deleted successfully');
INSERT INTO `cb_phrases` (`id`, `lang_iso`, `varname`, `text`) VALUES
(881, 'en', 'page_updated', 'Page has been updated'),
(880, 'en', 'new_page_added_successfully', 'New page has been added successfully'),
(879, 'en', 'page_content_empty', 'Page content was empty'),
(878, 'en', 'page_title_empty', 'Page title was empty'),
(877, 'en', 'page_name_empty', 'Page name was empty'),
(876, 'en', 'email_tpl_has_updated', 'Email Template has been updated'),
(875, 'en', 'email_msg_empty', 'Email msg was empty'),
(874, 'en', 'email_subj_empty', 'Email subject was empty'),
(873, 'en', 'email_template_not_exist', 'Email template does not exist'),
(872, 'en', 'this_vdo_not_working', 'This video is not working properly&#8221;'),
(871, 'en', 'new_mem_added', 'New member has been added'),
(870, 'en', 'pelase_select_img_file_for_vdo', 'Please select image file for video thumb'),
(869, 'en', 'page_doesnt_exist', 'Page does not exist'),
(868, 'en', 'you_cant_moderate_group', 'You cannot moderate this group'),
(867, 'en', 'you_cant_invite_mems', 'You cannot invite members'),
(866, 'en', 'you_cant_edit_group', 'You cannot edit this group'),
(865, 'en', 'unable_find_download_file', 'Unable to find download file'),
(864, 'en', 'sel_vids_updated', 'Selected videos have been updated'),
(863, 'en', 'you_not_allowed_add_grp_vids', 'You are not member of this group so cannot add videos'),
(862, 'en', 'arslan_hassan', 'Arslan Hassan'),
(892, 'en', 'you_not_allowed_post_topics', 'You are not allowed to post topics'),
(893, 'en', 'you_cant_add_this_vdo', 'You cannot add this video'),
(894, 'en', 'video_added', 'Video has been added'),
(895, 'en', 'you_cant_del_this_vdo', 'You cannot remove this video'),
(896, 'en', 'video_removed', 'Video has been removed'),
(897, 'en', 'user_not_grp_mem', 'User is not group member'),
(898, 'en', 'user_already_group_mem', 'User has already joined this group'),
(899, 'en', 'invitations_sent', 'Invitations have been sent'),
(900, 'en', 'you_not_grp_mem', 'You are not member of this group'),
(901, 'en', 'you_cant_delete_this_grp', 'You cannot delete this group'),
(902, 'en', 'grp_deleted', 'Group has been deleted'),
(903, 'en', 'you_cant_del_grp_mems', 'You cannot delete group members'),
(904, 'en', 'mems_deleted', 'Members have been deleted'),
(905, 'en', 'you_cant_del_grp_vdos', 'You cannot delete group videos'),
(906, 'en', 'thnx_for_voting', 'Thanks for voting'),
(907, 'en', 'you_hv_already_rated_vdo', 'You have already rated this video'),
(908, 'en', 'please_login_to_rate', 'Please login to rate'),
(909, 'en', 'you_not_subscribed', 'You are not subscribed'),
(910, 'en', 'you_cant_delete_this_user', 'You cannot delete this user&#8221;'),
(911, 'en', 'you_dont_hv_perms', 'You dont have sufficient permissions'),
(912, 'en', 'user_subs_hv_been_removed', 'User subscriptions have been removed'),
(913, 'en', 'user_subsers_hv_removed', 'User subscribers have been removed'),
(914, 'en', 'you_already_sent_frend_request', 'You have already sent friend request'),
(915, 'en', 'friend_added', 'Friend has been added'),
(916, 'en', 'friend_request_sent', 'Friend request has been sent'),
(917, 'en', 'friend_confirm_error', 'Either user has not requested you friend request or you have already confirmed it'),
(918, 'en', 'friend_confirmed', 'Friend has been confirmed'),
(919, 'en', 'friend_request_not_found', 'No friend request found'),
(920, 'en', 'you_cant_confirm_this_request', 'You cannot confirm this request'),
(921, 'en', 'friend_request_already_confirmed', 'Friend request is already confirmed'),
(922, 'en', 'user_no_in_contact_list', 'User is not in your contact list'),
(923, 'en', 'user_removed_from_contact_list', 'User has been removed from your contact list'),
(924, 'en', 'cant_find_level', 'Cannot find level'),
(925, 'en', 'please_enter_level_name', 'Please enter level name'),
(926, 'en', 'level_updated', 'Level has been updated'),
(927, 'en', 'level_del_sucess', 'User level has been deleted, all users of this level has been transfered to %s'),
(928, 'en', 'level_not_deleteable', 'This level is not deletable'),
(929, 'en', 'pass_mismatched', 'Passwords Mismatched'),
(930, 'en', 'user_blocked', 'User has been blocked'),
(931, 'en', 'user_already_blocked', 'User is already blocked'),
(932, 'en', 'you_cant_del_user', 'You cannot block this user'),
(933, 'en', 'user_vids_hv_deleted', 'User videos have been deleted'),
(934, 'en', 'user_contacts_hv_removed', 'User contacts have been removed'),
(935, 'en', 'all_user_inbox_deleted', 'All User inbox messages have been delete'),
(936, 'en', 'all_user_sent_messages_deleted', 'All user sent messages have been deleted'),
(937, 'en', 'pelase_enter_something_for_comment', 'Please enter something for comment'),
(938, 'en', 'please_enter_your_name', 'Please enter your name'),
(939, 'en', 'please_enter_your_email', 'Please enter your email'),
(940, 'en', 'template_activated', 'Template has been activated'),
(941, 'en', 'error_occured_changing_template', 'An error occured while changing the template'),
(942, 'en', 'phrase_code_empty', 'Phrase code was empty'),
(943, 'en', 'phrase_text_empty', 'Phrase text was empty'),
(944, 'en', 'language_does_not_exist', 'Language does not exist'),
(945, 'en', 'name_has_been_added', '%s has been added'),
(946, 'en', 'name_already_exists', '&#8216;%s&#8217; already exist'),
(947, 'en', 'lang_doesnt_exist', 'language does not exist'),
(948, 'en', 'no_file_was_selected', 'No file was selected'),
(949, 'en', 'err_reading_file_content', 'Error reading file content'),
(950, 'en', 'cant_find_lang_name', 'Cant find language name'),
(951, 'en', 'cant_find_lang_code', 'Cant find language code'),
(952, 'en', 'no_phrases_found', 'No phrases were found'),
(953, 'en', 'language_already_exists', 'Language already exists'),
(954, 'en', 'lang_added', 'Language has been added successfully'),
(955, 'en', 'error_while_upload_file', 'Error occured while uploading language file'),
(956, 'en', 'default_lang_del_error', 'This is default language, please select other language as &#8220;default&#8221; and then delete this pack'),
(957, 'en', 'lang_deleted', 'Language pack has been deleted'),
(958, 'en', 'lang_name_empty', 'Language name was empty'),
(959, 'en', 'lang_code_empty', 'Language code was empty'),
(960, 'en', 'lang_regex_empty', 'Language regular expression was empty'),
(961, 'en', 'lang_code_already_exist', 'Language code already exists'),
(962, 'en', 'lang_updated', 'Language has been updated'),
(963, 'en', 'player_activated', 'Player has been activated'),
(964, 'en', 'error_occured_while_activating_player', 'An error occured while activating player'),
(965, 'en', 'plugin_has_been_s', 'Plugin has been %s'),
(966, 'en', 'plugin_uninstalled', 'Plugin has been Uninstalled'),
(967, 'en', 'perm_code_empty', 'Permission code is empty'),
(968, 'en', 'perm_name_empty', 'Permission name is empty'),
(969, 'en', 'perm_already_exist', 'Permission already exists'),
(970, 'en', 'perm_type_not_valid', 'Permission type is not valid'),
(971, 'en', 'perm_added', 'New Permission has been added'),
(972, 'en', 'perm_deleted', 'Permission has been deleted'),
(973, 'en', 'perm_doesnt_exist', 'Permission does not exist'),
(974, 'en', 'acitvation_html_message', 'Please enter your user username and activation code in order to activate your account, please check your inbox for Activation code, if you do not have activation code, please request by filling next form'),
(975, 'en', 'acitvation_html_message2', 'Please enter your email address to request your activation code'),
(976, 'en', 'admin_panel', 'Admin Panel'),
(977, 'en', 'moderate_videos', 'Moderate Videos'),
(978, 'en', 'moderate_users', 'Moderate Users'),
(979, 'en', 'revert_back_to_admin', 'Revert back to admin'),
(980, 'en', 'more_options', 'More Options'),
(981, 'en', 'downloading_string', 'Downloading %s ...'),
(982, 'en', 'download_redirect_msg', '<a href="%s">click here if you don''t redirect automatically</a> - <a href="%s"> Click Here to Go Back to Video Page</a>'),
(983, 'en', 'account_details', 'Account Details'),
(984, 'en', 'profile_details', 'Profile Details'),
(985, 'en', 'update_profile', 'Update Profile'),
(986, 'en', 'please_select_img_file', 'Please select image file'),
(987, 'en', 'or', 'or'),
(988, 'en', 'pelase_enter_image_url', 'Please Enter Image URL'),
(989, 'en', 'user_bg', 'User Background'),
(990, 'en', 'user_bg_img', 'User Background Image'),
(991, 'en', 'please_enter_bg_color', 'Please Enter Background Color'),
(992, 'en', 'bg_repeat_type', 'Background Repeat Type (if using image as a background)'),
(993, 'en', 'fix_bg', 'Fix Background'),
(994, 'en', 'delete_this_img', 'Delete this image'),
(995, 'en', 'current_email', 'Current Email'),
(996, 'en', 'confirm_new_email', 'Confirm new email'),
(997, 'en', 'no_subs_found', 'No subscription found'),
(998, 'en', 'video_info_all_fields_req', 'Video Information - All fields are required'),
(999, 'en', 'update_group', 'Update Group'),
(1000, 'en', 'default', 'Default'),
(1001, 'en', 'grp_info_all_fields_req', 'Group Information - All Fields Are Required'),
(1002, 'en', 'date_recorded_location', 'Date recorded &amp; Location'),
(1003, 'en', 'update_video', 'Update Video'),
(1004, 'en', 'click_here_to_recover_user', 'Click here to recover username'),
(1005, 'en', 'click_here_reset_pass', 'Click here to reset password'),
(1006, 'en', 'remember_me', 'Remember Me'),
(1007, 'en', 'howdy_user', 'howdy %s'),
(1008, 'en', 'notifications', 'Notifications'),
(1009, 'en', 'playlists', 'Playlists'),
(1010, 'en', 'friend_requests', 'Friend Requests'),
(1011, 'en', 'after_meny_guest_msg', 'Welcome Guest ! Please <a href="%s">Login</a> or <a href="%s">Register</a>'),
(1012, 'en', 'being_watched', 'Being Watched'),
(1013, 'en', 'change_style_of_listing', 'Change Style of Listing'),
(1014, 'en', 'website_members', '%s Members'),
(1015, 'en', 'guest_homeright_msg', 'Watch, Upload, Share and more'),
(1016, 'en', 'reg_for_free', 'Register for free'),
(1017, 'en', 'rand_vids', 'Random Videos'),
(1018, 'en', 't_10_users', 'Top 10 Users'),
(1019, 'en', 'pending', 'Pending'),
(1020, 'en', 'confirm', 'Confirm'),
(1021, 'en', 'no_contacts', 'No Contacts'),
(1022, 'en', 'you_dont_hv_any_grp', 'You do not have any group'),
(1023, 'en', 'leave_groups', 'Leave Groups'),
(1024, 'en', 'manage_grp_mems', 'Manage Group Members'),
(1025, 'en', 'pending_mems', 'Pending Members'),
(1026, 'en', 'active_mems', 'Active Members'),
(1027, 'en', 'disapprove', 'Disapprove'),
(1028, 'en', 'manage_grp_vids', 'Manage Group Videos'),
(1029, 'en', 'pending_vids', 'Pending Videos'),
(1030, 'en', 'no_pending_vids', 'No Pending Videos'),
(1031, 'en', 'no_active_videos', 'No Active Videos'),
(1032, 'en', 'active_videos', 'Active Videos'),
(1033, 'en', 'manage_playlists', 'Manage Playlists'),
(1034, 'en', 'total_items', 'Total Items'),
(1035, 'en', 'play_now', 'PLAY NOW'),
(1036, 'en', 'no_video_in_playlist', 'This playlist has no video'),
(1037, 'en', 'view', 'View'),
(1038, 'en', 'you_dont_hv_fav_vids', 'You do not have any favorite video'),
(1039, 'en', 'private_messages', 'Private Messages'),
(1040, 'en', 'new_private_msg', 'New private message'),
(1041, 'en', 'search_for_s', 'Search For %s'),
(1042, 'en', 'signup_success_usr_ok', '<h2 style="margin: 5px 5px 8px; font-family: Arial,Verdana,sans-serif;">Just One More Step</h2>     	<p style="margin: 0px 5px; line-height: 18px; font-size: 11px;">Your are just one step behind from becoming an official memeber of our website.  Please check your email, we have sent you a confirmation email which contains a confirmation link from our website, Please click it to complete your registration.</p>'),
(1043, 'en', 'signup_success_usr_emailverify', '<h2 style="font-family:Arial,Verdana,sans-serif; margin:5px 5px 8px;">Welcome To our community</h2>\r\n    	<p style="margin:0px 5px; line-height:18px; font-size:11px;">Your email has been confirmed, Please <strong><a href="%s">click here to login</a></strong> and continue as our registered member.</p>'),
(1044, 'en', 'if_you_already_hv_account', 'if you already have account, please login here '),
(1045, 'en', 'signup_message_under_login', ' <p>Our website is the home for video online:</p>\r\n          \r\n            <ul><li><strong>Watch</strong> millions  of videos</li><li><strong>Share favorites</strong> with friends and family</li>\r\n            <li><strong>Connect with other users</strong> who share your interests</li><li><strong>Upload your videos</strong> to a worldwide audience\r\n\r\n</li></ul>'),
(1046, 'en', 'new_mems_signup_here', 'New Members Signup Here'),
(1047, 'en', 'register_as_our_website_member', 'Register as a member, its free and easy just '),
(1048, 'en', 'video_complete_msg', '<h2>Video Upload Has Been Completed</h2>\r\n<span class="header1">Thank you! Your upload is complete.</span><br>\r\n<span class="tips">This video will be available in <a href="%s"><strong>My Videos</strong></a> after it has finished processing.</span>  \r\n<div class="upload_link_button" align="center">\r\n    <ul>\r\n        <li><a href="%s" >Upload Another Video</a></li>\r\n        <li><a href="%s" >Goto My Videos</a></li>\r\n    </ul>\r\n<div class=''clearfix''></div>\r\n</div>\r\n'),
(1049, 'en', 'upload_right_guide', ' <div>\r\n            <div>\r\n              <p>\r\n                <strong>\r\n                <strong>Important:</strong>\r\n                Do not upload any TV shows, music videos, music concerts, or  commercials without permission unless they consist entirely of content  you created yourself.</strong></p>\r\n                <p>The \r\n                <a href="#">Copyright Tips page</a> and the \r\n                <a href="#">Community Guidelines</a> can help you determine whether your video infringes someone else''s copyright.</p>\r\n                <p>By clicking "Upload Video", you are representing that this video does not violate Our website''s \r\n                <a id="terms-of-use-link" href="#">Terms of Use</a> \r\n                and that you own all copyrights in this video or have authorization to upload it.</p>\r\n            </div>\r\n        </div>'),
(1050, 'en', 'report_this_user', 'Report This User'),
(1051, 'en', 'add_to_favs', 'Add to favorites'),
(1052, 'en', 'report_this', 'Report this!'),
(1053, 'en', 'share_this', 'Share This'),
(1054, 'en', 'add_to_playlist', 'Add to playlist'),
(1055, 'en', 'view_profile', 'View Profile'),
(1056, 'en', 'subscribe', 'Subscribe'),
(1057, 'en', 'uploaded_by_s', 'Uploaded by %s'),
(1058, 'en', 'more', 'More'),
(1059, 'en', 'link_this_video', 'Link This Video'),
(1060, 'en', 'click_to_download_video', 'Click Here To Download This Video'),
(1061, 'en', 'name', 'Name'),
(1062, 'en', 'email_wont_display', 'Email (Wont display)'),
(1063, 'en', 'please_login_to_comment', 'Please login to comment'),
(1064, 'en', 'marked_as_spam_comment_by_user', 'Marked as spam, commented by <em>%s</em>'),
(1065, 'en', 'spam', 'Spam'),
(1066, 'en', 'user_commented_time', '<a href="%s">%s</a> commented %s'),
(1067, 'en', 'no_comments', 'No Comments'),
(1068, 'en', 'view_video', 'View Video'),
(1069, 'en', 'topic_icon', 'Topic Icon'),
(1070, 'en', 'group_options', 'Group option'),
(1071, 'en', 'info', 'Info'),
(1072, 'en', 'basic_info', 'Basic Info'),
(1073, 'en', 'group_owner', 'Group Owner'),
(1074, 'en', 'total_mems', 'Total Members'),
(1075, 'en', 'total_topics', 'Total Topics'),
(1076, 'en', 'grp_url', 'Group URL'),
(1077, 'en', 'more_details', 'More Details<'),
(1078, 'en', 'view_all_mems', 'View All Members'),
(1079, 'en', 'view_all_vids', 'View All Videos'),
(1080, 'en', 'topic_title', 'Topic Title'),
(1081, 'en', 'last_reply', 'Last Reply'),
(1082, 'en', 'topic_by_user', '<a href="%s">%s</a></span> by <a href="%s">%s</a>'),
(1083, 'en', 'no_topics', 'No Topics'),
(1084, 'en', 'last_post_time_by_user', '%s<br />\r\nby <a href="%s">%s'),
(1085, 'en', 'profile_views', 'Profile views'),
(1086, 'en', 'last_logged_in', 'last logged in'),
(1087, 'en', 'last_active', 'Last active'),
(1088, 'en', 'total_logins', 'Total logins'),
(1089, 'en', 'total_videos_watched', 'Total videos watched'),
(1090, 'en', 'view_group', 'View Group'),
(1091, 'en', 'you_dont_hv_any_pm', 'You do not have any private message'),
(1092, 'en', 'date_sent', 'Date sent'),
(1093, 'en', 'show_hide', 'show - hide'),
(1094, 'en', 'quicklists', 'Quicklists'),
(1095, 'en', 'are_you_sure_rm_grp', 'Are you sure you want to remove this group ?'),
(1096, 'en', 'are_you_sure_del_grp', 'Are you sure you want to delete this group?'),
(1097, 'en', 'change_avatar', 'Change Avatar'),
(1098, 'en', 'change_bg', 'Change Background'),
(1099, 'en', 'uploaded_videos', 'Uploaded Videos'),
(1100, 'en', 'video_playlists', 'Video Playlists'),
(1101, 'en', 'add_contact_list', 'Add contact list'),
(1102, 'en', 'topic_post', 'Topic Post'),
(1103, 'en', 'invite', 'Invite'),
(1104, 'en', 'time_ago', '%s %s ago'),
(1105, 'en', 'from_now', '%s %s from now');

