server {
    listen 8081;
    server_name PROFILING_DOMAIN_PLACEHOLDER;
    root /usr/share/xhgui/webroot;
    index index.php;

    location ~* \.php$ {
        fastcgi_pass unix:/run/php/phpPHP_VERSION_PLACEHOLDER-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location / {
        try_files $uri $uri/ /index.php?$args;
    }
}
