<?php
namespace V5_5_0;
require_once \DirPath::get('classes') . DIRECTORY_SEPARATOR . 'migration' . DIRECTORY_SEPARATOR . 'migration.class.php';

class M00289 extends \Migration
{
    /**
     * @throws \Exception
     */
    public function start()
    {
        $sql = 'DELETE FROM `{tbl_prefix}config` WHERE `name` = \'video_age_verification\';';
        self::query($sql);
        $sql = 'DROP TABLE IF EXISTS `{tbl_prefix}group_invitations`;';
        self::query($sql);
        $sql = 'DROP TABLE IF EXISTS `{tbl_prefix}group_members`;';
        self::query($sql);
        $sql = 'DROP TABLE IF EXISTS `{tbl_prefix}group_videos`;';
        self::query($sql);
        $sql = 'DROP TABLE IF EXISTS `{tbl_prefix}group_topics`;';
        self::query($sql);
        $sql = 'DROP TABLE IF EXISTS `{tbl_prefix}group_posts`;';
        self::query($sql);
        $sql = 'DROP TABLE IF EXISTS `{tbl_prefix}group_categories`;';
        self::query($sql);
        $sql = 'DROP TABLE IF EXISTS `{tbl_prefix}groups`;';
        self::query($sql);

        self::alterTable('ALTER TABLE `{tbl_prefix}users` DROP COLUMN `total_groups`;', [
            'table' => 'users',
            'column' => 'total_groups',
        ]);
        $sql = 'DELETE FROM `{tbl_prefix}user_permissions` WHERE `permission_code` IN(\'view_groups\',\'view_group\')';
        self::query($sql);

        self::alterTable('ALTER TABLE `{tbl_prefix}user_levels_permissions` DROP COLUMN `view_groups`', [
            'table' => 'user_levels_permissions',
            'column' => 'view_groups',
        ]);
        self::alterTable('ALTER TABLE `{tbl_prefix}user_levels_permissions` DROP COLUMN `view_group`', [
            'table' => 'user_levels_permissions',
            'column' => 'view_group',
        ]);

        $sql = 'DELETE FROM `{tbl_prefix}languages_translations` WHERE `id_language_key` IN(
                SELECT `id_language_key` FROM `{tbl_prefix}languages_keys` WHERE `language_key` IN(
                    \'ad_code_error\',\'grp_err\',\'grp_fr_msg\',\'grp_fr_msg1\',\'grp_ac_msg\',\'grp_dac_msg\',\'grp_del_msg\',\'editor_pic_up\',\'editor_pic_down\',
                    \'grp_name_error\',\'grp_name_error1\',\'grp_des_error\',\'grp_tags_error\',\'grp_url_error\',\'grp_url_error1\',\'grp_url_error2\',\'grp_tpc_error\',
                    \'grp_comment_error\',\'grp_join_error\',\'grp_prvt_error\',\'grp_inact_error\',\'grp_join_error1\',\'grp_exist_error\',\'grp_tpc_error1\',
                    \'grp_cat_error\',\'grp_tpc_error2\',\'grp_tpc_error3\',\'grp_tpc_msg\',\'grp_vdo_msg\',\'grp_vdo_msg1\',\'grp_vdo_msg2\',\'grp_mem_msg\',
                    \'grp_mem_msg1\',\'grp_inv_msg\',\'grp_tpc_msg1\',\'grp_tpc_msg2\',\'grp_fr_msg2\',\'grp_inv_msg1\',\'grp_av_msg\',\'grp_da_msg\',\'grp_post_msg\',
                    \'grp_update_msg\',\'grp_owner_err\',\'grp_owner_err1\',\'grp_owner_err2\',\'grp_prvt_err1\',\'grp_rmv_msg\',\'grp_tpc_err4\',\'grp_title_topic\',
                    \'grp_add_title\',\'usr_sadmin_err\',\'usr_email_err\',\'usr_pass_err1\',\'usr_cmt_err\',\'usr_cmt_err1\',\'usr_cmt_err2\',\'usr_cmt_err3\',
                    \'usr_cmt_err4\',\'usr_cmt_del_err\',\'usr_cnt_err\',\'usr_cnt_err1\',\'usr_ccode_err\',\'usr_exist_err1\',\'usr_exist_err2\',\'usr_pcode_err\',
                    \'usr_fname_err\',\'usr_lname_err\',\'usr_dob_err\',\'usr_sadmin_msg\',\'usr_pass_msg\',\'usr_cnt_msg\',\'usr_email_msg\',\'usr_dels_msg\',
                    \'usr_mem_ac\',\'usr_mems_ac\',\'usr_fr_msg\',\'usr_ufr_msg\',\'usr_frs_msg\',\'usr_ufrs_msg\',\'usr_ubans_msg\',\'usr_uubans_msg\',
                    \'usr_pass_reset_conf\',\'usr_dear_user\',\'usr_pass_reset_msg\',\'usr_rpass_msg\',\'usr_rpass_req_msg\',\'usr_uname_req_msg\',\'usr_uname_recovery\',
                    \'usr_add_succ_msg\',\'usr_activation_em_err\',\'usr_no_msg_del_err\',\'usr_sel_msg_del_msg\',\'usr_arr_open_marriage\',\'title_forgot\',
                    \'title_inbox\',\'title_sent\',\'title_usr_contact\',\'title_edit_video\',\'vdo_title_err\',\'vdo_des_err\',\'vdo_tags_err\',\'vdo_cat_err\',
                    \'vdo_cat_err1\',\'vdo_sub_email_msg\',\'vdo_has_upload_nv\',\'vdo_del_selected\',\'vdo_cheat_msg\',\'vdo_limits_warn_msg\',\'vdo_cmt_del_msg\',
                    \'vdo_is_in_process\',\'vdo_upload_allow_err\',\'vdo_download_allow_err\',\'vdo_edit_owner_err\',\'vdo_embed_code_wrong\',\'vdo_seconds_err\',
                    \'vdo_mins_err\',\'vdo_thumb_up_err\',\'class_comment_err\',\'class_comment_err1\',\'class_comment_err2\',\'class_comment_err3\',
                    \'class_comment_err4\',\'class_comment_err5\',\'class_comment_msg\',\'class_vdo_fav_err\',\'class_vdo_fav_msg\',\'class_vdo_flag_err\',
                    \'class_vdo_flag_msg\',\'class_vdo_flag_rm\',\'class_send_msg_err\',\'class_msg_err\',\'class_sent_you_msg\',\'class_sent_prvt_msg\',
                    \'class_click_inbox\',\'class_click_login\',\'class_email_notify\',\'class_msg_has_sent_to\',\'class_inbox_del_msg\',\'class_sent_del_msg\',
                    \'class_msg_exist_err\',\'class_sub_exist_err\',\'class_vdo_rm_fav_msg\',\'class_vdo_fav_err1\',\'class_cont_del_msg\',\'class_cot_err\',
                    \'class_vdo_ep_err1\',\'class_img_gif_err\',\'class_img_png_err\',\'class_img_jpg_err\',\'class_logo_msg\',\'com_join_now\',
                    \'com_my_account\',\'com_view_channel\',\'com_welcome\',\'com_top_mem\',\'com_vidz\',\'com_sign_up_now\',\'com_my_videos\',\'com_my_subs\',
                    \'com_user_no_contacts\',\'com_user_no_vides\',\'com_user_no_vid_com\',\'com_view_all_contacts\',\'com_view_fav_all_videos\',
                    \'com_login_success_msg\',\'com_logout_success_msg\',\'com_not_redirecting\',\'com_not_redirecting_msg\',\'com_manage_contacts\',
                    \'com_subscribe_to\',\'com_total_subs\',\'com_total_vids\',\'com_date_subscribed\',\'com_search_results\',\'com_search_results_in\',
                    \'videos_being_watched\',\'latest_added_videos\',\'recently_added\',\'highest_rated\',\'most_discussed\',\'style_change\',
                    \'rss_feed_latest_title\',\'rss_feed_featured_title\',\'rss_feed_most_viewed_title\',\'lang_folder\',\'reg_closed\',\'reg_for\',
                    \'is_currently_closed\',\'added\',\'advertisements\',\'age\',\'approve\',\'approved\',\'approval\',\'books\',\'browse\',\'check_all\',
                    \'click_here\',\'community\',\'contacts\',\'created\',\'date_joined\',\'dear\',\'des_title\',\'embed\',\'favourite\',\'favourited\',\'filter\',
                    \'forgot\',\'groups\',\'hello\',\'hi\',\'home\',\'interests\',\'join_now\',\'join\',\'keywords\',\'latest\',\'leave\',\'most_members\',
                    \'most_videos\',\'music\',\'no_user_exists\',\'no_video_exists\',\'occupations\',\'owner\',\'please\',\'privacy\',\'random\',\'rate\',
                    \'related\',\'results\',\'relationship\',\'select\',\'times\',\'url\',\'verification\',\'viewing\',\'welcome\',\'of\',\'on\',\'ratings\',
                    \'show_all\',\'signupup\',\'subscriptions\',\'time\',\'top\',\'tos_title\',\'proccession_wait\',\'group\',\'not_logged_in\',\'fill_auth_form\',
                    \'admin_disabled_you\',\'recover_password\',\'submit\',\'reset_Fields\',\'admin_reg_req\',\'lang_change\',\'lang_changed\',\'lang_choice\',
                    \'if_not_redir\',\'style_changed\',\'style_choice\',\'vdo_stills\',\'vdo_watch_video\',\'vdo_date_loc\',\'vdo_date_rec\',\'vdo_for_date\',
                    \'vdo_comm_vote\',\'vdo_allow_com_vote\',\'vdo_dallow_com_vote\',\'vdo_update_title\',\'vdo_inactive_msg\',\'vdo_click_here\',
                    \'vdo_continue_upload\',\'vdo_upload_step1\',\'vdo_upload_step2\',\'vdo_upload_step3\',\'vdo_select_vdo\',\'vdo_enter_remote_url\',
                    \'vdo_enter_embed_code_msg\',\'vdo_enter_embed_code\',\'vdo_enter_druation\',\'vdo_select_vdo_thumb\',\'vdo_having_trouble\',
                    \'vdo_if_having_problem\',\'vdo_clic_to_manage_all\',\'vdo_rawfile\',\'vdo_video_upload_complete\',\'vdo_thanks_you_upload_complete_1\',
                    \'vdo_thanks_you_upload_complete_2\',\'vdo_after_it_has_process\',\'vdo_embed_this_video_on_web\',\'vdo_copy_and_paste_the_code\',
                    \'vdo_upload_another_video\',\'vdo_goto_my_videos\',\'vdo_sperate_emails_by\',\'vdo_personal_msg\',\'vdo_related_tags\',
                    \'vdo_reply_to_this\',\'vdo_add_reply\',\'vdo_share_video\',\'vdo_about_this_video\',\'vdo_post_to_a_services\',\'vdo_commentary\',
                    \'vdo_post_a_comment\',\'grp_add_vdo_msg\',\'grp_no_vdo_msg\',\'grp_add_to\',\'grp_add_vdos\',\'grp_name_title\',\'grp_tag_title\',
                    \'grp_des_title\',\'grp_tags_msg\',\'grp_tags_msg1\',\'grp_url_title\',\'grp_url_msg\',\'grp_cat_tile\',\'grp_vdo_uploads\',
                    \'grp_forum_posting\',\'grp_join_opt1\',\'grp_join_opt2\',\'grp_join_opt3\',\'grp_vdo_opt1\',\'grp_vdo_opt2\',\'grp_vdo_opt3\',
                    \'grp_post_opt1\',\'grp_post_opt2\',\'grp_post_opt3\',\'grp_crt_grp\',\'grp_thumb_title\',\'grp_upl_thumb\',\'grp_must_be\',
                    \'grp_90x90\',\'grp_thumb_warn\',\'grp_del_confirm\',\'grp_del_success\',\'grp_click_go_grps\',\'grp_edit_grp_title\',
                    \'grp_manage_vdos\',\'grp_manage_mems\',\'grp_del_group_title\',\'grp_add_vdos_title\',\'grp_join_grp_title\',\'grp_leave_group_title\',
                    \'grp_invite_grp_title\',\'grp_view_mems\',\'grp_create_grp_title\',\'grp_most_members\',\'grp_most_discussed\',\'grp_invite_msg\',
                    \'grp_invite_msg1\',\'grp_invite_msg2\',\'grp_url_title1\',\'grp_invite_msg3\',\'grp_join_confirm_msg\',\'grp_join_msg_succ\',
                    \'grp_click_here_to_go\',\'grp_leave_confirm\',\'grp_leave_succ_msg\',\'grp_for_approval\',\'grp_rm_videos\',\'grp_rm_mems\',
                    \'grp_groups_title\',\'grp_joined_title\',\'grp_remove_group\',\'grp_bo_grp_found\',\'grp_joined_groups\',\'grp_owned_groups\',
                    \'grp_edit_this_grp\',\'grp_topics_title\',\'grp_topic_title\',\'grp_posts_title\',\'grp_discus_title\',\'grp_author_title\',
                    \'grp_replies_title\',\'grp_last_post_title\',\'grp_viewl_all_videos\',\'grp_add_new_topic\',\'grp_attach_video\',\'grp_add_topic\',
                    \'grp_please_login\',\'grp_please_join\',\'grp_inactive_account\',\'grp_about_this_grp\',\'grp_no_vdo_err\',\'grp_posted_by\',
                    \'grp_add_new_comment\',\'grp_add_comment\',\'grp_pls_login_comment\',\'grp_pls_join_comment\',\'usr_actiavation_msg\',\'usr_compose_msg\',
                    \'usr_inbox_title\',\'usr_sent_title\',\'usr_to_title\',\'usr_or_select_frm_list\',\'user_attached_video\',\'usr_send_message\',
                    \'user_no_message\',\'user_delete_message_msg\',\'user_forgot_message_2\',\'user_pass_reset_msg\',\'user_pass_forgot_msg\',
                    \'user_reocover_user\',\'user_user_forgot_msg\',\'user_dashboard\',\'user_manage_prof_chnnl\',\'user_manage_friends\',\'user_prof_channel\',
                    \'user_message_box\',\'user_new_messages\',\'user_goto_inbox\',\'user_goto_sentbox\',\'user_compose_new\',\'user_total_subs_users\',
                    \'user_you_have\',\'user_your_vids_watched\',\'user_times\',\'user_you_have_watched\',\'user_channel_views\',\'user_channel_comm\',
                    \'user_manage_prof\',\'user_you_created\',\'user_you_joined\',\'user_create_group\',\'user_manage_my_videos\',\'user_manage_my_channel\',
                    \'user_manage_channel\',\'user_manage_my_contacts\',\'user_manage_favourites\',\'user_mem_login\',\'user_already_have\',
                    \'user_forgot_password\',\'user_create_your\',\'user_valid_email_addr\',\'user_reg_msg_0\',\'user_reg_msg_1\',\'user_enter_text_as_img\',
                    \'user_refresh_img\',\'user_thanks_for_reg\',\'user_email_has_sent\',\'user_and_activation\',\'user_details_you_now\',
                    \'user_upload_share_vds\',\'user_make_friends\',\'user_send_messages\',\'user_grow_your_network\',\'user_make_customize\',
                    \'user_to_upload_vid\',\'user_click_to_login\',\'user_view_my_channel\',\'user_email_settings\',\'user_usr_prof_chnl_edit\',
                    \'user_personal_info\',\'user_gender\',\'user_display_age\',\'user_website_url\',\'user_eg_website\',\'user_prof_info\',\'user_education\',
                    \'user_school_colleges\',\'user_occupations\',\'user_companies\',\'user_sperate_by_commas\',\'user_interests_hobbies\',
                    \'user_upload_avatar\',\'user_channel_info\',\'user_channel_title\',\'user_channel_description\',\'user_channel_permission\',
                    \'user_allow_comments_msg\',\'user_dallow_comments_msg\',\'user_allow_rating\',\'user_dallow_rating\',\'user_allow_rating_msg1\',
                    \'user_dallow_rating_msg1\',\'user_channel_feature_vid\',\'user_select_vid_for_fr\',\'user_chane_channel_bg\',\'user_remove_bg\',
                    \'user_currently_you_d_have_pic\',\'user_notify_me\',\'user_do_not_have_contact\',\'user_no_fav_video_exist\',\'user_have_no_vide\',
                    \'user_add_contact\',\'user_dob\',\'user_movies_shows\',\'user_no_fr_video\',\'user_view_all_video_of\',\'user_subscribe_message\',
                    \'user_subscribe_subject\',\'embed_code_invalid_err\',\'invalid_duration\',\'vid_thumb_change_err\',\'my_text_context\',
                    \'profile_title\',\'profile_desc\',\'temp_file_load_err\',\'user_no_subscribers\',\'user_no_subscriptions\',\'confirm_del_video\',
                    \'remove_fav_video_confirm\',\'ban_users\',\'user_have_no_playlists\',\'this_thing_added_playlist\',\'group_join_login_err\',
                    \'terms_of_serivce\',\'arslan_hassan\',\'you_not_allowed_add_grp_vids\',\'sel_vids_updated\',\'you_cant_edit_group\',
                    \'you_cant_invite_mems\',\'you_cant_moderate_group\',\'grp_details_updated\',\'you_cant_del_topic\',\'you_cant_del_user_topics\',
                    \'topics_deleted\',\'you_cant_delete_grp_topics\',\'you_not_allowed_post_topics\',\'you_cant_add_this_vdo\',\'video_added\',
                    \'you_cant_del_this_vdo\',\'video_removed\',\'user_not_grp_mem\',\'user_already_group_mem\',\'invitations_sent\',
                    \'you_not_grp_mem\',\'you_cant_delete_this_grp\',\'grp_deleted\',\'you_cant_del_grp_mems\',\'mems_deleted\',\'you_cant_del_grp_vdos\',
                    \'phrase_code_empty\',\'phrase_text_empty\',\'name_has_been_added\',\'name_already_exists\',\'lang_doesnt_exist\',
                    \'no_file_was_selected\',\'err_reading_file_content\',\'cant_find_lang_name\',\'cant_find_lang_code\',\'no_phrases_found\',
                    \'language_already_exists\',\'error_while_upload_file\',\'lang_regex_empty\',\'lang_code_already_exist\',\'perm_code_empty\',
                    \'perm_name_empty\',\'perm_already_exist\',\'perm_type_not_valid\',\'perm_added\',\'perm_deleted\',\'perm_doesnt_exist\',
                    \'admin_panel\',\'moderate_videos\',\'moderate_users\',\'revert_back_to_admin\',\'more_options\',\'downloading_string\',
                    \'download_redirect_msg\',\'profile_details\',\'update_profile\',\'user_bg_img\',\'please_enter_bg_color\',\'bg_repeat_type\',
                    \'fix_bg\',\'video_info_all_fields_req\',\'update_group\',\'grp_info_all_fields_req\',\'click_here_to_recover_user\',
                    \'click_here_reset_pass\',\'howdy_user\', \'friend_requests\',\'after_meny_guest_msg\',\'being_watched\',\'website_members\',
                    \'guest_homeright_msg\',\'reg_for_free\',\'rand_vids\',\'t_10_users\',\'pending\',\'confirm\',\'no_contacts\',\'you_dont_hv_any_grp\',
                    \'you_dont_joined_any_grp\',\'leave_groups\',\'manage_grp_mems\',\'pending_mems\',\'active_mems\',\'disapprove\',\'manage_grp_vids\',
                    \'pending_vids\',\'no_pending_vids\',\'no_active_videos\',\'active_videos\',\'search_for_s\',\'if_you_already_hv_account\',
                    \'signup_message_under_login\',\'new_mems_signup_here\',\'register_as_our_website_member\',\'video_complete_msg\',
                    \'upload_right_guide\',\'report_this_user\',\'add_to_favs\',\'share_this\',\'uploaded_by_s\',\'click_to_download_video\',
                    \'marked_as_spam_comment_by_user\',\'user_commented_time\',\'topic_icon\',\'group_options\',\'group_owner\',\'total_mems\',
                    \'total_topics\',\'grp_url\',\'more_details\',\'view_all_mems\',\'view_all_vids\',\'topic_title\',\'last_reply\',\'topic_by_user\',
                    \'no_topics\',\'last_post_time_by_user\',\'profile_views\',\'last_logged_in\',\'last_active\',\'total_videos_watched\',\'view_group\',
                    \'show_hide\',\'are_you_sure_rm_grp\',\'are_you_sure_del_grp\',\'change_bg\',\'video_playlists\',\'add_contact_list\',\'topic_post\',
                    \'invite\',\'lang_has_been_activated\',\'lang_has_been_deactivated\',\'lang_default_no_actions\',\'coments_disabled_profile\',
                    \'chane_lang\',\'recent\',\'commented\',\'no_new_subs_video\',\'pending_requests\',\'required_fields\',\'please_enter_remote_file_url\',
                    \'upload_videos_can_be\',\'photo_non_readable\',\'wrong_mime_type\',\'photo_tags\',\'no_upload_opt\',\'uploaded\',\'upload_desktop_msg\',
                    \'embed_video_msg\',\'most_downloaded\',\'total_videos\',\'upload_right_guide_vid\',\'collect_items_deleted\',\'rand_photos\',
                    \'watch_video_page\',\'watch_on_photo_page\',\'found_no_videos\',\'found_no_photos\',\'this_video_found_in_no_collection\',
                    \'more_from\',\'this_collection\',\'channel_account_settings\',\'user_doesnt_any_collection\',\'total_collections\',\'total_photos\',
                    \'comments_made\',\'tp_del_confirm\',\'you_need_owners_approval_to_view_group\',\'please_enter_confimation_ode\',
                    \'vdo_brd_confidential\',\'please_provide_valid_userid\',\'user_has_created_new_group\',\'total_members\',\'user_has_joined_group\',
                    \'activity\',\'feed_has_been_deleted\',\'you_cant_del_this_feed\',\'group_is_public\',\'collection_thumb\',\'edit_type_collection\',
                    \'view_all\',\'you_dont_have_any_videos\',\'update_blocked_use\',\'group_is_private\',\'block_user\',\'send_message\',
                    \'you_not_grp_mem_or_approved\',\'download\',\'flag_video\',\'upload_beats_guide\',\'contact\',\'no_collection_upload\',
                    \'upload_in_progress\',\'complete_of_video\',\'agree\',\'terms\',\'and\',\'policy\',\'edit_video\',\'del_video\',\'last_one\',\'subscribe_btn\',
                    \'play\',\'no_vid_in_playlist\',\'anonymous\',\'please_enter_collection_name\',\'select_collection\',\'vdo_inactive\',
                    \'photo_tags_error\',\'photo_tags_err\'
                )
            );';
        self::query($sql);

        $sql = 'DELETE FROM `{tbl_prefix}languages_keys` WHERE `language_key` IN(
        \'ad_code_error\',\'grp_err\',\'grp_fr_msg\',\'grp_fr_msg1\',\'grp_ac_msg\',\'grp_dac_msg\',\'grp_del_msg\',\'editor_pic_up\',\'editor_pic_down\',
        \'grp_name_error\',\'grp_name_error1\',\'grp_des_error\',\'grp_tags_error\',\'grp_url_error\',\'grp_url_error1\',\'grp_url_error2\',\'grp_tpc_error\',
        \'grp_comment_error\',\'grp_join_error\',\'grp_prvt_error\',\'grp_inact_error\',\'grp_join_error1\',\'grp_exist_error\',\'grp_tpc_error1\',
        \'grp_cat_error\',\'grp_tpc_error2\',\'grp_tpc_error3\',\'grp_tpc_msg\',\'grp_vdo_msg\',\'grp_vdo_msg1\',\'grp_vdo_msg2\',\'grp_mem_msg\',
        \'grp_mem_msg1\',\'grp_inv_msg\',\'grp_tpc_msg1\',\'grp_tpc_msg2\',\'grp_fr_msg2\',\'grp_inv_msg1\',\'grp_av_msg\',\'grp_da_msg\',\'grp_post_msg\',
        \'grp_update_msg\',\'grp_owner_err\',\'grp_owner_err1\',\'grp_owner_err2\',\'grp_prvt_err1\',\'grp_rmv_msg\',\'grp_tpc_err4\',\'grp_title_topic\',
        \'grp_add_title\',\'usr_sadmin_err\',\'usr_email_err\',\'usr_pass_err1\',\'usr_cmt_err\',\'usr_cmt_err1\',\'usr_cmt_err2\',\'usr_cmt_err3\',
        \'usr_cmt_err4\',\'usr_cmt_del_err\',\'usr_cnt_err\',\'usr_cnt_err1\',\'usr_ccode_err\',\'usr_exist_err1\',\'usr_exist_err2\',\'usr_pcode_err\',
        \'usr_fname_err\',\'usr_lname_err\',\'usr_dob_err\',\'usr_sadmin_msg\',\'usr_pass_msg\',\'usr_cnt_msg\',\'usr_email_msg\',\'usr_dels_msg\',
        \'usr_mem_ac\',\'usr_mems_ac\',\'usr_fr_msg\',\'usr_ufr_msg\',\'usr_frs_msg\',\'usr_ufrs_msg\',\'usr_ubans_msg\',\'usr_uubans_msg\',
        \'usr_pass_reset_conf\',\'usr_dear_user\',\'usr_pass_reset_msg\',\'usr_rpass_msg\',\'usr_rpass_req_msg\',\'usr_uname_req_msg\',\'usr_uname_recovery\',
        \'usr_add_succ_msg\',\'usr_activation_em_err\',\'usr_no_msg_del_err\',\'usr_sel_msg_del_msg\',\'usr_arr_open_marriage\',\'title_forgot\',
        \'title_inbox\',\'title_sent\',\'title_usr_contact\',\'title_edit_video\',\'vdo_title_err\',\'vdo_des_err\',\'vdo_tags_err\',\'vdo_cat_err\',
        \'vdo_cat_err1\',\'vdo_sub_email_msg\',\'vdo_has_upload_nv\',\'vdo_del_selected\',\'vdo_cheat_msg\',\'vdo_limits_warn_msg\',\'vdo_cmt_del_msg\',
        \'vdo_is_in_process\',\'vdo_upload_allow_err\',\'vdo_download_allow_err\',\'vdo_edit_owner_err\',\'vdo_embed_code_wrong\',\'vdo_seconds_err\',
        \'vdo_mins_err\',\'vdo_thumb_up_err\',\'class_comment_err\',\'class_comment_err1\',\'class_comment_err2\',\'class_comment_err3\',
        \'class_comment_err4\',\'class_comment_err5\',\'class_comment_msg\',\'class_vdo_fav_err\',\'class_vdo_fav_msg\',\'class_vdo_flag_err\',
        \'class_vdo_flag_msg\',\'class_vdo_flag_rm\',\'class_send_msg_err\',\'class_msg_err\',\'class_sent_you_msg\',\'class_sent_prvt_msg\',
        \'class_click_inbox\',\'class_click_login\',\'class_email_notify\',\'class_msg_has_sent_to\',\'class_inbox_del_msg\',\'class_sent_del_msg\',
        \'class_msg_exist_err\',\'class_sub_exist_err\',\'class_vdo_rm_fav_msg\',\'class_vdo_fav_err1\',\'class_cont_del_msg\',\'class_cot_err\',
        \'class_vdo_ep_err1\',\'class_img_gif_err\',\'class_img_png_err\',\'class_img_jpg_err\',\'class_logo_msg\',\'com_join_now\',
        \'com_my_account\',\'com_view_channel\',\'com_welcome\',\'com_top_mem\',\'com_vidz\',\'com_sign_up_now\',\'com_my_videos\',\'com_my_subs\',
        \'com_user_no_contacts\',\'com_user_no_vides\',\'com_user_no_vid_com\',\'com_view_all_contacts\',\'com_view_fav_all_videos\',
        \'com_login_success_msg\',\'com_logout_success_msg\',\'com_not_redirecting\',\'com_not_redirecting_msg\',\'com_manage_contacts\',
        \'com_subscribe_to\',\'com_total_subs\',\'com_total_vids\',\'com_date_subscribed\',\'com_search_results\',\'com_search_results_in\',
        \'videos_being_watched\',\'latest_added_videos\',\'recently_added\',\'highest_rated\',\'most_discussed\',\'style_change\',
        \'rss_feed_latest_title\',\'rss_feed_featured_title\',\'rss_feed_most_viewed_title\',\'lang_folder\',\'reg_closed\',\'reg_for\',
        \'is_currently_closed\',\'added\',\'advertisements\',\'age\',\'approve\',\'approved\',\'approval\',\'books\',\'browse\',\'check_all\',
        \'click_here\',\'community\',\'contacts\',\'created\',\'date_joined\',\'dear\',\'des_title\',\'embed\',\'favourite\',\'favourited\',\'filter\',
        \'forgot\',\'groups\',\'hello\',\'hi\',\'home\',\'interests\',\'join_now\',\'join\',\'keywords\',\'latest\',\'leave\',\'most_members\',
        \'most_videos\',\'music\',\'no_user_exists\',\'no_video_exists\',\'occupations\',\'owner\',\'please\',\'privacy\',\'random\',\'rate\',
        \'related\',\'results\',\'relationship\',\'select\',\'times\',\'url\',\'verification\',\'viewing\',\'welcome\',\'of\',\'on\',\'ratings\',
        \'show_all\',\'signupup\',\'subscriptions\',\'time\',\'top\',\'tos_title\',\'proccession_wait\',\'group\',\'not_logged_in\',\'fill_auth_form\',
        \'admin_disabled_you\',\'recover_password\',\'submit\',\'reset_Fields\',\'admin_reg_req\',\'lang_change\',\'lang_changed\',\'lang_choice\',
        \'if_not_redir\',\'style_changed\',\'style_choice\',\'vdo_stills\',\'vdo_watch_video\',\'vdo_date_loc\',\'vdo_date_rec\',\'vdo_for_date\',
        \'vdo_comm_vote\',\'vdo_allow_com_vote\',\'vdo_dallow_com_vote\',\'vdo_update_title\',\'vdo_inactive_msg\',\'vdo_click_here\',
        \'vdo_continue_upload\',\'vdo_upload_step1\',\'vdo_upload_step2\',\'vdo_upload_step3\',\'vdo_select_vdo\',\'vdo_enter_remote_url\',
        \'vdo_enter_embed_code_msg\',\'vdo_enter_embed_code\',\'vdo_enter_druation\',\'vdo_select_vdo_thumb\',\'vdo_having_trouble\',
        \'vdo_if_having_problem\',\'vdo_clic_to_manage_all\',\'vdo_rawfile\',\'vdo_video_upload_complete\',\'vdo_thanks_you_upload_complete_1\',
        \'vdo_thanks_you_upload_complete_2\',\'vdo_after_it_has_process\',\'vdo_embed_this_video_on_web\',\'vdo_copy_and_paste_the_code\',
        \'vdo_upload_another_video\',\'vdo_goto_my_videos\',\'vdo_sperate_emails_by\',\'vdo_personal_msg\',\'vdo_related_tags\',
        \'vdo_reply_to_this\',\'vdo_add_reply\',\'vdo_share_video\',\'vdo_about_this_video\',\'vdo_post_to_a_services\',\'vdo_commentary\',
        \'vdo_post_a_comment\',\'grp_add_vdo_msg\',\'grp_no_vdo_msg\',\'grp_add_to\',\'grp_add_vdos\',\'grp_name_title\',\'grp_tag_title\',
        \'grp_des_title\',\'grp_tags_msg\',\'grp_tags_msg1\',\'grp_url_title\',\'grp_url_msg\',\'grp_cat_tile\',\'grp_vdo_uploads\',
        \'grp_forum_posting\',\'grp_join_opt1\',\'grp_join_opt2\',\'grp_join_opt3\',\'grp_vdo_opt1\',\'grp_vdo_opt2\',\'grp_vdo_opt3\',
        \'grp_post_opt1\',\'grp_post_opt2\',\'grp_post_opt3\',\'grp_crt_grp\',\'grp_thumb_title\',\'grp_upl_thumb\',\'grp_must_be\',
        \'grp_90x90\',\'grp_thumb_warn\',\'grp_del_confirm\',\'grp_del_success\',\'grp_click_go_grps\',\'grp_edit_grp_title\',
        \'grp_manage_vdos\',\'grp_manage_mems\',\'grp_del_group_title\',\'grp_add_vdos_title\',\'grp_join_grp_title\',\'grp_leave_group_title\',
        \'grp_invite_grp_title\',\'grp_view_mems\',\'grp_create_grp_title\',\'grp_most_members\',\'grp_most_discussed\',\'grp_invite_msg\',
        \'grp_invite_msg1\',\'grp_invite_msg2\',\'grp_url_title1\',\'grp_invite_msg3\',\'grp_join_confirm_msg\',\'grp_join_msg_succ\',
        \'grp_click_here_to_go\',\'grp_leave_confirm\',\'grp_leave_succ_msg\',\'grp_for_approval\',\'grp_rm_videos\',\'grp_rm_mems\',
        \'grp_groups_title\',\'grp_joined_title\',\'grp_remove_group\',\'grp_bo_grp_found\',\'grp_joined_groups\',\'grp_owned_groups\',
        \'grp_edit_this_grp\',\'grp_topics_title\',\'grp_topic_title\',\'grp_posts_title\',\'grp_discus_title\',\'grp_author_title\',
        \'grp_replies_title\',\'grp_last_post_title\',\'grp_viewl_all_videos\',\'grp_add_new_topic\',\'grp_attach_video\',\'grp_add_topic\',
        \'grp_please_login\',\'grp_please_join\',\'grp_inactive_account\',\'grp_about_this_grp\',\'grp_no_vdo_err\',\'grp_posted_by\',
        \'grp_add_new_comment\',\'grp_add_comment\',\'grp_pls_login_comment\',\'grp_pls_join_comment\',\'usr_actiavation_msg\',\'usr_compose_msg\',
        \'usr_inbox_title\',\'usr_sent_title\',\'usr_to_title\',\'usr_or_select_frm_list\',\'user_attached_video\',\'usr_send_message\',
        \'user_no_message\',\'user_delete_message_msg\',\'user_forgot_message_2\',\'user_pass_reset_msg\',\'user_pass_forgot_msg\',
        \'user_reocover_user\',\'user_user_forgot_msg\',\'user_dashboard\',\'user_manage_prof_chnnl\',\'user_manage_friends\',\'user_prof_channel\',
        \'user_message_box\',\'user_new_messages\',\'user_goto_inbox\',\'user_goto_sentbox\',\'user_compose_new\',\'user_total_subs_users\',
        \'user_you_have\',\'user_your_vids_watched\',\'user_times\',\'user_you_have_watched\',\'user_channel_views\',\'user_channel_comm\',
        \'user_manage_prof\',\'user_you_created\',\'user_you_joined\',\'user_create_group\',\'user_manage_my_videos\',\'user_manage_my_channel\',
        \'user_manage_channel\',\'user_manage_my_contacts\',\'user_manage_favourites\',\'user_mem_login\',\'user_already_have\',
        \'user_forgot_password\',\'user_create_your\',\'user_valid_email_addr\',\'user_reg_msg_0\',\'user_reg_msg_1\',\'user_enter_text_as_img\',
        \'user_refresh_img\',\'user_thanks_for_reg\',\'user_email_has_sent\',\'user_and_activation\',\'user_details_you_now\',
        \'user_upload_share_vds\',\'user_make_friends\',\'user_send_messages\',\'user_grow_your_network\',\'user_make_customize\',
        \'user_to_upload_vid\',\'user_click_to_login\',\'user_view_my_channel\',\'user_email_settings\',\'user_usr_prof_chnl_edit\',
        \'user_personal_info\',\'user_gender\',\'user_display_age\',\'user_website_url\',\'user_eg_website\',\'user_prof_info\',\'user_education\',
        \'user_school_colleges\',\'user_occupations\',\'user_companies\',\'user_sperate_by_commas\',\'user_interests_hobbies\',
        \'user_upload_avatar\',\'user_channel_info\',\'user_channel_title\',\'user_channel_description\',\'user_channel_permission\',
        \'user_allow_comments_msg\',\'user_dallow_comments_msg\',\'user_allow_rating\',\'user_dallow_rating\',\'user_allow_rating_msg1\',
        \'user_dallow_rating_msg1\',\'user_channel_feature_vid\',\'user_select_vid_for_fr\',\'user_chane_channel_bg\',\'user_remove_bg\',
        \'user_currently_you_d_have_pic\',\'user_notify_me\',\'user_do_not_have_contact\',\'user_no_fav_video_exist\',\'user_have_no_vide\',
        \'user_add_contact\',\'user_dob\',\'user_movies_shows\',\'user_no_fr_video\',\'user_view_all_video_of\',\'user_subscribe_message\',
        \'user_subscribe_subject\',\'embed_code_invalid_err\',\'invalid_duration\',\'vid_thumb_change_err\',\'my_text_context\',
        \'profile_title\',\'profile_desc\',\'temp_file_load_err\',\'user_no_subscribers\',\'user_no_subscriptions\',\'confirm_del_video\',
        \'remove_fav_video_confirm\',\'ban_users\',\'user_have_no_playlists\',\'this_thing_added_playlist\',\'group_join_login_err\',
        \'terms_of_serivce\',\'arslan_hassan\',\'you_not_allowed_add_grp_vids\',\'sel_vids_updated\',\'you_cant_edit_group\',
        \'you_cant_invite_mems\',\'you_cant_moderate_group\',\'grp_details_updated\',\'you_cant_del_topic\',\'you_cant_del_user_topics\',
        \'topics_deleted\',\'you_cant_delete_grp_topics\',\'you_not_allowed_post_topics\',\'you_cant_add_this_vdo\',\'video_added\',
        \'you_cant_del_this_vdo\',\'video_removed\',\'user_not_grp_mem\',\'user_already_group_mem\',\'invitations_sent\',
        \'you_not_grp_mem\',\'you_cant_delete_this_grp\',\'grp_deleted\',\'you_cant_del_grp_mems\',\'mems_deleted\',\'you_cant_del_grp_vdos\',
        \'phrase_code_empty\',\'phrase_text_empty\',\'name_has_been_added\',\'name_already_exists\',\'lang_doesnt_exist\',
        \'no_file_was_selected\',\'err_reading_file_content\',\'cant_find_lang_name\',\'cant_find_lang_code\',\'no_phrases_found\',
        \'language_already_exists\',\'error_while_upload_file\',\'lang_regex_empty\',\'lang_code_already_exist\',\'perm_code_empty\',
        \'perm_name_empty\',\'perm_already_exist\',\'perm_type_not_valid\',\'perm_added\',\'perm_deleted\',\'perm_doesnt_exist\',
        \'admin_panel\',\'moderate_videos\',\'moderate_users\',\'revert_back_to_admin\',\'more_options\',\'downloading_string\',
        \'download_redirect_msg\',\'profile_details\',\'update_profile\',\'user_bg_img\',\'please_enter_bg_color\',\'bg_repeat_type\',
        \'fix_bg\',\'video_info_all_fields_req\',\'update_group\',\'grp_info_all_fields_req\',\'click_here_to_recover_user\',
        \'click_here_reset_pass\',\'howdy_user\', \'friend_requests\',\'after_meny_guest_msg\',\'being_watched\',\'website_members\',
        \'guest_homeright_msg\',\'reg_for_free\',\'rand_vids\',\'t_10_users\',\'pending\',\'confirm\',\'no_contacts\',\'you_dont_hv_any_grp\',
        \'you_dont_joined_any_grp\',\'leave_groups\',\'manage_grp_mems\',\'pending_mems\',\'active_mems\',\'disapprove\',\'manage_grp_vids\',
        \'pending_vids\',\'no_pending_vids\',\'no_active_videos\',\'active_videos\',\'search_for_s\',\'if_you_already_hv_account\',
        \'signup_message_under_login\',\'new_mems_signup_here\',\'register_as_our_website_member\',\'video_complete_msg\',
        \'upload_right_guide\',\'report_this_user\',\'add_to_favs\',\'share_this\',\'uploaded_by_s\',\'click_to_download_video\',
        \'marked_as_spam_comment_by_user\',\'user_commented_time\',\'topic_icon\',\'group_options\',\'group_owner\',\'total_mems\',
        \'total_topics\',\'grp_url\',\'more_details\',\'view_all_mems\',\'view_all_vids\',\'topic_title\',\'last_reply\',\'topic_by_user\',
        \'no_topics\',\'last_post_time_by_user\',\'profile_views\',\'last_logged_in\',\'last_active\',\'total_videos_watched\',\'view_group\',
        \'show_hide\',\'are_you_sure_rm_grp\',\'are_you_sure_del_grp\',\'change_bg\',\'video_playlists\',\'add_contact_list\',\'topic_post\',
        \'invite\',\'lang_has_been_activated\',\'lang_has_been_deactivated\',\'lang_default_no_actions\',\'coments_disabled_profile\',
        \'chane_lang\',\'recent\',\'commented\',\'no_new_subs_video\',\'pending_requests\',\'required_fields\',\'please_enter_remote_file_url\',
        \'upload_videos_can_be\',\'photo_non_readable\',\'wrong_mime_type\',\'photo_tags\',\'no_upload_opt\',\'uploaded\',\'upload_desktop_msg\',
        \'embed_video_msg\',\'most_downloaded\',\'total_videos\',\'upload_right_guide_vid\',\'collect_items_deleted\',\'rand_photos\',
        \'watch_video_page\',\'watch_on_photo_page\',\'found_no_videos\',\'found_no_photos\',\'this_video_found_in_no_collection\',
        \'more_from\',\'this_collection\',\'channel_account_settings\',\'user_doesnt_any_collection\',\'total_collections\',\'total_photos\',
        \'comments_made\',\'tp_del_confirm\',\'you_need_owners_approval_to_view_group\',\'please_enter_confimation_ode\',
        \'vdo_brd_confidential\',\'please_provide_valid_userid\',\'user_has_created_new_group\',\'total_members\',\'user_has_joined_group\',
        \'activity\',\'feed_has_been_deleted\',\'you_cant_del_this_feed\',\'group_is_public\',\'collection_thumb\',\'edit_type_collection\',
        \'view_all\',\'you_dont_have_any_videos\',\'update_blocked_use\',\'group_is_private\',\'block_user\',\'send_message\',
        \'you_not_grp_mem_or_approved\',\'download\',\'flag_video\',\'upload_beats_guide\',\'contact\',\'no_collection_upload\',
        \'upload_in_progress\',\'complete_of_video\',\'agree\',\'terms\',\'and\',\'policy\',\'edit_video\',\'del_video\',\'last_one\',\'subscribe_btn\',
        \'play\',\'no_vid_in_playlist\',\'anonymous\',\'please_enter_collection_name\',\'select_collection\',\'vdo_inactive\',
        \'photo_tags_error\',\'photo_tags_err\'
        );';
        self::query($sql);
    }
}